### ISSUE TITLE
Explain how to add existing data (from IPFS, AWS, Google Drive, etc) to Filecoin.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#100]
In some cases, users will be coming to Filecoin from other storage solutions (i.e. not starting from scratch with their data storage). In these cases, users will want to know how to ingest their data into Filecoin all at once. We should prepare a guide that shows how to do this.

Title: "Initial data ingest"
- For those who are transferring data over from an existing storage solution

Some areas to cover/open questions:
- Note some of the particulars of online deal-making with Lotus, e.g. your node must be running in the background the whole time, how many deals can be made at once, can you import all data at once and let it run until deals are made?
- Is Lotus the right solution for this or should we be recommending people use Powergate instead?
- Provide a code/shell/script example of commands you would run to do this initial data ingest
- Provide examples of data ingest from various services we expect users to be using, e.g. IPFS, AWS S3 and AWS Glacier

**Comment by johndmulhausen** [comment]
Closing per Pooja "nice to have" - do if we're seeing interest someday
