### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by DSBUGAY2** [filecoin-project/filecoin-docs#1013]
### Who

Grant https://gitcoin.co/grants/3364/blockscout
Tweet https://twitter.com/blockscoutcom/status/1427671538459938821

### What

Receiving an error on twitter verification 

### Why

__Originally posted by @andogro in https://github.com/gitcoinco/web/issues/9366__

**Comment by johnnymatthews** [comment]
Looks like this was created by mistake. Closing.
