### ISSUE TITLE
Add Intel processor to the list of examples for hardware configurations

### ISSUE THREAD

**Issue by Stefaan-V** [filecoin-project/filecoin-docs#1018]
Is there an item missing from Filecoin documentation that would be helpful to you? Please use this template to let us know!

**What's the subject of the item you're requesting?**

Update the following page by adding a tested Intel architecture here:

https://docs.filecoin.io/mine/mining-architectures/#protocol-labs-example-architecture

Content

![Screen Shot 2021-08-23 at 6 54 40 PM](https://user-images.githubusercontent.com/83617805/130545933-83a9b508-35cc-4d1c-86cb-7b96531ad6bc.png)

**What's the content of the item you're requesting?**
Updated rows for Intel 

**What will the user know how to do after going through this item?**
What Intel processor to chose.

**Would you be interested in helping create this item?**

_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away. Or if you'd like to brainstorm with other contributors and work in collaboration to create this content, that's great too; just say so._

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by Stefaan-V** [comment]
Verified and tested by Intel in a Filecoin environment

**Comment by johnnymatthews** [comment]
I'm confused. The link you supplied, and the table you screenshotted, both show Intel CPUs. Are there other test setups you're expecting to see?

**Comment by Stefaan-V** [comment]
Hi Johnny, 

The link I shared to the documentation only shows AMD processors, not Intel.

link: https://docs.filecoin.io/mine/mining-architectures/#protocol-labs-example-architecture

The picture I added is an updated picture with Intel processors that were tested by Intel. 

We would like to expand the table in the documentation page (link) with the tested Intel processors please.

**Comment by johnnymatthews** [comment]
Oh I see. So we need to add the information listed in the table you screenshotted to the existing table. Gotcha.
