### ISSUE TITLE
Add `fee address` to dedicated market not for `DealPublishControl`.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/filecoin-docs#1028]
Adding the Fee address to the dedicated market node resolved this. Probably need this added to the docs.

_Originally posted by @stuberman in https://github.com/filecoin-project/lotus/issues/7168#issuecomment-909773492_

**Comment by jennijuju** [comment]
@dayou5168 could you please work on this next week?

**Comment by dayou5168** [comment]
sure

**Comment by johnnymatthews** [comment]
Added you as an assignee @dayou5168. :)
