### ISSUE TITLE
Potentially remove filwallet.io for security flaws.

### ISSUE THREAD

**Issue by jeebster** [filecoin-project/filecoin-docs#1030]
**URL of the page in question:**
https://docs.filecoin.io/reference/#wallets

Who has audited [filwallet.io](https://fivetoken.io/) - now fivetoken.io? It is not flagged **recommended** but lives in the [Wallet (Audited)](https://docs.filecoin.io/reference/#wallets-audited) section. Their web browser extension is riddled with security issues via logging data to console, most notably [leaking wallet private key in console](https://github.com/FiveToken/FiveToken-Wallet-Chrome-Extension/issues/2).

Please consider removing this to the [Other Wallets](https://docs.filecoin.io/reference/#other-wallets) section until the issues are resolved

**Comment by johnnymatthews** [comment]
We're looking into this now. Thanks for raising.

**Comment by jeebster** [comment]
> We're looking into this now. Thanks for raising.

Sure thing; happy to provide steps to reproduce or screenshots of a throwaway wallet if necessary
