### ISSUE TITLE
https://linksharing.samsungcloud.com/hzPeiyWQoMpl

### ISSUE THREAD

**Issue by farisei77** [filecoin-project/filecoin-docs#1031]
https://linksharing.samsungcloud.com/hzPeiyWQoMpl

_Originally posted by @Vanina095 in https://github.com/tronprotocol/documentation/issues/399#issuecomment-912959000_

**Comment by Kowaczek** [comment]
[REP-BFG-Token-2021-09-19.pdf](https://github.com/filecoin-project/filecoin-docs/files/7350287/REP-BFG-Token-2021-09-19.pdf)
