### ISSUE TITLE
Add Documentation for lotus v1.11.2

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/filecoin-docs#1033]
- [ ] https://github.com/filecoin-project/lotus/pull/6097
- [ ] https://github.com/filecoin-project/lotus/pull/7027
- [ ] https://github.com/filecoin-project/lotus/pull/6927
- [ ] https://github.com/filecoin-project/lotus/pull/6803

**Comment by BlocksOnAChain** [comment]
@jennijuju should this be assigned to  Stewards docs team or someone on the devs side?

**Comment by dayou5168** [comment]
I will do it.
