### ISSUE TITLE
Update the Filecoin logo across the site.

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/filecoin-docs#106]
Update Filecoin logos (in many files/formats) w/ new blue. 

See also #11 re branding updates more generally.

**Comment by har00ga** [comment]
Where can I get the files required to make this change @terichadbourne?

**Comment by terichadbourne** [comment]
When I did it originally I took as many logo files in the right formats as I could from the Google Drive branding folder for Filecoin. However, the ones I see there are still in the old teal color: https://drive.google.com/drive/folders/1Cr8tRQDRup2tHH05cxRuNR8QT_UTpKF7?usp=sharing

@akrych and @eronne are the folks most likely to be able to help track down new versions - I've pinged them in the PL slack design channel to see if the file structure changed. 

I converted some manually to the right dimensions and file types for the gazillion different logo versions (favicon, various brands of mobile devices, etc.) and asked @akrych to create the rest for me where I didn't have an appropriate editor. Took me a few tries to find the gazillion places where there are various versions of the logo. IIRC they're spread across `.vuepress/public/` and `.vuepress/public/images`. 

These are the ones I needed help with last time and where I went to ask for it: https://github.com/protocol/design-shop/issues/287

**Comment by jesseclay** [comment]
Added the new logo to that folder!

**Comment by har00ga** [comment]
Thank you both:)

**Comment by johnnymatthews** [comment]
@cwaring I'm assuming this got done? Looks done to me.

**Comment by cwaring** [comment]
Still on TODO as the theme palette also needs to be updated, best to leave it open for now.

**Comment by johndmulhausen** [comment]
Closing in favor of #11 which would encapsulate this change.
