### ISSUE TITLE
Add a callout to inform users about the benefits of encryption.

### ISSUE THREAD

**Issue by sunitaparbhu** [filecoin-project/filecoin-docs#1078]
Regarding: https://docs.filecoin.io/get-started/store-and-retrieve/store-data/#things-to-note

I think the document should be written with a default step of encrypting the data. And then a suggestion to drop encryption if you don't care about the privacy of the stored data. 

Sometimes you need to state content which is fairly obvious (e.g. later in the tutorial you say "There are two parts to a Filecoin address: the public address and the private key. You can freely share your public address with anyone, but you should never share your private key...")

Encrypting data is important to most people. It's a good practice. And mistakes by rookies who don't encrypt would harm the Filecoin project's reputation.

**Comment by johnnymatthews** [comment]
## Tasks

- [ ] Add a callout suggesting that users may encrypt their content if they're planning to store private data.

**Comment by momack2** [comment]
I think a small how-to tutorial on various ways to encrypt data before uploading to a Filecoin SP would be useful (though agree not homed in the quickstart!). Might this be a good issue for a launchpad participant to pick up? If so, can we add "good first issue"?

**Comment by johnnymatthews** [comment]
> Might this be a good issue for a launchpad participant to pick up? 

For sure! Should probably get an encryption expert to go over the PR before we merge it too. We don't wanna be recommending the wrong encryption tools, or the right tools with the wrong method, or something like that.
