### ISSUE TITLE
Define estimated mining rewards in FIL.

### ISSUE THREAD

**Issue by SKS5115** [filecoin-project/filecoin-docs#1086]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
_e.g. https://docs.filecoin.io/introduction/usage/_

**What's wrong with this page?**
_Shows all the parameters but not numbers or example or use cases.

**What would you like to have changed/amended/fixed in order to make things right?**
_couldn't find the amount of Fill that I can earn if I'm invest in a mining node, or an example with real numbers

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._ 

I'm a industrial engineer, I'll like to create a cashflow for this, its not an issue,  but I need the data! , people needs to know at what point/rate they gonna earn money and how much. 

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by SKS5115** [comment]
Hi Johnny, I'll like to help figure out a function to estimate how much money a node can produce, lets make a cash flow, with all the values stated in Fill per Gig. I just need more data about how the rewards work

**Comment by johnnymatthews** [comment]
Starboard Ventures recently shipped [this Filecoin storage provider return calculator](https://sproi.starboard.ventures/) that might be of interest to you.
