### ISSUE TITLE
Use brand-book to correct the style and themeing of docs.filecoin.io.

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/filecoin-docs#11]
Per the convo in #8, we'll return to a discussion on the color scheme after Filecoin's new brand book is released.

**Comment by terichadbourne** [comment]
@mishmosh Do you know if the brand book has materialized, given that the new website was launched? Or are we still waiting on that?

**Comment by mishmosh** [comment]
There is a new [brand book](https://docs.google.com/presentation/d/1bOG02pRLR58Rn3GtqCWms2AURlcVIY2bnnyontnjZ8E/edit#slide=id.g716d6e8d16_0_82) just released.

**Comment by cwaring** [comment]
👋🏻 @ericronne where can we find the latest brand book for Filecoin too apply these changes?

**Comment by ericronne** [comment]
Scroll to the second fat bar on the master **[PL brand directory](https://www.figma.com/proto/zwiBoppEK16FXV89bqDVgX/PL-%2B-project-branding-master-index?node-id=0%3A6&scaling=min-zoom)**. The password you'll need is there on the bar.

**Comment by ericronne** [comment]
Note: Design is about to tackle this refresh, following styles outlined in the [Filecoin brand sheet](https://www.figma.com/proto/SujAdL1z8HBPHUuQTxExbv/Filecoin-brand-sheet?node-id=22%3A2).

**Comment by mishmosh** [comment]
Awesome!

**Comment by ericronne** [comment]
Given that it's a docs site, a minimalist vibe seems fitting (just one text-link color, eg 😅), but with a bit of personality.

The current look and feel is gorgeous, but matches [Filecoin Grants.](https://grants.filecoin.io/) I'd propose that we let the grants program own that aesthetic outright.

**Comment by johndmulhausen** [comment]
Closing as we have now shipped our new themed site!
