### ISSUE TITLE
Update build section

### ISSUE THREAD

**Issue by longfeiWan9** [filecoin-project/filecoin-docs#1102]
The Filecoin ecosystem is growing rapidly as well as its toolings and infrastructures to support developer building on Filecoin, but I have noticed that our docs of `build` is a bit behind the progress of our infrastructures. For examples,
+ Hosted Powergate is not supported anymore.
+ Instruction of how to start building on Filecoin is not very clear and also outdated.
+ web3.storage and nft.storage is advancing readily, but not showing in our docs.

Since Filecoin docs will be the place where most developers will go to find appropriate tools to develop their application on Filecoin. So I would like to propose to put some effort to update `build` section of Filecoin docs to give clearer instruction and more explanation on how to start and what to use to develop on Filecoin. 
The followings are my proposed areas to start first:
+ Remove Hosted Powergate [PR-1101](https://github.com/filecoin-project/filecoin-docs/pull/1101)
+ Update readme of Build page for a clearer instructions (Will create PR soon)
+ Restructure sidebar after removing lotus docs separate repo: [Issue-1071](https://github.com/filecoin-project/filecoin-docs/issues/1071)
+ Add nft.storage (Will create PR soon)
+ Add web3.storage (Will create PR soon)

Any thoughts and recommendations are welcome. @mishmosh @johnnymatthews

**Comment by johnnymatthews** [comment]
> Remove Hosted Powergate PR-1101
> Update readme of Build page for a clearer instructions (Will create PR soon)
> Restructure sidebar after removing lotus docs separate repo: Issue-1071
> Add nft.storage (Will create PR soon)
> Add web3.storage (Will create PR soon)

Pretty sure all these points got address, no? Closing for now.
