### ISSUE TITLE
Web development

### ISSUE THREAD

**Issue by Prince-Tanaka-XI** [filecoin-project/filecoin-docs#1105]
Hi, if you could add a video on how to upload a website step by step and how to make the website in such a way that it shows correctly. Also do you offer web site development for clients?

**Comment by johnnymatthews** [comment]
Filecoin isn't the best solution to _host_ a video. Take a look at the [IPFS Website tutorial series](https://docs.ipfs.io/how-to/websites-on-ipfs/single-page-website/) to using IPFS to host a website. Or take a look at [Fleek.co](https://fleek.co/) if you want to build a website that runs on IPFS and it backed up to Filecoin.

Actually serving a website directly from Filecoin is not the way to go.
