### ISSUE TITLE
keep it simple 

### ISSUE THREAD

**Issue by Tristantro** [filecoin-project/filecoin-docs#1123]
why in gods name have you made it so hard to store filecoin in some wallet where oneself owns the key. i mean its literally ridiculous and useless

**Comment by johnnymatthews** [comment]
If you fancy [Lotus-lite](https://lotus.filecoin.io/docs/set-up/lotus-lite/) then you can follow the [Manage FIL](https://lotus.filecoin.io/docs/set-up/install/) guide to learn how to create an address and manage your private keys on your own.

Obviously the standard _don't share your private keys etc, etc_ warning applies here. If you run into any major issues, checkout the [Lotus discussions tab in GitHub](https://github.com/filecoin-project/lotus/discussions) or [Filecoin Slack](https://filecoin.io/slack/).

**Comment by Tristantro** [comment]
sounds good johny,

i see if i can manage, you know im from the70´s and edu in concrete construction, not really a cpu programmer dude or even good on cpu..

i remember "press play on tape" but today the tape runs to much on auto..

i tried to setup a developer enviroment on github because of a learning program to see if i could learn to code, im still stuck on github, its a freaking jungle out there

thanx bro !

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
D. tirsdag den 30. november 2021 kl. 20:18, Johnny skrev ***@***.***>:
