### ISSUE TITLE
Replace filwallet.ai with FiveToken wallet.

### ISSUE THREAD

**Issue by luckyceline** [filecoin-project/filecoin-docs#1145]
For this page:  https://docs.filecoin.io/reference/#other-wallets 
need to replace filwallet.ai with Fivetoken.io. 
There's no more Filwallet in Filecoin ecosystem, and FiveToken is an independent team which based in Singapore. 

More info about Fivetoken:
Website: fivetoken.io 
Twitter: @fivetokenio
Github: https://github.com/FiveToken

fyi, Fivetoken is under auditing now and we will update the community once the audit done

**Comment by johnnymatthews** [comment]
Thanks for the heads up. We'll remove filwallet.ai since that wallet is dead. Please comment in this issue when the Fivetoken wallet has been audited and we'll add the link to this page.
