### ISSUE TITLE
Research Algolia ability to build cross-site indexes

### ISSUE THREAD

**Issue by Annamarie2019** [filecoin-project/filecoin-docs#1174]
Problem: Content referenced in the Storage and Retrieval guide now only exists in Lotus docs, and people are having trouble finding that content from the [docs.filecoin.io](http://docs.filecoin.io/)

Solution: Find out if [Algolia](https://www.algolia.com) can fix that by building cross-site indexes.

**Comment by BlocksOnAChain** [comment]
@johndmulhausen how are we looking on this one?

**Comment by Annamarie2019** [comment]
@johnnymatthews  Looks like this one should be a P1, since [#27](https://github.com/filecoin-project/lotus-docs/issues/27) is a P1 and is dependent on this. I would change it, but the labels field isn't responding to me.

**Comment by walkerlj0** [comment]
@johnnymatthews @Annamarie2019 @BlocksOnAChain I did this exact thing at my last company, would be happy to give a walkthough of what this entails. Basically to do cross-site indexes, you need to do two things:


1) Configure/ create an instantsearch JS widget, esp if you aren't using the same site for all docs: https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/

2) Configure the crawler for each of the sites that you want to search: https://www.algolia.com/products/search-and-discovery/crawler/. This can all be done in one configuration file that is hosted on Algolia

I am also interested in incorporating this for the learning site once I decide on another platform.

**Comment by BlocksOnAChain** [comment]
@walkerlj0 thanks so much for you feedback and ideas here.  @johndmulhausen sounds like something we can explore?

**Comment by johnnymatthews** [comment]
We've now implemented cross-site search!

![image](https://user-images.githubusercontent.com/9611008/165663169-91f063d2-bbdd-4192-b3f5-375536e38d25.png)
