### ISSUE TITLE
External scripts being blocked by content security policy.

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/filecoin-docs#1211]
I spotted this error in the console in both Safari and Chrome: 

`Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=G-H3D2P5EGFR' because it violates the following Content Security Policy directive: "script-src 'self' https://*.netlify.app 'sha512-RBYr6Ld4w1yVqaACrgrBLQfPgGhj/1jyacA74WxJ1KM6KVcSWymwrdDwb3HDcdpwiNJ5yssot1He0U9vXoQVlg==' 'sha256-aWZ3y/RxbBYKHXH0z8+8ljrHG1mSBvyzSfxSMjBSaXk='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

(Same is true on lotus.filecoin.io, I note)

**Comment by johnnymatthews** [comment]
Well that's not great. Thanks for raising! We're looking at this now.
