### ISSUE TITLE
Review the Filecoin implementations table.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1219]
The Filecoin implementations table in https://github.com/filecoin-project/filecoin-docs/blob/main/content/en/get-started/overview/index.md#filecoin-implementations might be out of date. We need to speak with dev-rel members from each team and find out what features are available.

![image](https://user-images.githubusercontent.com/9611008/163009852-29d6cd22-4577-4bda-b185-21230cf6eb57.png)

**Comment by jenks-guo-filecoin** [comment]
Happy to take this on @johnnymatthews. Will report back in a week.

**Comment by johnnymatthews** [comment]
Nice, it's all yours @jenks-guo-filecoin!

**Comment by jenks-guo-filecoin** [comment]
I have picked this up again, will aim to get this updated before end of next week.

**Comment by ElPaisano** [comment]
@johnnymatthews I can work on this one.

Who would be my go to dev rel folks on each team for this?
