### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#1248]
Let's add a README to this repo. It can be modelled after the ipfs docs readme as they share the same platform. https://github.com/ipfs/ipfs-docs/blob/main/README.md

**Comment by johnnymatthews** [comment]
Let's include instructions for building a publishing the site too:

```shell
git clone https://github.com/filecoin-project/filecoin-docs
cd filecoin-docs
npm install

# To preview the build, run:
npm run start # Open browser to http://localhost:1313

# To publish the site run:
npm run build # The project will be built and saved to /public
```

**Comment by dawnkelly09** [comment]
@johnnymatthews I'm just seeing this suggestion here but I can def add that in. If one of you can please look at my PR and answer those questions in the code comments (search for "TO-DO") then I will work on those items plus your publishing addition tomorrow. Thank you!
