### ISSUE TITLE
Add customer service links for wallets

### ISSUE THREAD

**Issue by dawnkelly09** [filecoin-project/filecoin-docs#1256]
Add links to individual customer service pages for the wallet list where possible. 

https://docs.filecoin.io/about-filecoin/managing-assets/

RE: https://filecoinproject.slack.com/archives/C023PPKBM6Z/p1652299629096379?thread_ts=1652297991.573119&cid=C023PPKBM6Z

**Comment by Annamarie2019** [comment]
Research where to contact customer service or direct questions: For example, if you google Glif Web Wallet you'll see that there is more information on [GitHub](https://github.com/glifio/wallet). See if that is the best place...or are there others?
