### ISSUE TITLE
Docs reorg - Developers section: write content

### ISSUE THREAD

**Issue by dawnkelly09** [filecoin-project/filecoin-docs#1262]
Child of #1254 

- [x] Write the content (use a Google Doc for faster editing)
  - [x] Overview
  - [x] Application data
  - [x] Build on Filecoin L1

### Section outline

- Developers
  - Getting started 
    - Hello World tutorial link
    - IPFS & Filecoin Application Design link
  - Overview 
    - What Filecoin brings to applications 
    - IPFS & Filecoin in application design
    - Using Filecoin in other chains (Polygon, Harmony, etc.)
  - Application data
    - NFT data: Use NFT.storage
    - General application data
      - Storage helpers: Web3.storage, Estuary, etc.
      - Manage your own storage deals with raw libraries: Textile Powergate (choose specific SPs, customize pricing, etc.)
    - Advanced application design: dbs, etc.
  - Build on Filecoin L1 (for wallets, exchanges, devtools)
    - Hello world tutorial (extremely simple version that uses a hosted node, something that can be completed in <15 mins)
    - Comprehensive tutorial (maybe point to longfei's Building with Filecoin API tutorial)
    - Signing libraries, devnets, hosted node providers

**Comment by jenks-guo-filecoin** [comment]
Looking forward to get cracking with this @dawnkelly09 @mishmosh. Do we need a bit more discussion next week before we start the google docs? I could organise a meeting for us.

**Comment by dawnkelly09** [comment]
@jenks-guo-filecoin I feel like I definitely need guidance as to what to keep from the current docs vs how much new content is needed, etc.

**Comment by mishmosh** [comment]
Let's set aside some time in our weekly call to discuss. I created this [GDoc](https://docs.google.com/document/d/1er7ogbVN6G_4Wb3p8GRbsX3ZASaB6BuA-7tz-68STzc/edit#) for drafting and stubbed out the outline from #1253. @jenks-guo-filecoin @dawnkelly09 if you could give a skim before today's call that would be great.

**Comment by jenks-guo-filecoin** [comment]
Thanks @mishmosh for getting this started. Will discuss in the meeting shortly.

**Comment by mishmosh** [comment]
Done!
