### ISSUE TITLE
Docs reorg - Developers section: open subsection PRs

### ISSUE THREAD

**Issue by dawnkelly09** [filecoin-project/filecoin-docs#1264]
Child of #1254 

- [x] PR for each subsection (Overview, Application data, etc.) to `feat/developers-section-reorg` branch

### Section outline

- Developers
  - Getting started 
    - Hello World tutorial link
    - IPFS & Filecoin Application Design link
  - Overview 
    - What Filecoin brings to applications 
    - IPFS & Filecoin in application design
    - Using Filecoin in other chains (Polygon, Harmony, etc.)
  - Application data
    - NFT data: Use NFT.storage
    - General application data
      - Storage helpers: Web3.storage, Estuary, etc.
      - Manage your own storage deals with raw libraries: Textile Powergate (choose specific SPs, customize pricing, etc.)
    - Advanced application design: dbs, etc.
  - Build on Filecoin L1 (for wallets, exchanges, devtools)
    - Hello world tutorial (extremely simple version that uses a hosted node, something that can be completed in <15 mins)
    - Comprehensive tutorial (maybe point to longfei's Building with Filecoin API tutorial)
    - Signing libraries, devnets, hosted node providers

**Comment by dawnkelly09** [comment]
Added needed folders and files for the new doc org structure on the feat/developers-section-reorg branch. Did not open PR as I didn't think we were ready for these to go to main just yet.

**Comment by mishmosh** [comment]
Closing as these were completed incrementally.
