### ISSUE TITLE
Update devnet info with nerpa devnet

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#128]
There’s an updated devnet (called nerpa): https://gist.githubusercontent.com/travisperson/83bcc914a02a12ae9bdf19fe40f7e35a/raw/564b4e46937cf787a612b593bf4fe57afb94c1a7/gistfile1.txt

Please update the instructions in the “Connecting to the network” page, replacing the existing Devnet instructions with the new instructions.

**Comment by pooja** [comment]
Completed in this PR: https://github.com/filecoin-project/filecoin-docs/pull/133

**Comment by mishmosh** [comment]
There are 2 clarifications we should make (regarding access to report outages, & who nerpa devnet is for). I added them as comments to #133.

**Comment by har00ga** [comment]
Resolved with #135
