### ISSUE TITLE
Quickstart tutorial 'Validate an Address' code snippets include invalid trailing comma in JSON request body 

### ISSUE THREAD

**Issue by jsolly** [filecoin-project/filecoin-docs#1359]
### Context 
In the [Quickstart Tutorial](https://docs.filecoin.io/build/get-started/#validate-an-address) the Validate Address section (steps 2 and 3) include a trailing comma. According to the [JSON spec](https://www.json.org/json-en.html) trailing commas are not allowed.

Including the comma results in an empty response body with a 400 error (bad request). When I remove the trailing comma, the response comes back as expected.

### Suggest change
Remove trailing comma from the end of `params` like I've done below.

```json
  body: `{
      "jsonrpc": "2.0",
      "id": 0,
      "method": "Filecoin.WalletValidateAddress",
      "params": ["f1ydrwynitbbfs5ckb7c3qna5cu25la2agmapkchi"]
  }`
```

### Additional Thoughts
I checked the rest of the tutorial and it appears that it is only these two steps that include the trailing comma, but it might be smart to check code snippets across all the docs to make sure there are no trailing commas inside JSON strings.

**Comment by jsolly** [comment]
Feel free to assign me this issue and I will open a PR removing the trailing comma from these two steps. I would love to contribute!

**Comment by johnnymatthews** [comment]
Ah that's frustrating, I wonder how they got there! If you've got time @jsolly PRs are always welcome! If not, I'll tackle this later on this evening.

**Comment by jsolly** [comment]
@johnnymatthews 
Here is the PR closing this issue -> https://github.com/filecoin-project/filecoin-docs/pull/1360

**Comment by jsolly** [comment]
Fixed in https://github.com/filecoin-project/filecoin-docs/pull/1360 

Verified on https://docs.filecoin.io/build/get-started/#validate-an-address

Trailing commas no longer present!
