### ISSUE TITLE
Matrix link no longer points to a room.

### ISSUE THREAD

**Issue by TimDaub** [filecoin-project/filecoin-docs#1377]
- https://github.com/filecoin-project/filecoin-docs/blob/80c929cfe5336bc0941be35de686c8a198fd8039/content/en/about-filecoin/chat-and-discussion-forums.md?plain=1#L18

<img width="931" alt="Screenshot 2022-09-08 at 16 39 34" src="https://user-images.githubusercontent.com/2758453/189151371-daed321e-7638-4655-824d-9fb7d76c16ab.png">

**Comment by TimDaub** [comment]
<img width="587" alt="Screenshot 2022-09-08 at 16 40 54" src="https://user-images.githubusercontent.com/2758453/189151717-bcf99d9d-5451-44a5-87aa-46acfeca3d8a.png">

same for the matrix link

**Comment by johnnymatthews** [comment]
The Slack link redirects properly for me:

![image](https://user-images.githubusercontent.com/9611008/189958333-9c00fe40-9256-49c1-8990-b138a38cbe38.png)

Can you try again in a private browser/with extensions turned off. There might be something blocking it in there.

I believe that the Matrix chatroom has closed. I'll doublecheck. If it is in fact closed, I'll remove this link.

**Comment by johnnymatthews** [comment]
Yeahp, looks like that Matrix room is no more. Ripping it out now.
