### ISSUE TITLE
Rename Build > Developers

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#1410]
Rename Build to Developers, which is a more popular industry standard and avoids confusion with building hardware/storage rigs.

An incomplete list of files to be modified:
- menus.en.toml
- the frontmatter of every file in the /build folder
- search the repo for links to `/build` and rename them

@johnnymatthews anything else we're missing?

**Comment by johnnymatthews** [comment]
Nope, that's about everything!

**Comment by johnnymatthews** [comment]
Addressed in https://github.com/filecoin-project/filecoin-docs/issues/1253
