### ISSUE TITLE
Contradiction in GasPremium lower bound in filecoin-docs/content/en/about-filecoin/how-filecoin-works.md 

### ISSUE THREAD

**Issue by dudzicz** [filecoin-project/filecoin-docs#1421]
In the description of __GasPremium__ on line 69, it is specified that 
> [ __GasPremium__] is measured in units of attoFIL/Gas and can be as low as 1 attoFIL/Gas.

However, the remark on line 78, mentions that 
> an important detail is that a message will always pay the _burn fee_, regardless of the _GasFeeCap_ used. Thus, a low _GasFeeCap_ may result in a reduced _GasPremium_ or even a negative one!

It appears unclear what is the actual lower bound of  __GasPremium__  either 1 attoFIL/Gas or possibly -\infty  attoFIL/Gas.

**Comment by longfeiWan9** [comment]
The description for the lower bound of GasPremium is actually right. When you construct a message, you will need to specify GasPremium which will be used to calculate the storage provider's reward, like `storage provider's reward = GasLimit * GasPremium`. This GasPremium can be set as low as 1 attoFIL/GAS, which means the storage provider should get tips for processing this message. 

If the message sender did not set enough `GasFeeCap * GasLimit` to cover the burned fee which is `GasUsage * BaseFee`, then the storage provider's reward (GasLimit * GasPremium) will be reduced or maybe even a negative when VM processes this message. 

Maybe this causes confusion, it is the storage provider's reward (GasLimit * GasPremium) will be reduced during the GAS calculation. But the message sender should set proper GasPremium for rewarding storage providers, and it can be as low as 1 attoFIL/Gas.
