### ISSUE TITLE
Generate JSON-RPC docs to include FEVM features.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1459]
Issue https://github.com/filecoin-project/ref-fvm/issues/854 is tracking the Ethereum JSON-RPC implementation in Lotus.

## Top priority

Do these tasks before anything else.

- [x] Include all supported Eth methods within the `/reference/json-rpc` section of this repo.
- [ ] Each method includes:
    - [ ] A description.
    - [ ] Required input parameters.
        - [ ] Type of param, and a description of what it is.
    - [ ] The expected response.

## Secondary

Once the [Top priority](#top-priority) tasks have been achieved, let's focus on these issues.

- [ ] Each method includes:
    - [ ] A copy-and-pasteable curl example.
    - [ ] The actual response from a valid input as an example.

**Comment by ElPaisano** [comment]
@johnnymatthews is this still needed. I see there was a PR https://github.com/filecoin-project/filecoin-docs/pull/1458 that was worked on but then got closed?

**Comment by johnnymatthews** [comment]
We can close this one now.
