### ISSUE TITLE
Broken link: Get Building Overview

### ISSUE THREAD

**Issue by dawnkelly09** [filecoin-project/filecoin-docs#1465]
Build Directly on Filecoin link in the Get Started paragraph is taking users to the top of that same page rather than directing elsewhere

https://docs.filecoin.io/build/get-building/overview/

@mishmosh

**Comment by johnnymatthews** [comment]
Hmm, I'm not sure where this is meant to go. I'll remove that line for now. We really shouldn't have recursive links like this.
