### ISSUE TITLE
Allow for labels within sidebar menu.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1468]
The scope of our navigation is limited by the number of navigation levels we have. We currently have four levels:

1. The topbar.
2. The sidebar.
3. The menu items themselves.
4. The table of contents on each page.

![Untitled](https://user-images.githubusercontent.com/9611008/204660975-cf31e9a1-6127-40fe-9751-7a0ae9f7c478.png)

By adding unclickable labels into the sidebar, we'd be creating an entirely new level, without adding much complexity for the user:

![Untitled(1)](https://user-images.githubusercontent.com/9611008/204661205-671612b0-fe6e-4ccc-b74e-a52d25c4dc51.png)

This issue tracks the creation of a sidebar-label feature.

**Comment by jennijuju** [comment]
lgtm

**Comment by johnnymatthews** [comment]
Closes in https://github.com/filecoin-project/filecoin-docs/pull/1484.
