### ISSUE TITLE
Favicon doesn't render for the published docs site

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#147]
The production docs site doesn't include the favicon. The local testing version does. Requires a bug fix.

**Comment by cwaring** [comment]
Is this still an issue? I investigated (#138) and fixed (#139) the Chrome rendering problem earlier this week. LMK if I'm missing any additional details.

**Comment by pooja** [comment]
Hmm, I'm still seeing it. Should I do something differently in my setup?

![Screen Shot 2020-07-16 at 9 12 06 AM](https://user-images.githubusercontent.com/5668171/87695540-73a33200-c744-11ea-8d80-dd35f4119c03.png)

**Comment by terichadbourne** [comment]
Working for me in Chrome (favicon visible but not yet updated to new color scheme per #106): 

![image](https://user-images.githubusercontent.com/19171465/87821334-b0068900-c83d-11ea-8fe4-d6488554f78a.png)

**Comment by cwaring** [comment]
@pooja I suspect this is caching related, would you mind checking from an incognito window?

**Comment by pooja** [comment]
Ah yes, correct! Opening in an incognito window indeed works. Thanks team! Closing this one out.
