### ISSUE TITLE
Explain what payment channels are and how they work.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#149]
We need more information on how payment channels in Filecoin work, how to use them from Lotus (and possibly other implementations), and how to use payment channels in applications both in terms of use cases and through the API.

**Comment by mishmosh** [comment]
For the majority of storage and retrieval usage, the lotus & markets implementations are designed such that managing individual channels is largely internal to the node. Wallet, token, and other users would need to interact at the *payments* level but not payment channels.

**Comment by pooja** [comment]
Lotus exposes payment channels through its CLI and APIs, and it's a useful feature that we'd want to promote to any lotus users. It's also intended to be a top-level feature in Slate. The idea of individual transactions is useful, but the fact that Filecoin essentially allows subscription payments is a unique feature that we should document well and explain how it can be used in applications (it's especially valuable for developers).

**Comment by pooja** [comment]
[Here's an excellent overview](https://www.evernote.com/shard/s10/client/snv?noteGuid=135ecd3b-b743-4f6d-8943-e9c381fbf7df&noteKey=51f2120ace7d6ed6&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs10%2Fsh%2F135ecd3b-b743-4f6d-8943-e9c381fbf7df%2F51f2120ace7d6ed6&title=Filecoin%2527s%2Bexisting%2Bpayment%2Bchannels%2B-%2BFilecoin%2BRetrieval%2BMarket%2B-%2BConfluence) from a community member on how filecoin payment channels work.

cc @johnnymatthews
