### ISSUE TITLE
Explain what "Multisig" is, how it works, and why it's important.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#150]
Filecoin has multisig functionality. We should document what multisig is, how it works in Filecoin, and how to use it.

**Comment by johnnymatthews** [comment]
Do we have any existing docs for multisig? Failing that, anyone from the Lotus team that could explain things a bit here?

**Comment by pooja** [comment]
We do not have any existing docs for multisig to my knowledge. I think a quick chat with @arajasek might help clear things up here.

**Comment by johnnymatthews** [comment]
Gonna close this one since we've now got a page listing this stuff. https://docs.filecoin.io/get-started/lotus/multisig/#create-a-multsig-wallet
