### ISSUE TITLE
Have the sub-section headers link to whatever is the first page in the sub-menu.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#152]
In today's docs site, sub-section headers (e.g. "Start Building" in the screenshot below) are not clickable. There's no visual feedback that this is not the case, so users try to click on the headers to no avail.
![Screen Shot 2020-07-15 at 6 07 19 PM](https://user-images.githubusercontent.com/5668171/87614846-0cdf3380-c6c6-11ea-9388-8533c163665d.png)

We should make the headers clickable and have content on the section header page. But if we cannot do this, an interim solution is to gray out the section headers so that users don't try to click on them.

**Comment by johnnymatthews** [comment]
If these sub-section headers were clickable, then they'd each need a _landing page_. This would be great because it would need we wouldn't have to have pages like **Overview** or **Introduction**. It does increase the effort needed to complete this issue however.

**Comment by cwaring** [comment]
This issue is mostly a structural one and we need to ensure that we are consistent so that the interaction is clear. Many docs sites use label groupings to indicate a collection of topics that are not necessarily nested so I want to be sure that we don't lose this flexibility by enforcing an index pattern. Let's work towards a common approach for this during the restructure, I believe we can find a nice balance with an additional style refactor :)

**Comment by johnnymatthews** [comment]
How about we **don't** make sub-section header clickable right now. We continue to use _faux-landing pages_ like **Overview** or **Introduction**. Then, once the mainnet launch is behind us and everyone has more breathing room, we take a look at this again.

### Or

We can have the sub-section headers link to whatever is the first page in the sub-menu. So in @pooja's screenshot above, **START BUILDING** will link to **Interacting with the network**, **CORE PRODUCTS** will link to **Filecoin-backed IPFS Pinning Services**, **DEVELOPER TOOLS** will link to **Wallets, signing tools, API clients**, etc.

**Comment by cwaring** [comment]
I'm thinking along the lines of option 2 because this combined with effectively removing a level of depth in the sidebar will solve the UX issue for this particular case and leave us with the option to expand into index pages at later date as required 👌

**Comment by johnnymatthews** [comment]
Excellent! Let's go with the second solution then: have the sub-section headers link to whatever is the first page in the sub-menu.

**Comment by cwaring** [comment]
This is mostly fixed after the content re-org, calling it complete for now.
