### ISSUE TITLE
Some fixes for How Filecoin Works document

### ISSUE THREAD

**Issue by DannyS03** [filecoin-project/filecoin-docs#1529]
Sidebar menu disappears when on the [How Filecoin Works](https://docs.filecoin.io/about/basics/how-filecoin-works/) document.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/25497083/210035596-a56a368f-efa1-4171-88d4-dabc88bf5720.png)

</details>

The older document  (https://docs.filecoin.io/about-filecoin/how-filecoin-works/) also doesn't redirect to the newer one.

An opportunity to also check other pages and redirects. Feel free to assign me as there are some general writing style tweaks that can also be made to the page.

**Comment by johnnymatthews** [comment]
Aaaah, I see what happened. Thanks for the flag! Fixing now.
