### ISSUE TITLE
Explain how accounts and assets work in relation to the FVM.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1543]
The `/developers/smart-contracts/concepts/accounts-and-assets/` page needs to explain how accounts and assets work in relation to smart contracts and the FVM. Specifically, how can developers create and manage their accounts programmatically, and also how to properly store and manage assets within actors/smart-contracts.

This issue can be a holding place for content discussion and ideas.

**Comment by johnnymatthews** [comment]
Specifically for `f4` addresses:

- What is an f4 address?
- How are they different from other F addresses?
- What are they for?
- How do I create an F4 address?
	- Curl request to somewhere would be nice.

**Comment by ElPaisano** [comment]
Hey @johnnymatthews i can take this one
