### ISSUE TITLE
Replace Twitter icon from topbar nav with link to Glossary page.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1545]
Playing around with adding a Glossary link to the topbar nav so that readers can get to definitions faster. MIght not be necessary since we've got the tooltip feature now, but still might be useful.

<img width="1552" alt="Screen Shot 2022-12-26 at 8 02 23 PM" src="https://user-images.githubusercontent.com/9611008/209595381-4d5eb45f-79e1-4dfe-8ed3-5bf69eaf1dde.png">

The reason for replacing the Twitter icon is that I don't think it's used particularly often, nor does it add any significant value to the documentation. However, I have no data to back this up. We can probably put a counter on the Twitter icon to track how many clicks it gets a day.

This issue can serve as a discussion page.

**Comment by smagdali** [comment]
I looked in GA - I couldn't see any clicks on the twitter link in December. But I'm not sure this will be a strong enough call-to-action to make people think 'Glossary'. Also definitely the best way to do a glossarise in a website is via a link or a tooltip. Glossaries are a workaround for printed matter where you can't link in context :)

**Comment by johnnymatthews** [comment]
> But I'm not sure this will be a strong enough call-to-action

Yeah, I think you might be right. Having the tooltips _clickable_ might be an option to get folks to the glossary. But saying that, the tooltips act as the glossary themselves.

Either way, it might be an idea to remove the Twitter icon from the topbar nav. It doesn't really add much value to a _docs_ site; I can't imagine devs are gonna start scrolling through a Twitter feed to get API info 😅

**Comment by smagdali** [comment]
agreed.

**Comment by smagdali** [comment]
100% (still)

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/filecoin-docs/pull/2122
