### ISSUE TITLE
Explain what actors and contracts are.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1547]
> Actors are blocks of code that run on the Filecoin virtual machine. Smart contracts are small, self-executing blocks of code that run on Ethereum. Both actors and smart-contracts are used within the FVM.

The [Actors and Contracts](https://docs.filecoin.io/developers/smart-contracts/concepts/actors-and-contracts/) page currently only contains very basic definitions of what the two concepts are. We can flesh-out this page by detailing the build-in actors that exist within the network.

**Comment by ElPaisano** [comment]
Hey @johnnymatthews I can take a look at this one

**Comment by ElPaisano** [comment]
Covered by https://github.com/filecoin-project/filecoin-docs/pull/1693
