### ISSUE TITLE
Use consistent price units for various steps in the process of deal-making through the docs.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#155]
Currently _ask prices_ are in `FIL`, while _deal information_ is displayed in `attoFIL`. Make these units clear on the docs site.

**Comment by johnnymatthews** [comment]
@pooja, is this issue meant to make the price unit consistent across both _ask prices_ and _deal information_ so they both use the same unit (they'd both display `FIL` for example)?

**Comment by pooja** [comment]
I think they should be consistent units and/or labeled with the right units. However, since UX changes are low on the lotus team list, for now, just hoping we can document what's actually going on and improve in lotus UX down the road!

**Comment by johndmulhausen** [comment]
@arajasek To follow up on this to see if it's still an issue on the Lotus side, which has seen considerable UX improvements.
