### ISSUE TITLE
Improve distinctiveness of alert blocks

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/filecoin-docs#1558]
In the new design, the styling of alert blocks is indistinguishable from code blocks. It would be good to bring back the icons or change the coloring/font.

As an example see: https://docs.filecoin.io/get-started/store-and-retrieve/setup/

**Comment by johnnymatthews** [comment]
Here's a screenshot of the link above for reference: 

<img width="843" alt="Screen Shot 2023-01-11 at 3 22 12 PM" src="https://user-images.githubusercontent.com/9611008/211909851-8094da5c-9551-4ec9-b8eb-2b8fca01f4b4.png">

**Comment by smagdali** [comment]
The previous version of filecoin.io had alert boxes with a yellow background that was more distinct from the code blocks, and also worked well in both light and dark modes. 

<img width="735" alt="image" src="https://user-images.githubusercontent.com/942675/213728358-23a3537a-488c-4dfb-aa90-50e3f3cc6333.png">

It would be useful to 'info' and 'warning; options available, possibly with a more intense yellow for a warning, but just bringing back the yellow would be good.

Disclaimer: not a designer.
