### ISSUE TITLE
How to call a built-in actor.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1561]
Let's create a user guide on how to call a built-in actor within a smart-contract. More details for this issue to come shortly.

**Comment by ElPaisano** [comment]
Hey @johnnymatthews I can take a look at this one. Are there useful GH repos, videos, etc., where I can find some existing info to start with?

**Comment by longfeiWan9** [comment]
@ElPaisano currently, the easy way to call exposed methods from built-in actors are using [filecoin.solidity](https://github.com/Zondax/filecoin-solidity).

**Comment by ElPaisano** [comment]
Created https://github.com/filecoin-project/filecoin-docs/pull/1747 for this

**Comment by ElPaisano** [comment]
Closed by https://github.com/filecoin-project/filecoin-docs/pull/1747
