### ISSUE TITLE
Define which files are too small and too large to be stored using Filecoin.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#157]
Make clear recommendations for file storage pathways based on item size:
- If <128B, don't store on Filecoin -- just put into a message on the blockchain
- If > X TBs (not sure what X should be exactly), use offline data transfer

**Comment by jimpick** [comment]
The threshold for offline data transfer is highly situation dependent and not particularly clear. It depends on what they are optimizing for ... cost, timeliness, throughput + details such as how fast they can transfer over their network, what their cost is for network traffic vs. hard disk prices, can they re-uses disks, what media are they using, etc, etc.

**Comment by pooja** [comment]
Agreed, although are there some ways in which to present a clearer heuristic to the user? Maybe it's enough just to say that if you have really large data volumes, you might want to consider offline data transfer.

**Comment by johnnymatthews** [comment]
I'm not sure this is something we need to explicitly tell users. We cover offline storage deals pretty well, and I haven't encountered any users attempting to store < 128B of data into a single deal. @pooja, thoughts? Can we close this one?

**Comment by johndmulhausen** [comment]
Table:
< 128B: Batch
< 100MB: Batch
< 1GB-32GB: Store as-is
< 1TB: Split into 32gb sectors, maintain index of pieces
> 1TB: Offline

**Comment by johndmulhausen** [comment]
127 bytes is minimum, technologically
32GB / 128 * 127 is maximum

**Comment by johndmulhausen** [comment]
Closing in favor of #99 where we're going to talk about the batching process for <128B use case
