### ISSUE TITLE
Import built-in actor docs

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#1573]
@longfeiWan9 has written some very useful reference content on built-in actors. It's currently living in a personal repo: 
https://github.com/longfeiWan9/BuiltIn-Actor-API

As discussed with @longfeiWan9 and @hammertoe, we want to import it to this project docs so developers can find & use it. 
- Add this content to the [Reference > JSON RPC section](https://docs.filecoin.io/developers/reference/json-rpc/introduction/)
- Link to it from [smart contracts > actors and contracts](https://docs.filecoin.io/developers/smart-contracts/concepts/actors-and-contracts/) 

FYI @johnnymatthews

**Comment by johnnymatthews** [comment]
Nice! Outstanding work @longfeiWan9! I can merge this in asap.
