### ISSUE TITLE
Replace screenshots in Smart contract section.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1588]
A recent update to the Filecoin test networks means that Wallaby is no longer the preferred network. This makes a lot of our screenshot invalid. This tasks is to track updating those screenshots.

There are no screenshots within the `/developers/smart-contract` section at the moment, so we'll have to re-create all the screenshots.

**Comment by TMoMoreau** [comment]
To clarify, which specific pages are we looking to add screenshots to?
