### ISSUE TITLE
Update JSON-RPC calls to use mainnet.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1590]
Once Filecoin EVM runtime is launched on Mainnet we'll need to update all the JSON-RPC examples we've got. For example:

https://github.com/filecoin-project/filecoin-docs/blob/main/content/en/developers/reference/json-rpc/eth/index.md#ethaccounts

```shell
curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "method":"eth_accounts",
    "params":[],
    "id":1
}' | jq
```

**Comment by ElPaisano** [comment]
I can take this one @johnnymatthews. I'm guessing that the idea here would be do the work for this, and then wait to merge  into the docs until the Filecoin EVM runtime is launched on Mainnet?

**Comment by ElPaisano** [comment]
Created https://github.com/filecoin-project/filecoin-docs/pull/1751 for this

**Comment by johnnymatthews** [comment]
> And the ask is just to update the --request field to the mainnet address for all the example curls in the reference?

It's a bit more finicky that this. We need to go through the docs and find any instances where we're saying something like _"this will be available on mainnet on XYZ date_".

Then, in the Reference section, all Curl requests need to use `mainnet`. But Curl requests in things like tutorials and guides should likely use Hyperspace (since that's what devs will likely initially be using). However, if the tutorial/guide specifically talks about using mainnet, then we should use a mainnet endpoint in the Curl request.

I'm also using Curl requests as an example here. It could be any kind of request to a node.

**Comment by ElPaisano** [comment]
> > And the ask is just to update the --request field to the mainnet address for all the example curls in the reference?
> 
> It's a bit more finicky that this. We need to go through the docs and find any instances where we're saying something like _"this will be available on mainnet on XYZ date_".
> 
> Then, in the Reference section, all Curl requests need to use `mainnet`. But Curl requests in things like tutorials and guides should likely use Hyperspace (since that's what devs will likely initially be using). However, if the tutorial/guide specifically talks about using mainnet, then we should use a mainnet endpoint in the Curl request.
> 
> I'm also using Curl requests as an example here. It could be any kind of request to a node.

Got it, I'll update https://github.com/filecoin-project/filecoin-docs/pull/1751 accordingly

**Comment by ElPaisano** [comment]
After discussion, the best thing to do it to recreate #1751  but against the feat/docs-information-restructure branch. Closing this. Superseded by https://github.com/filecoin-project/filecoin-docs/pull/1789
