### ISSUE TITLE
Add message receipt work-around for stability.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1595]
From [Filecoin Slack](https://filecoinproject.slack.com/archives/CRK2LKYHW/p1674146561012789):

Are you using hardhat, ethers, or Open Zeppelin to deploy contracts? This EVM toolchain is great for FEVM development, but there's one additional trick that should help you deploy and have successful transactions on hyperspace consistently.

Since receipts in Filecoin are generated in the next tipset, depending on when a transaction is submitted to the mempool, the receipt could come in anywhere between 30-90 seconds. The default transaction receipt timeout for a lot of toolchains is 60000 ms (one minute).

This will work for you roughly half of the time. If you override the defaults when deploying a transaction or waiting for a confirmation, a little bit more patience will consistently return a transaction receipt:

```plaintext
// example of open zeppelin upgradeable proxy
const deployment = await upgrades.deployProxy(contract, preparedArguments, {
    timeout: 180000
});
```

Let's add this snippet/tip into the docs.

**Comment by ElPaisano** [comment]
@johnnymatthews I can take this. However, looking at the current docs, I'm not entirely sure where this should go. Ideas:

- Somewhere on https://docs.filecoin.io/developers/smart-contracts/how-tos/deploy-a-contract/
- A best practices page (I don't think we have one)

Not sure where else. LMK what you think

**Comment by ElPaisano** [comment]
Adding my copy rewrite here until we decide on location. I think this would be good as a note on guides that involve Hardhart, Open Zeppelin, etc.

_Since receipts in Filecoin are generated in the next tipset, depending on when a transaction is submitted to the mempool, the receipt may take between 30 and 90 seconds to return. To consistently return transaction receipts when deploying a transaction or waiting confirmation, change the default transaction receipt timeout (60000 ms or 1 minute for many toolchains). An example using Open Zeppelin is as follows:_

```js
const deployment = await upgrades.deployProxy(contract, preparedArguments, {
    timeout: 180000
});
```

**Comment by johnnymatthews** [comment]
Based on the `feat/docs-information-restructure` branch, this should likely go under `/smart-contracts/developing-contracts/`. I think you're right, a new page called _Best practices_ or something like that should be created.

**Comment by ElPaisano** [comment]
@johnnymatthews  I accidentally pushed https://github.com/filecoin-project/filecoin-docs/commit/9a61103029982bf30243d5234cbaad2130e8c766 onto your https://github.com/filecoin-project/filecoin-docs/tree/feat/docs-information-restructure. This commit is the best practices page with the message receipt work around from https://github.com/filecoin-project/filecoin-docs/issues/1595 as the initial content. Anyways, sorry about that, meant to make a PR against that branch not push a commit. LMK if you want me to revert.
