### ISSUE TITLE
Add `beryx.zondax.ch` as a Hyperspace Block explorer.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1596]
Add `beryx.zondax.ch` as a Hyperspace Block explorer to the following pages:

- https://docs.filecoin.io/developers/infrastructure/block-explorers/
- https://docs.filecoin.io/developers/reference/tools/

**Comment by jennijuju** [comment]
they also support mainnet

**Comment by jennijuju** [comment]
im not sure about the effort evaluation here, i think its more propoer to be `effort/minutes`

**Comment by johnnymatthews** [comment]
Ya we don't have an `effort/minutes` label. There's a reason for that, but I forgot what it is.
