### ISSUE TITLE
Improve the Install section.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#161]
Our metrics have identified this page as most "not helpful" -- lots of opportunities to improve its usefulness, which would be great to work towards in our next milestone.

We might want to include:
- links to upcoming official lotus image on DockerHub: https://hub.docker.com/u/filecoin
- direct install instructions for lotus
- links to lotus + Powergate cloud images (don't act on this one yet, exploring if we can make these more official somehow): https://github.com/protofire/filecoin-cloud-images

**Comment by johnnymatthews** [comment]
Looks like this one got finished a while ago. I can't see a Lotus image on Dockerhub. Gonna close this one.
