### ISSUE TITLE
Outdated steps in the `/developers/smart-contracts/quickstart/`

### ISSUE THREAD

**Issue by TMoMoreau** [filecoin-project/filecoin-docs#1621]
While running through the smart contracts quickstart guide to capture screenshots, I noticed that some of the steps given in the guide are outdated.

One example would be:
[Step 9 under the "Create a wallet" header](https://docs.filecoin.io/developers/smart-contracts/quickstart/#create-a-wallet), MetaMask no longer uses that kind of recovery phrase confirmation, instead, you are prompted to type in the words that are missing from the phrase.

There are a few others as well, and may be more further into the guide.

**Comment by TMoMoreau** [comment]
I can take this on, considering I'm already running through the guide anyway.

**Comment by TMoMoreau** [comment]
I assume this can be handled in the same way as the screenshots issue? As in, make changes to the individual how-to pages so they can be ported to the quickstart.

**Comment by johnnymatthews** [comment]
Ya that's about right.

**Comment by TMoMoreau** [comment]
Just went through the steps again, everything now seems to be accurate and up to date. Closing.
