### ISSUE TITLE
Refine "Linking MetaMask" section

### ISSUE THREAD

**Issue by raulk** [filecoin-project/filecoin-docs#1623]
https://docs.filecoin.io/developers/smart-contracts/how-tos/add-to-metamask/#simple-method

This is a pretty important flow, and the new website directs to it prominently, so we gotta make it easier to follow.

![image](https://user-images.githubusercontent.com/1101242/215087895-560335c1-1c67-4abc-be81-6a4fd6fbfdac.png)

```[tasklist]
### Tasks
- [ ] Add screenshots.
- [ ] Add a video/GIF.
```

**Comment by johnnymatthews** [comment]
See https://github.com/filecoin-project/filecoin-docs/issues/1588. Closing.
