### ISSUE TITLE
Broken link in intro-to-filecoin/crypto-economics

### ISSUE THREAD

**Issue by fridrik01** [filecoin-project/filecoin-docs#1660]
The link in question:

![image](https://user-images.githubusercontent.com/124135/218719633-d71993da-8b37-4a3e-b5e7-ce2b7af9f6cf.png)

Resolves to this:

![image](https://user-images.githubusercontent.com/124135/218719772-778efb23-f8e6-4186-971b-88d79adbb267.png)

It should probably resolve to https://spec.filecoin.io/#section-systems.filecoin_token.minting_model

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/filecoin-docs/pull/1663
