### ISSUE TITLE
Don't display raw URLs.

### ISSUE THREAD

**Issue by raulk** [filecoin-project/filecoin-docs#1674]
Here's one instance:

https://docs.filecoin.io/about/assets/wrapped-filecoin/

<img width="874" alt="image" src="https://user-images.githubusercontent.com/1101242/219864253-0bc1f104-30f6-49c5-8aac-f20b41446c2e.png">

**Comment by johnnymatthews** [comment]
This is often something that can be picked up by a markdown linter. @ElPaisano do you know if Vale has this capability?

**Comment by ElPaisano** [comment]
I went through the docs and updated the raw urls that made sense to update (ignored code samples). PR is https://github.com/filecoin-project/filecoin-docs/pull/1687

**Comment by ElPaisano** [comment]
@johnnymatthews yeah it looks like markdownlint's [rule 34 ](https://github.com/DavidAnson/markdownlint/blob/main/doc/md034.md) can check for bare URLs. We don't currently check it in ipfs-docs, but all you need to do is toggle it to true to enforce https://github.com/ipfs/ipfs-docs/blob/main/.markdownlint.jsonc#L206
