### ISSUE TITLE
Built-in actors

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1698]
Created from https://github.com/filecoin-project/filecoin-docs/issues/1692

Let's create a simple overview page for the built-in actors API. We should explain:

- [ ] What the built-in actors are.
- [ ] How they're different to other Filecoin APIs.
- [ ] The two different API _types*_ available to devs:
    - [ ] Protocol API
    - [ ] Zondax/Filecoin.sol API
- [ ] How developers can access/invoke the built-in actors API.

**Comment by ElPaisano** [comment]
Closed by https://github.com/filecoin-project/filecoin-docs/pull/1760
