### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1699]
Spawned from https://github.com/filecoin-project/filecoin-docs/issues/1692

Let's create a _fairly simple_ store and retrieve tutorial. We don't need to dive too deep into exactly how storing and retrieving works, we just need to show the reader (in this case a dev) how simple it _can_ be to store something on the Filecoin network, and then how they can get that data back.

Since this is gonna be fairly simple, we're likely gonna be using libraries rather than hard coding everything -- which is fine. But at the end of the the tutorial, we should point out that there are _many_ **many** ways to store and retrieve on Filecoin.

**Comment by trruckerfling** [comment]
@ZakAyesh can u pls include:
- https://github.com/filecoin-project/filecoin-docs/issues/1743

**Comment by johnnymatthews** [comment]
After discussion, the ERC-20 Quickstart can serve as the major Quickstart for the docs at this time. https://docs.filecoin.io/smart-contracts/fundamentals/erc-20-quickstart/

Once the Client Contract work has settled, we can create a robust tutorial surrounding that.
