### ISSUE TITLE
What is the FVM

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1700]
Spawned from https://github.com/filecoin-project/filecoin-docs/issues/1692

This page needs to be less than 500 words, but cover the following points:

- [x] What the FVM is.
- [x] Why it is being created.
- [x] What it's being created _now_.
- [x] Why it's useful.
- [x] A handful of use-cases that the FVM unlocks.
    - [x] Link to Use-cases page.

**Comment by trruckerfling** [comment]
sarah doing

**Comment by dawnkelly09** [comment]
Google doc available for feedback: https://docs.google.com/document/d/1RvRkn8QN3sjMDwj3HBM-d5K6Lr5Yv6myEjAckh6Cnws/edit?usp=sharing

**Comment by johnnymatthews** [comment]
Merged! Thanks for that @dawnkelly09!
