### ISSUE TITLE
About FEVM

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1702]
Spawned from https://github.com/filecoin-project/filecoin-docs/issues/1692

- [x] Define with the Filecoin EVM runtime is.
- [x] Explain how the runtime fits into the Filecoin platform.
- [ ] Show example of a Solidity contract being ported to the Filecoin EVM runtime.
- [x] Detail what the Filecoin EVM runtime _can't_ do.

The acronym _FEVM_ means literally nothing to folks outside of the FVM project. So let's stick to using _Filecoin EVM runtime_, that's a bit more self-explanatory.

**Comment by trruckerfling** [comment]
Sarah doing

**Comment by dawnkelly09** [comment]
This is ready for feedback: https://docs.google.com/document/d/1CBuhhbgfWJyX-x1tXd84417WvCwUqo8kRV4Ekhn9TWQ/edit?usp=sharing

**Comment by johnnymatthews** [comment]
Adding a note here for myself: @ElPaisano has done some work that can be added into this page over at https://github.com/filecoin-project/filecoin-docs/pull/1750. 

I'll merge that stuff into this issue manually.

**Comment by trruckerfling** [comment]
reviewed dawn's article and added in #1750, @johnnymatthews if youre good to go pls go ahead
