### ISSUE TITLE
How gas works

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1706]
Spawned from https://github.com/filecoin-project/filecoin-docs/issues/1692

We've already kinda go this issue sorted: https://docs.filecoin.io/developers/smart-contracts/how-tos/calculate-gas/

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/filecoin-docs/pull/1726

**Comment by trruckerfling** [comment]
https://gist.github.com/vyzo/781c081cc9769e2f99a087a5886cfc2b engineering just wrote additional information, opening this to add to it

**Comment by trruckerfling** [comment]
do you wanna take this one johnny? to update your gas article with eng's info?

**Comment by johnnymatthews** [comment]
Yeah I'll add this into the existing page now.

**Comment by johnnymatthews** [comment]
Done! [5ff90fc](https://github.com/filecoin-project/filecoin-docs/pull/1694/commits/5ff90fc5eb9d7bd517bdbce119e831826cefcd40)
