### ISSUE TITLE
MetaMask

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1710]
Spawned from https://github.com/filecoin-project/filecoin-docs/issues/1692

- [x] How to add a Filecoin network to MetaMask
    - [x] Grab content from https://docs.filecoin.io/developers/smart-contracts/how-tos/add-to-metamask/
    - [ ] Include Local testnet steps.
- [ ] How to send FIL from an exchange to a MetaMask wallet.
- [ ] How to send FIL from a MetaMask wallet to different `f...` addresses.

**Comment by hammertoe** [comment]
Assigned: hammertoe

**Comment by johnnymatthews** [comment]
There's a conversation happening here discussing some of these points: https://github.com/orgs/filecoin-project/projects/82/views/13?pane=issue&itemId=20303852

**Comment by johnnymatthews** [comment]
Related issue here: https://github.com/filecoin-project/filecoin-docs/issues/1668
