### ISSUE TITLE
Foundry

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1713]
Spawned from https://github.com/filecoin-project/filecoin-docs/issues/1692

- [x] Explain what Foundry is.
- [x] Re-create the Hardhard tutorial from https://github.com/filecoin-project/filecoin-docs/issues/1712

**Comment by xBalbinus** [comment]
https://github.com/filecoin-project/filecoin-docs/pull/1775

**Comment by johnnymatthews** [comment]
Done!
