### ISSUE TITLE
Solidity libraries

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1714]
Spawned from https://github.com/filecoin-project/filecoin-docs/issues/1692

- [ ] List all the Solidity libraries we have.
- [ ] Either link to, and include a simple quickstart for using each library.

**Comment by longfeiWan9** [comment]
What is the difference with #1715 & #1697 ?

**Comment by johnnymatthews** [comment]
Good call @longfeiWan9. https://github.com/filecoin-project/filecoin-docs/issues/1715 can be integrated into _this_ issue.

https://github.com/filecoin-project/filecoin-docs/issues/1697 is similar to this issue, however that page mainly acts as a pointer to folks diving straight into the Reference section and expecting to see Filecoin.sol information.

**Comment by longfeiWan9** [comment]
Cool. Then I will take this one.

**Comment by longfeiWan9** [comment]
@johnnymatthews This is ready to review.

**Comment by johnnymatthews** [comment]
Merged!
