### ISSUE TITLE
Integrating existing Ethereum libraries and contracts

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1715]
Spawned from https://github.com/filecoin-project/filecoin-docs/issues/1692

- [ ] Explain that external libraries can be simply integrated into Solidity contracts.
- [ ] Use OpenZeplin as an example.
    - [ ] Showcase their ERC-20 contract as an example.
    - [ ] Can grab content from https://docs.filecoin.io/developers/smart-contracts/quickstart/
    - [ ] Link to OpenZeplin docs for more info.

**Comment by ZakAyesh** [comment]
One of the main libraries should definitely be [OpenZeppelin ](https://www.openzeppelin.com/contracts). These are the gold standard for Ethereum libraries. We can explain what OpenZeppelin is, maybe talk about one standard (like their ERC20 contract) and just link out to their docs for the rest.

**Comment by longfeiWan9** [comment]
I will work on this along with #1714. They should be all mentioned in a doc

**Comment by longfeiWan9** [comment]
This is ready to review.

**Comment by johnnymatthews** [comment]
Merged!
