### ISSUE TITLE
Hardhat

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1717]
- [ ] Explain what Hardhat is
- [ ] How to run a test in Hardhat
    - [ ] [Use the FVM Hardhat Kit](https://github.com/filecoin-project/fevm-hardhat-kit)
- [ ] Link to the external Hardhat docs.

**Comment by ZakAyesh** [comment]
This will just explain the basics of what hardhat is (an SDK for automating the deployment, testing and interaction of EVM Smart Contracts). We can then link to the hardhat starter kit as an example, and finally link out to the hardhat docs
