### ISSUE TITLE
Holder for incoming IPC content.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1721]
The Interplanetary consensus (IPC) project is spinning up! Which means we'll soon have IPC docs content in this repo. This issue can act as a placeholder and discussion thread for new content.

**Comment by jsoares** [comment]
from @TippyFlitsUK:
> I just wanted to reach out WRT to the upcoming IPC launch. We will need to feature a new IPC/Spacenet section on the [docs.filecoin.io](http://docs.filecoin.io/) site were originally aiming for the "Developers" section but this is no longer an option. The Spacenet section can happily live in the "Networks" dropdown but the only logical place for the IPC section is a new top menu item which I understand may not be preferable.
Would be very interested in hearing team thoughts and suggestions!! Many thanks all!!

I was happy with the original developers solution we were planning, but I don't see a great alternative to the top bar in the new structure. _Maybe_ a section under the _basics_ tab would work? We'll need to go into some detail, though, so it might become a bit of an outlier.

What would make sense @johnnymatthews ? We need to have the docs up next week in time for the launch, so guidance on how we should go is much appreciated 🙏

**Comment by TippyFlitsUK** [comment]
Added as PR for the new IPC section under Basics here - https://github.com/filecoin-project/filecoin-docs/pull/1916
