### ISSUE TITLE
Broken link: Both Mainnet and Calibration are pages that cannot be found

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/filecoin-docs#1728]
![image](https://user-images.githubusercontent.com/69969590/221767016-fcdeafe7-5e8b-45e3-a738-2dbc16d8f5ea.png)

![image](https://user-images.githubusercontent.com/69969590/221766618-140b911b-7d5b-4de5-830b-04fed49c5c54.png)

**Comment by johnnymatthews** [comment]
Thanks for the flag. Fixed in https://github.com/filecoin-project/filecoin-docs/commit/d4e139baa691844b4a7ef9ab03d01649d578bb12
