### ISSUE TITLE
Fix the meta description

### ISSUE THREAD

**Issue by raulk** [filecoin-project/filecoin-docs#1738]
<img width="240" alt="image" src="https://user-images.githubusercontent.com/1101242/222709659-451ea55f-0329-4e95-a05e-5be10b930ed0.png">

Suggestion, use the same as filecoin.io, but add something about smart contracts: "Filecoin is making the web more secure and efficient with a decentralized data storage marketplace, protocol, and cryptocurrency. Now with smart contracts."

**Comment by johnnymatthews** [comment]
Hmm, strange. The description _is_ set in `params.toml`, but it's being picked up from `/content/en/_index.md` instead...
