### ISSUE TITLE
Which drives should an SP use for different situations?

### ISSUE THREAD

**Issue by gaowayne** [filecoin-project/filecoin-docs#1740]
Hello, is there any insight storage workload analysis for filecoin, 
how to choose different media for different filecoin internal scenarios?
if all flash high density drives help on filecoin?

**Comment by johnnymatthews** [comment]
Thanks for the issue! I've edited the title to better fit your request. I'm not 100% sure on the answer, so I'll pull in an SP advisor to help out here.

**Comment by smagdali** [comment]
@bobdubois relevant content request here.

**Comment by gaowayne** [comment]
> Thanks for the issue! I've edited the title to better fit your request. I'm not 100% sure on the answer, so I'll pull in an SP advisor to help out here.

thank you so much. I already joined slack, we can chat more there too. :)

**Comment by bobdubois** [comment]
Hi @gaowayne , please see the following content:
- https://docs.filecoin.io/storage-provider/infrastructure/storage/
- https://docs.filecoin.io/storage-provider/infrastructure/reference-architectures/

You will see that SATA is the storage medium for long-term storage. NVMe is used as a scratch space during the sealing.
A full flash setup is overkill and especially economically not feasible.
