### ISSUE TITLE
Add last updated or last reviewed date to docs content

### ISSUE THREAD

**Issue by ivanka** [filecoin-project/filecoin-docs#1741]
We have been doing user research on docs content with aspiring storage providers and one of the findings is that people struggle to identify the most up-to-date information on a given topic. 

Adding a date to docs isn't the whole solution to the challenge of keeping people informed and helping them avoid incorrect information, but it is a useful data point (for us and for users). 

I propose that we include the date on the right hand menu above the "on this page" section, particularly as it resolves well on mobile. Of course there might be better solutions given the practicalities of implementation which I don't know about. 

Once we have an implementation we can follow up with further user research and identify further improvements.

Here is a quote from one of the participants in the last round of research: 

> "...my first feedback to you on that...Because I've had, I've had loads of problems with it...Is to date stuff.. it's because things change. They change so often. So a last updated date or created date, and a last updated date would really help because I've gone everywhere...there's Chinese duplication of this document. I've had to go into Slack, on Slack people will, they'll make references to content that's no longer there. "

**Comment by johnnymatthews** [comment]
This feature is pretty trivial to implement, [we'd just need to set `lastMod` to `true`](https://github.com/filecoin-project/filecoin-docs/blob/83f22c52bdc904cff0313f82600a2f77aa7ffdcb/config/_default/params.toml#L87).
