### ISSUE TITLE
UX improvements for Filecoin Docs

### ISSUE THREAD

**Issue by cwaring** [filecoin-project/filecoin-docs#1742]
Tracking issue for visual updates to docs.filecoin.io

```[tasklist]
### Typography
- [x] Improve base typography and font selection to enhance readability
- [x] Review and improve global font scale
- [x] Improve embedded page TOC
- [x] Improve spacing on embedded lists
- [ ] Improve table typography scale
- [ ] Improve top level navigation
```
```[tasklist]
### Layout
- [x] Redesign the homepage for better content discoverability
- [ ] Expand the max-width to make better use of screen real estate
```
```[tasklist]
### Navigation
- [x] Make  table of contents on the right hand side more compact; review vertical spacing
```

**Comment by johnnymatthews** [comment]
> Expand the max-width to make better use of screen real estate

We can do this _right_ now by [setting `fullWidth` to `true`.](https://github.com/filecoin-project/filecoin-docs/blob/83f22c52bdc904cff0313f82600a2f77aa7ffdcb/config/_default/params.toml#L106)

> Make table of contents on the right hand side more compact; review vertical spacing

Just want some clarification here. We can make the right-hand menu (known at the ToC) more compact by only showing `<h2` headers. For example:

<img width="619" alt="Screen Shot 2023-03-06 at 4 26 42 PM" src="https://user-images.githubusercontent.com/9611008/223234612-2fbff95e-5273-4b81-89d7-6c05385f6450.png">

Would become: 

<img width="600" alt="Screen Shot 2023-03-06 at 4 27 31 PM" src="https://user-images.githubusercontent.com/9611008/223234739-6ac35e4a-26e5-4f5f-82ab-7e9887335f82.png">

Is that compact enough, or would you like to see the margins and padding changed?

**Comment by ivanka** [comment]
To add to the discussion here, in the recent usability sessions it is the fact that the left - main - menu doesn't collapse that has elicited comments.

In the case of the content I am testing right now - for the new Storage Provider section -  it's almost certainly down to the number of items in each section that makes it feel overwhelming but regardless, collapsing navigation on the right would mean that users can process an overview of the main sections before diving in the the detail. One participant highlighted the example of the lotus docs site and the collapsable menus there and it would make sense to keep a consistency in behaviour between the two sites I think.

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/filecoin-docs/pull/1801

**Comment by johnnymatthews** [comment]
Closing due to switch to GitBook.
