### ISSUE TITLE
Deal making tutorial - deal bounty

### ISSUE THREAD

**Issue by trruckerfling** [filecoin-project/filecoin-docs#1762]
- [ ] explain deal bounty contract + tutorial
- [ ] add how to make deal look more attractive https://www.notion.so/pl-strflt/fevm-launch-dev-notice-on-SP-parameters-8fab510f84ce48f09047d96257649419?pvs=4 although do consider that in this method, there is a bounty hunter incentivized to make your deal happen but can't hurt to make your deal attractive in the first place

**Comment by trruckerfling** [comment]
context/existing info @dawnkelly09 
- https://www.youtube.com/watch?v=KTVHhx1bKiE&list=PL_0VrY55uV18owIh7aQite_hxsS4YGHkX&index=2
- https://www.youtube.com/watch?v=2Cpahhb0IW0&list=PLhmonklIHGmXu_uJ9JBvB6bA7hGb7tsXT&index=1
- https://github.com/filecoin-project/community/discussions/601 (refer to Current method to store data with FEVM: Incentivising Storage Using Bounties)

**Comment by johnnymatthews** [comment]
Closing in favour of #1761
