### ISSUE TITLE
Actor Types: Accounts, Placeholders, Smart Contracts

### ISSUE THREAD

**Issue by trruckerfling** [filecoin-project/filecoin-docs#1769]
https://gist.github.com/Stebalien/d79b564d9a89ce2e31d2d25824b37911

**Comment by johnnymatthews** [comment]
Closed in [2580ed0](https://github.com/filecoin-project/filecoin-docs/pull/1694/commits/2580ed0061a04761ac105bc0e07c6271d35f5885)
