### ISSUE TITLE
Reorganize wallets + add MetaMask

### ISSUE THREAD

**Issue by raulk** [filecoin-project/filecoin-docs#1777]
- Move Glif and Ledger to the top. These are by far the most popular ones!
- Add MetaMask, with a link to the appropriate MetaMask section under Smart Contracts.
- Add a column "Smart Contracts" (indicating if the wallet supports smart contracts), with only MetaMask saying yes.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/1101242/224572931-0071380d-8fa0-4ee3-b8b9-555dd0c326c2.png">

**Comment by jennijuju** [comment]
Add Okex wallet, which supports FIL, and adding f410/0x later this week (so ✅ for eth accounts/evm actors)

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/filecoin-docs/pull/1788
