### ISSUE TITLE
we can't execute this request"

### ISSUE THREAD

**Issue by dawnvi** [filecoin-project/filecoin-docs#1809]
`[{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x16DF3E4", true],"id":1}]`

`{
"jsonrpc": "2.0",
-"error": {
"code": 0,
"message": "we can't execute this request"
},
"id": null
}`

**Comment by johnnymatthews** [comment]
I'm not sure that your request is formatted correctly. Try:

```
curl --location --request POST 'https://api.node.glif.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "method":"eth_getBlockByNumber",
    "params":["0x16DF3E4", true],
    "id":1
}' | jq
```

Also, `0x16DF3E4` hasn't yet happened on mainnet. Are you trying to run this on Hyperspace?
