### ISSUE TITLE
List frequently asked questions.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#181]
We have a draft PR up for review that includes a v1 FAQ section. In the spirit of shipping quickly, we will get that PR out asap, but need to capture some latent todos not addressed in the PR:
- Reorder the questions in the PR in a more logical order
- Add more FAQs that are less about specific edge cases and more "frequently asked"

**Comment by johnnymatthews** [comment]
This page now exists in [/about-filecoin/faq](https://docs.filecoin.io/about-filecoin/faq/)
