### ISSUE TITLE
Remove Fuhon from list of nodes in /reference/json-rpc/introduction/

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1819]
Right at the bottom of /reference/json-rpc/introduction/ is a list of implementations developers can use to get authentication stuff for JSON-RPC stuff.

![image](https://user-images.githubusercontent.com/9611008/225388995-2eb2bced-28f8-4013-ad4c-f32d0affdcd8.png)

## Tasks

- [x] Remove Fuhon from this list.

**Comment by ElPaisano** [comment]
I can take this @johnnymatthews
