### ISSUE TITLE
Storage Provider section calls-to-action footer block

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/filecoin-docs#1834]
We would like to add a small block with various options for aspirant storage providers to be able to access the various forms of support. @ivanka mocked up something in figma:

https://www.figma.com/file/jwWJr0RxEJXlRfL2QCrFAL/Becoming-a-storage-provider%3A-wireframes?node-id=204-2&t=aOvk51qPmJwRlOBg-0

<img width="692" alt="image" src="https://user-images.githubusercontent.com/942675/226001207-6a54fc85-3dfb-4493-8e03-7fc8d682a76e.png">

@johnnymatthews - if you can help us build the block and the shortcode, I can tweak it with the right links and words, and dropping it into the right pages.

**Comment by johnnymatthews** [comment]
> for aspirant storage providers

Oooph, _aspirant_ is a fun word!

> @johnnymatthews - if you can help us build the block and the shortcode, I can tweak it with the right links and words, and dropping it into the right pages.

Yeah no problem. I'll put something together but leave the content blank.

**Comment by smagdali** [comment]
the content is live on one page: https://docs.filecoin.io/storage-provider/architecture/lotus-components/
