### ISSUE TITLE
[Request]: Review / Update the lifecycle of a drand beacon in Filecoin 

### ISSUE THREAD

**Issue by AnomalRoil** [filecoin-project/filecoin-docs#1853]
### Request type

Changes to existing content

### Describe the issue.

Currently there is a doc entry about drand: https://spec.filecoin.io/#section-libraries.drand
However it says currently:
"DRand (Distributed Randomness) is a publicly verifiable random beacon protocol Filecoin relies on as a source of unbiasable entropy for leader election (see [Secret Leader Election](https://spec.filecoin.io/#section-algorithms.expected_consensus.secret-leader-election))."

But the section about leader election doesn't detail properly how the drand beacons are used in there.
It notably says:
> Get randomness for the current epoch using GetRandomness.
> Generate a VRF and compute its hash
> The storage miner’s workerKey is given as input in the VRF process

But it is not clear what VRF is being used, if we are calling the drand derivation a VRF or if it's something else.
Currently is also says:
> BLS signature can be used as the basis to construct a VRF. Filecoin transforms the BLS signature scheme it uses (see [Signatures](https://spec.filecoin.io/#section-algorithms.crypto.signatures) into a VRF, Filecoin uses the random oracle model and deterministically hashes the signature (using blake2b to produce a 256 bit output) to produce the final digest.

But then the verify function example is wrong and reads as follows for the verify function:
```
func (self *VRFResult_I) Verify(input util.Bytes, pk VRFPublicKey) bool {
	// return new(BLS).Verify(self.Proof, pk.(*BLSPublicKey), input)
	return false
}
```
instead of returning always false, it should: verify the BLS signature, and then proceed with derivation again from that signature and compare it against the input.

Furthermore it is stated also that "In Filecoin, we hash it using blake2b in order to obtain a 256 bit output" and yet the drand doc entry proceeds to explain that drand beacons uses Sha256 for deriving randomness from the  beacons signature.
However if you're using a custom derivation with blake2b then the sha256 done by drand is not useful.

I would recommend to:
- Review the current docs for invalid links (quite a few links in the drand-related docs where linking to github files that didn't exist anymore there because on master and not on a given commit with a permalink)
- Review the current docs to avoid putting information that's not relevant for Filecoin: if we use Blake2b for derivation, it makes sense to link to that section about it from the drand section and say it's using the signature for derivation as recommended by the drand team, but then there's no need to include details about how randomness is derived from drand with Sha256 since that's not how Filecoin does it.
- Make sure the "lifecycle" of a drand beacon can be understood properly from the docs: when is it needed, what do we use it for, do we re-use it, where do we store it in the headers, with what metadata, etc. Currently it's almost impossible to gather from the docs by following the links what's going on really with the drand beacons.
- Update the part about the VRF to make it clear what's actually being used and how to verify it.

### Is there any other information we need to know?

@Kubuxu is a good source on the topic.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElPaisano** [comment]
Hi @AnomalRoil thank you for taking the time to create this issue. If I'm understanding you correctly, the issues you are describing are with https://spec.filecoin.io/#section-libraries.drand, correct? If that is the case, this is the incorrect repository to open an issue in - apologies for the confusion. The `filecoin-docs` repository holds documentation for https://docs.filecoin.io/, whereas https://github.com/filecoin-project/specs/blob/master/content/libraries/drand/_index.md is where the markdown used to generate https://spec.filecoin.io/#section-libraries.drand is stored. 

Please let me know if I am misunderstanding your issue description here. I'm cc'ing my colleague @johnnymatthews to review this as well. Thank you.

**Comment by johnnymatthews** [comment]
I was under the immediate impression that @AnomalRoil was referring to [/basics/the-blockchain/drand](https://docs.filecoin.io/basics/the-blockchain/drand/), but re-reading the initial issue, I think you're right @ElPaisano.

Unfortunately I can't transfer this issue to that repo. @AnomalRoil would you mind recreating your issue over in https://github.com/filecoin-project/specs/issues.

Closing.
