### ISSUE TITLE
[Request]: Clean up wallet & Metamask wallet mentions

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#1874]
### Request type

Changes to existing content

### Describe the issue.

There are currently 5 separate places where wallets or Metamask wallets are documented. 

1. Basics > Assets > Wallets
2. Smart contracts > Wallets > Metamask (Hyperspace instructions only)
3. Smart contracts > Wallets > FilForwarder (explains f4 > f0 address confusion)
4. Networks > Mainnet > Add to Metamask
5. Networks > Hyperspace > Add to Metamask
6. Reference > Wallets > Wallets (audited + other)

This means every list is out of date, and users have a hard time navigating.

Proposal to clean up:
- [x] Delete 6, since 1 + 6 overlap
- [x] Delete 2, since it's a duplicate of 5 and outdated since it only has instructions to Hyperspace (confirm contents are identical first)
- [x] Rename 3 to a title that describes the user's problem instead of the solution they don't know they need yet. Maybe "ETH address compatibility" or "FIL <> ETH addresses" or perhaps @hammertoe @trruckerfling @ZakAyesh @longfeiWan9 have a better idea.
- [x] Move 4 & 5 into the Basics > Assets > Wallets section. It's not specific to smart contracts, and Metamask is probably the most widely used of all the wallets that support Filecoin. I'm not sure the current site hierarchy supports a page underneath Wallets; if not, it could be "Metamask setup" and listed in the "Assets" section between "Wallets and "Get FIL"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BigLep** [comment]
Maybe related, but let me know if you want to move this to its own issue..

Some SEO observations

## Duckduckgo (what I have in Brave - can't remember if that is default)
https://duckduckgo.com/?q=fvm+metamask&t=brave&ia=web
<img width="840" alt="image" src="https://user-images.githubusercontent.com/85411/230262958-e5ae5dcb-499f-45d0-a53c-27892f3f8f50.png">

Result #1: not filecoin official docs
Result #2: legacy-docs.filecoin.io

## Google
https://www.google.com/search?q=fvm+metamask
<img width="893" alt="image" src="https://user-images.githubusercontent.com/85411/230263092-2dc13aac-3cc7-4d78-86ca-06efc0fcf6ef.png">

Google is better here but getting a bit snagged by the multiple FVM documentation points
