### ISSUE TITLE
Add a tooltip entry to `SP`. 

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1878]
_Storage provider_ often gets shortened to _SP_. Let's add a tooltip entry for SP, explaining that it's an acronym for _storage provider_.

**Comment by smagdali** [comment]
@SgtCoin one for you?

**Comment by SgtCoin** [comment]
Yep, Ill take a look.

**Comment by SgtCoin** [comment]
I think we want to change everything to "storage provider" lowercase from SP, so no tool tip would be needed.

**Comment by johnnymatthews** [comment]
Closing due to switch to GitBook.
