### ISSUE TITLE
Add UPnP section under Port Forwarding on the Connectivity page.

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/filecoin-docs#188]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/mine/connectivity/#setting-a-public-ip-address

**What would you like to have changed/amended/fixed in order to make things right?**
Add a subsection to `Port Forwarding` suggesting the use of UPnP, if the user's router supports it. For UPnP to work, it requires that the daemon be configured to use the address `0.0.0.0`. If UPnP is supported, the user does **not** need to also configure port forwarding and if both are done may cause neither to work.

**Comment by har00ga** [comment]
Thanks for noting this :) Will get a fix together tomorrow.
