### ISSUE TITLE
Find instances of `%23` and replace with `#`.

### ISSUE THREAD

**Issue by DeveloperAlly** [filecoin-project/filecoin-docs#1882]
### Request type

Changes to existing content

### Describe the issue.

Link broken on Crypto-economics page
https://docs.filecoin.io/basics/what-is-filecoin/crypto-economics/

[dual minting model](https://spec.filecoin.io/%23section-systems.filecoin_token.minting_model)

### Is there any other information we need to know?

<img width="765" alt="image" src="https://user-images.githubusercontent.com/12529822/229325986-8e2a1caa-e8b2-4573-b54d-abb63618ecd5.png">

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/12529822/229325991-31d43dfc-8ad0-4731-8bac-838b4ebf3fa5.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
It's because the link uses `%23` instead of `#`. This can be fixed with a simple find-and-replace.
