### ISSUE TITLE
[DataDAO Starter Kit]: Document Data DAO concepts

### ISSUE THREAD

**Issue by ElPaisano** [filecoin-project/filecoin-docs#1913]
### Request type

New content

### Describe the issue.

The Fil devrel folks are working on a number of tutorials, sample contracts and that sort of thing around Data DAOs with FVM.

For the initial docs, we need to document the concepts behind a DataDAO and how Data DAOs work on FVM. This can probably live on a single page

- [ ] Determine where in the docs this content should live
- [ ] Document the concepts behind a DataDAO and how Data DAOs work on FVM.

### Is there any other information we need to know?

This should be documented by the hackathon next Tuesday

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
Let's figure out where this should live.

**Comment by ElPaisano** [comment]
**Relevant slack thread** https://filecoinproject.slack.com/archives/C0370V3JTPB/p1681237796031839

**GPT-generated summary of thread:**

Summary:

Raul highlights the vast potential of Data DAOs, emphasizing the need for a shared mental framework and common language. He envisions Data DAOs as composable building blocks, with components such as governance mechanics, funding, and storage longevity. He believes creating a reference framework and executing towards it is the way forward, requiring FRC standards and other developments.

Mosh mentions the need for reusable base contracts discussed in a recent Filecoin Stack Leads weekly meeting. Outercore has pilot partners interested in a reliable, configurable base contract for perpetual storage and possible Data DAOs. They shared a draft of contract requirements: https://docs.google.com/document/d/1bUODuT7vOwL95GClouJYdTZJmtIaHxTa0muieSqQU_s/edit#heading=h.77oj2xe2kfm8

Anshuman shares a diagram based on notes from their discussion with Mosh. They suggest focusing on templates for an endowment pool and deal monitoring contract in the short term.

Raul appreciates the document and flowchart shared by Anshuman and Mosh. He suggests differentiating building blocks and reference solutions, with building blocks being composable modules and reference solutions being concrete, opinionated applications that use these modules. Starter kits for reference solutions can be provided for developers to adapt as needed.

**Comment by ElPaisano** [comment]
Based on the request for input from the team and the (lack of) reaction, seems like we should repriortize this, as it seems the larger team still needs to figure out vision, direction, etc.. Deprioritizing for now

**Comment by johnnymatthews** [comment]
We're still trying to figure out how this kinda thing should work, so I'm gonna close this for now.
