### ISSUE TITLE
Add padding to bottom of YouTube/media.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1921]
### Request type

Something else

### Describe the issue.

YouTube elements, and likely other media elements, aren't applying any padding or magins below their content. This causes things to bunch up a bit. See screenshot:

<img width="1552" alt="Screenshot 2023-04-12 at 13 00 19" src="https://user-images.githubusercontent.com/9611008/231515497-61099ec4-3349-4550-9db1-d2424af1007a.png">

We just need to add a margin to the bottom of the YouTube shortcode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
@Soham-glitch yeahp! It's not a priority for the core team right now. If you've got some time though, PRs are welcome.

**Comment by Soham-glitch** [comment]
assign me this issue I'd like to work on this.

**Comment by johnnymatthews** [comment]
Done! [Check the readme](https://github.com/filecoin-project/filecoin-docs#installation) if you need pointers on how to spin up the site locally.

**Comment by johnnymatthews** [comment]
Closing due to switch to GitBook.
