### ISSUE TITLE
Implement new documentation structure.

### ISSUE THREAD

**Issue by cwaring** [filecoin-project/filecoin-docs#193]
Once an agreed documentation structure has been finalised we will need to schedule a temporary code-freeze for contributions in order to implement the new structure. For this to be possible all existing PRs must be finalised and merged/closed to minimise the risk of conflicts.

Related to #159

**Comment by pooja** [comment]
I believe this issue is now closed, since we have implemented the new documentation structure at a high-level. Please reopen if you believe there is more left in this issue.
