### ISSUE TITLE
Review and fix grammar & formatting in `/smart-contracts/developing-contracts/ethereum-libraries`

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1932]
### Request type

Changes to existing content

### Describe the issue.

I was running through the ERC-20 tutorial on this page and noticed a few grammatical and formatting errors, enough that we should take care of this from it's own branch -- not a HOTFIX into `main`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElPaisano** [comment]
I can take this one @johnnymatthews
