### ISSUE TITLE
[Request]: Document Trust Wallet

### ISSUE THREAD

**Issue by ElPaisano** [filecoin-project/filecoin-docs#1937]
### Request type

New content

### Describe the issue.

Determine if we should document support for Trust Wallet and then do it if we need to.

Context: User in #fil-builders [Slack](https://filecoinproject.slack.com/archives/CRK2LKYHW/p1681471587745369) raised issue that Trust Wallet support, integration process, wallet set up was not clear.

Suggestion:
- [ ] Determine if we should document Trust Wallet (In the thread linked above, another user claimed that Trust Wallet is one of the wallets most used for holding)
- If so, 
  - [ ] Where in the docs?
  - [ ] What kind of content (integration guide, blurb that points the user to official docs, etc.)

### Is there any other information we need to know?

The slack thread (should be public) gives context https://filecoinproject.slack.com/archives/CRK2LKYHW/p1681471587745369. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
External wallet providers should provide their own documentation. Filecoin Docs focuses on MetaMask only, as the usable option for FVM.
