### ISSUE TITLE
[Request]:  Add deal bounty contract tutorial

### ISSUE THREAD

**Issue by ElPaisano** [filecoin-project/filecoin-docs#1942]
### Request type

New content

### Describe the issue.

The filecoin docs will need a tutorial on how to use a "deal bounty" contract based on this [page](https://github.com/filecoin-project/filecoin-docs/blob/82d707a1306f99f5e8e196130e77242189309c8b/content/en/smart-contracts/fundamentals/fvm-storage-deals/index.md?plain=1#L35) being published in https://github.com/filecoin-project/filecoin-docs/pull/1938 (WIP)

Triage todos:
- [ ] Sync with devrel around any content they may have already written, any other resource material (videos, repos, etc.)
- [ ] Based on this, figure out if we just need to prune / edit something, or create a guide
- [ ] Figure out where the content should go

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
I'm marking this as a `p2` since I'm pretty sure this whole process is currently up in the air. We need someone from the FVM DX team to weigh in here.

**Comment by trruckerfling** [comment]
I think we can close this. The focus is on deal client now and that tutorial has been completed. deal bounty is not recommended workflow for devs due to it not being fully programmatic e.g. FVM is not making the deal for you, someone else is
