### ISSUE TITLE
[Request]: Review docs on sending FIL from one address type to another

### ISSUE THREAD

**Issue by ElPaisano** [filecoin-project/filecoin-docs#1944]
### Request type

Something else

### Describe the issue.

Raised by (this is private channel, triage TODO is summarizing relevant parts of Slack thread in this issue thread to help scope)

Ask:

I know we recently had a "so you want to send FIL from one address to a different type" documentation.
However, its clear that anything related to larger workflows (I want to use FIL on my ledger to interact with a smart contract) will need to be added. These are tricky, because there are multiple set ups (things like installing metamask, adding the filecoin Network to its configuration, sending FIL from an F1 to an Ox address, then using the ethereum app on the Ledger to sign the transaction after setting it up through metamask). All of that is painful, and having the Ledger be used through metamask is also rather cumbersome.

- [ ] Discuss in weekly triage
- [ ] Summarize ask
- [ ] ID what parts of existing docs need to be updated
- [ ] ID missing info that needs to be added 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
Done: https://docs.filecoin.io/basics/assets/transfer-fil
