### ISSUE TITLE
Rome Blockchain Labs

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#1948]

**Comment by ElPaisano** [comment]
Hello @mishmosh. The issue doesn't appear to have a description, so reaching out for clarification.

**Comment by mishmosh** [comment]
Apologies! This somehow got created in the wrong repo.

**Comment by anshu93** [comment]
@anshu93 to follow up with JD

**Comment by anshu93** [comment]
Decided to move forward with them. Contracting still outstanding.
