### ISSUE TITLE
[Fixes]: Some Filecoin Link Rot

### ISSUE THREAD

**Issue by kt-wawro** [filecoin-project/filecoin-docs#1950]
### Request type

Changes to existing content

### Describe the issue.

On the filecoin docs on the [storage miner](https://spec.filecoin.io/systems/filecoin_mining/storage_mining/) sub-pages and [blockchain](https://spec.filecoin.io/systems/filecoin_blockchain/) subpages none of the links take you anywhere.

Sealing a sector does not link anywhere but the URL changes to (https://spec.filecoin.io/systems/filecoin_mining/storage_mining/#section-_index.Sealing-a-Sector)

[Sector Storage and Window PoSt scheduler](https://spec.filecoin.io/#section-systems.filecoin_mining) have broken links

[Sector Sealing](https://spec.filecoin.io/#section-systems.filecoin_mining.sector.sealing) has a [broken link](https://github.com/filecoin-project/lotus/blob/master/storage/sealing.go) to the Lotus-specific function at the end of the sector sealing section in sector quality. 

I spot-checked links on the following pages and they all seem to be working:
- Architecture Diagrams page 
- files and data subpages
- Market's subpages
- Appendix subpages
- Glossary
- Libraries
- Algorithms

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElPaisano** [comment]
@kt-wawro thanks for filing, working on a fix now

**Comment by ElPaisano** [comment]
@kt-wawro issue created in spec repo, tagged you https://github.com/filecoin-project/specs/issues/1320

I'm closing this issue now since this is a specs thing
