### ISSUE TITLE
[Request]: Add new RPC Provider

### ISSUE THREAD

**Issue by J1a-wei** [filecoin-project/filecoin-docs#1953]
### Request type

New content

### Describe the issue.

As an RPC Provider(ChainUpCloud), we are willing to make our filecoin RPC available for community use. Prior to this, we have added our endpoints to the [chainlist](https://chainlist.org/?search=filecoin).

### Is there any other information we need to know?

https://docs.chainupcloud.com/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xRook1e** [comment]
[PR](https://github.com/filecoin-project/filecoin-docs/pull/1915)

**Comment by johnnymatthews** [comment]
Hi @0xRook1e, thanks for raising this issue and creating a PR! The docs team are checking in with the Filecoin product team to make sure your request is legitimate. We'll be back here shortly.

**Comment by johnnymatthews** [comment]
Hey @0xRook1e. can you please join [Filecoin Slack](https://filecoin.io/slack/) and DM `@eshon`. Thanks!

**Comment by 0xRook1e** [comment]
@johnnymatthews Thanks， I am trying to DM @eshon
