### ISSUE TITLE
BUG: Chain snapshots links on /Networks/mainnet page are giving ACCESS DENIED

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/filecoin-docs#1987]
### Request type

Changes to existing content

### Describe the issue.

Go to:
https://docs.filecoin.io/networks/mainnet/details/

These two links are currently returning "Access Denied" 

[Latest chain snapshot (pruned)](https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car)
[Latest chain snapshot (full)](https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car)

Should these have been updated to the new snapshot links? 

(also the status link below should go to http://status.filecoin.io not https://filecoin.statuspage.io

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
These large scale snapshots are no longer created. A PR was created to remove them from [Lotus Docs](https://github.com/filecoin-project/lotus-docs/pull/397/files) but it seems that PR was not replicated over here. I'll sort things out.

**Comment by johnnymatthews** [comment]
Fixed in https://github.com/filecoin-project/filecoin-docs/commit/63b77064802dc8c47cc16038c79e2bf7854d1ed7
