### ISSUE TITLE
Replace docs content 

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/filecoin-docs#2]
- [ ] Update content based on the work of the Filecoin Storage & DevTools team, using content placeholders (rocketship screen) as needed
- [x] Confirm links to edit content in GitHub direct to this repo and not the IPFS one

**Comment by mishmosh** [comment]
Can we close this?

**Comment by terichadbourne** [comment]
@mishmosh My intention was to leave open until we've removed all the old IFPS content. These are the pages I see  that are still IPFS content and need replacement: 

Still IPFS content: 
- [ ] Landing page https://filecoin-docs.netlify.app/
- [ ] Introduction section landing page https://filecoin-docs.netlify.app/introduction/
- [ ] 

Filecoin sections with no actual content yet: 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by mishmosh** [comment]
Thanks for breaking this out.

**Comment by mishmosh** [comment]
Getting there! Just the Introduction section left.

**Comment by terichadbourne** [comment]
Searching for todos and we still have this on the [large files](https://filecoin-docs.netlify.app/how-to/store-large-files/) page, @mishmosh. Are you planning to take care of that one before launch? 

![image](https://user-images.githubusercontent.com/19171465/80833989-cba6af80-8bbd-11ea-8fa4-24eefab821c6.png)

**Comment by terichadbourne** [comment]
Closing this out and have opened issue #64 for our remaining TODO.
