### ISSUE TITLE
Add chainlist.org info to RPC pages

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2020]
Please add links to https://chainlist.org/?testnets=true&search=filecoin on the nice new RPC pages, but where the Mainnet RPC page links to https://chainlist.org/chain/314, etc.

**Comment by johnnymatthews** [comment]
Does Chainlist have RPC nodes that builders can connect to? Or are you suggesting that we tell readers that Chainlist contains a list of available RPC nodes and their current status?

**Comment by eshon** [comment]
The latter - that Chainlist contains a list of available RPC nodes and current status.

**Comment by johnnymatthews** [comment]
Gotcha.

## Tasks

- [ ] In each of the RPC pages, mention that Chainlist.org maintains lists of available RPC nodes and their status.

**Comment by Natchaphonwongplianphan** [comment]
My memory space is starting to fill up so I have to switch to another phone
but you have to understand that my email address is 2. I never use a
computer but use a computer software system.  2 simple android phone mobile
devices in development and in various communications now memory is getting
full so it is necessary to switch between devices including email or
address to avoid detection or  Intervention from hackers, you must
understand that I, we fight alone, you guys abandoned me, was shut down by
government agencies, data fraud  occupy unlawful copyright infringement of
copyrighted software, despite me

ในวันที่ อ. 13 มิ.ย. 2023 22:44 น. Johnny ***@***.***>
เขียนว่า:
