### ISSUE TITLE
[Request]: Add Ankr and Chainstack to Calibration testnet RPC providers

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2026]
### Request type

Changes to existing content

### Describe the issue.

Update https://docs.filecoin.io/networks/calibration/rpcs/ with:

- https://rpc.ankr.com/filecoin_testnet now points to Calibration
- https://chainstack.com/labs/#filecoin => Calibration also points to Calibration

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
Closing as done. 

![image](https://github.com/filecoin-project/filecoin-docs/assets/9611008/d238ba85-013b-417b-888b-c4e661df08e6)
