### ISSUE TITLE
Create screenshots for "Verify a contact" page.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#2042]
We have a guide that shows users [how to verify a contract](https://docs.filecoin.io/smart-contracts/developing-contracts/verify-contracts/). The guide was originally [created at this Gist](https://gist.github.com/trruckerfling/54918b8331f6fa10ae27cedd6afd9680). The original guide included screenshots that were not migrated into this repo. 

Some of the screenshots in the original guide are useful, but aren't of the specific quality we need in this repo. This issue tracks creating quality screenshots and adding them into `/content/en/smart-contracts/developing-contracts/verify-contracts/`.

**Comment by ATREAY** [comment]
Hey @johnnymatthews, if this issue is still open, can I work on it? 
And if so, I've got a quick question: could you just let me know where you want those screenshots to go?

**Comment by johnnymatthews** [comment]
Hey @ATREAY.  Yeah, PRs are always welcome! You can store [images in `/.gitbook/assets`](https://github.com/filecoin-project/filecoin-docs/tree/main/.gitbook/assets). I'll assign this issue to you. Let me know if you have any more questions.

**Comment by ATREAY** [comment]
Hey @johnnymatthews, appreciate you for assigning me this issue. My bad for not wording my previous question right.
What I meant to ask is, for the info on where to put those images in the current guide, can I just place them beneath the relevant point or is there a different approach you'd prefer?

**Comment by johnnymatthews** [comment]
Oh sorry, I misunderstood.

> can I just place them beneath the relevant point

Yeah this works fine. Take a look at the [Get test tokens](https://docs.filecoin.io/smart-contracts/developing-contracts/get-test-tokens) tutorial as an example.

**Comment by ATREAY** [comment]
Thanks, @johnnymatthews! I'll check out the link and make the necessary changes.

**Comment by ATREAY** [comment]
Hey @johnnymatthews, I've done the necessary updates. 
Could you please take a look when you have a moment?

**Comment by johnnymatthews** [comment]
Excellent, thanks for your help @ATREAY! I made a few minor tweaks to your PR and merged it in. Thanks again @ATREAY!

**Comment by ATREAY** [comment]
Thanks, @johnnymatthews! Really appreciate you handing me this issue and merging the PR.

**Comment by johnnymatthews** [comment]
No problem @ATREAY! We're always looking for great contributors like yourself! If you see anything else in the docs that could use improvement feel free to submit another PR.
