### ISSUE TITLE
Replace Chainlist.org links with ChainID.Network

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#2052]
There was a [recommendation from the folks that run Chainlist.org](https://github.com/ethereum-lists/chains/pull/2888) to start using ChainID.Network instead. This implies that maintenance on Chainlist.org will stop at some point.

## Tasks

- [x] Find and replace `chainlist.org` steps with `ChainID.Network`.

Keep in mind that the process for selecting a testnet on ChainID.Network is slightly different that Chainlist.org. Users must select the _filter_ icon and toggle *Show Testnets*

**Comment by longfeiWan9** [comment]
@ElPaisano @johnnymatthews Sorry to pick this up late. Actually the right link should be [ChainID.Network](https://chainid.network/), but not [chainlist.network](https://chainlist.network/). Can you guys help to fix that ?

**Comment by johnnymatthews** [comment]
Addressed in this one, no? https://github.com/filecoin-project/filecoin-docs/pull/2204

**Comment by longfeiWan9** [comment]
Looks like https://github.com/filecoin-project/filecoin-docs/pull/2204 fix that. But not reflected in docs.filecoin.io, not released yet ?

**Comment by johnnymatthews** [comment]
Ah I see what happened. Some of the changes from #2095 were incorrect. Fixed in [a6b78f0](https://github.com/filecoin-project/filecoin-docs/commit/a6b78f084c3aa97389391481659943b4c6b012de).
