### ISSUE TITLE
[Fix]: Update Lotus blurb on docs homepage 

### ISSUE THREAD

**Issue by juliaxbow** [filecoin-project/filecoin-docs#2092]
### Request type

Changes to existing content

### Describe the issue.

Where: docs.filecoin.io, quicklinks in second section
Description: Appears as though the description under Lotus was inadvertently replaced with the blurb for FVM. See screenshot below.

<img width="1318" alt="Screen Shot 2023-07-18 at 11 53 59 AM" src="https://github.com/filecoin-project/filecoin-docs/assets/58958327/68b8c759-d798-4248-bd97-409de0e63909">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
Nice catch @juliaxbow! It's been updated in PR #2094.
