### ISSUE TITLE
Improvements to the Basics section

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#2112]
According to [our analytics,](https://plausible.io/docs.filecoin.io) the Basics section of the Filecoin Docs is site is, by far, the most visited. They should be improved to help filter folks into other sections of the site. This issue serves as an epic.

We can improve the Basics section by doing the following:

- https://github.com/filecoin-project/filecoin-docs/issues/2119
- https://github.com/filecoin-project/filecoin-docs/issues/2115
- Including interactive tutorials or sandbox environments where users can try out basic Filecoin operations themselves.
- Increase the use of tooltips for this section.
- Provide real-world use cases that demonstrate how Filecoin can be utilized. This can help users understand the practical applications of the technology.

**Comment by ElPaisano** [comment]
@johnnymatthews for this super issue, we could:

1. divide this out into sub-issues
2. Split up the workload between us.  For example, I could take on the "Simplify the language and use less jargon. Avoid technical terms where possible, and if they are necessary, provide clear explanations in simple terms." task to start, would be a solid application of the various linter tools I've cobbled together 
3. Merge sub-issue as they are completed into `staging` once they are ready. Or, alternatively, could create a 'basics-improvements' branch that we merge into and review everything from there before squashing into a single nice commit that can be merged into staging. 

What do you think?

**Comment by johnnymatthews** [comment]
Ya so `#2` is the best solution. Let's each take one of the original tasks, create a new issue specifically for that task (and link here), and then have a todo list within that new issue listing the pages we've addresses.
