### ISSUE TITLE
Explain how providing storage for Filecoin works from a high-level persepctive.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#212]
We should have a more detailed explanation of how mining works. The information on the [Mine page](https://docs.filecoin.io/mine/), but we can get more detailed to provide some important conceptual information to people playing this role in the network.

Some of the concepts in [this blog post](https://filecoin.io/blog/filecoin-guide-to-storage-mining/) could be a good starting point.

**Comment by pooja** [comment]
Didn't notice #200 -- definitely some overlap. Will leave open since this issue focuses on conceptual overviews, rather than practical recommendations for miners (as the other issue does), although both are important and should be included.

**Comment by johnnymatthews** [comment]
@rstanberry this might be of interest to you. There's new content from the [Filecoin blog](https://filecoin.io/blog/#posts) that you can likely lend from, along with a load of information contained in videos in the [Filecoin YouTube channel](https://www.youtube.com/c/FilecoinProject/videos)

**Comment by Annamarie2019** [comment]
I've started it. In progress [Providing Storage on Filecoin](here: https://docs.google.com/document/d/110bwC8xnwoJU_scoQX24d7nMVrxVS-LQBpal1nKcuM0/edit?usp=sharing)

**Comment by Annamarie2019** [comment]
@johnnymatthews I'm just about to commit and create a pull request for Providing Storage.

The only thing I don't feel like I address as well as I'd like is Retrieval Storage, but, given my search, I think that may be the state of the feature. I searched our doc, specs, Filecoin video channel. I'll search in YouTube, unless you can confirm that it's just not as fully baked as Storage providing. Thanks.

**Comment by Annamarie2019** [comment]
@johnnymatthews Concerning Retrieval Providers: I'm not used to including future features in doc, but it was already in this and I wasn't sure of its status. It was starting to look like it isn't a full-fledged feature, so at least I put it into future tense ("will" everywhere). I got a status update from Patrick Woodhead this morning. He says: 
"When users upload files to Estuary, they are stored with 6 Filecoin storage providers and also made available for retrieval through the IPFS Gateway (https://filecoinproject.slack.com/archives/D03AZP27PKM/p1649691408226519)
So in this case the retrieval is available to users but via an IPFS gateway.
(https://filecoinproject.slack.com/archives/D03AZP27PKM/p1649691488471729)
Within the next few months, we hope to launch a retrieval network that will allow retrieval from Filecoin for end users without going through IPFS first."
So I can see us going one of several ways:
- leave retrieval out altogether
- leave it in with the future tense ("will") wording
- put it in saying it's available via IPFS gateway 

What do you think?

**Comment by Annamarie2019** [comment]
[#1234](https://github.com/filecoin-project/filecoin-docs/pull/1234)

**Comment by johnnymatthews** [comment]
#1234 has been merged. Closing.
