### ISSUE TITLE
[Fix]: Unreadable text in certain cards and buttons due to overridden css styles

### ISSUE THREAD

**Issue by juliaxbow** [filecoin-project/filecoin-docs#2125]
### Request type

Fix

### Describe the issue.

In Filecoin docs' dark mode, some CSS styles are being overridden, making text in some cards/buttons unreadable. Tried with chrome, brave, etc to make sure it wasn't an issue with my browser settings. See screenshots below:

[Becoming a Storage Provider](https://docs.filecoin.io/storage-provider/basics/overview/#:~:text=Storage%20providers%20in%20the%20Filecoin,technical%2C%20financial%20and%20business%20skills.)
<img width="1517" alt="Screen Shot 2023-07-27 at 2 19 05 PM" src="https://github.com/filecoin-project/filecoin-docs/assets/58958327/3c01d9ce-0bae-495b-8f61-619561aa6c82">

[Blocks and Tipsets](https://docs.filecoin.io/basics/the-blockchain/tipsets/)
<img width="1350" alt="Screen Shot 2023-07-27 at 2 18 30 PM" src="https://github.com/filecoin-project/filecoin-docs/assets/58958327/eda5424f-4901-4d27-ac81-542c05914132">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
Thanks for raising! Fixed in #2128.
