### ISSUE TITLE
[Request]: Point to PiKNiK's Calibration SPs

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2145]
### Request type

Point to PiKNiK's Calibration SPs

### Describe the issue.

PiKNiK has their SP on Calibration documentation here: https://github.com/benjaminh83/fvm-calib-deal-miners

Please point https://docs.filecoin.io/networks/calibration/details/ to it, perhaps where it says "[See the PiKNiK documentation for more details](https://docs.filecoin.io/networks/calibration/details/#)"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
I've added a new section called **Active storage providers** to list SPs devs can connect to on Calibration:

![image](https://github.com/filecoin-project/filecoin-docs/assets/9611008/19a31f8e-901d-44b9-9844-3fb2f2e5aa6c)

Also, is there anyway for https://github.com/benjaminh83/fvm-calib-deal-miners to move to an official-looking PiKNiK repo?

**Comment by eshon** [comment]
@johnnymatthews - Might be best to merge this for now and ask @benjaminh83 for your ask later
