### ISSUE TITLE
Create a page detailing the "Sealing" steps taken by miners.

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#216]
Sealing is one of the longest steps and where miners have lots of questions about whether they've hit a bug or an expected delay. Let's create a more detailed description of sealing (interim statuses/steps), error messages to look for, and troubleshooting steps.

Can @arajasek or @travisperson kick this off with a short description of what's happening in each of these (what is the softwarez doing and about how long should it take)? Any steps missing?
- waitSeed
- Precommit1
- Precommit2
- Proving
- FinalizeSector

**Comment by travisperson** [comment]
@cryptonemo can you provide us a short few sentences around the different proof phases so we can get some of the finer points accurate?

I know Precommit Phase 1 is replication and I believe Precommit Phase 2 is something to do with snarks. Similarly, I believe Commit Phase 2 is snark releated? I do not know what Commit Phase 1 is though.

**Comment by cryptonemo** [comment]
This doc is decent for the sealing phases: https://filecoin.io/blog/filecoin-guide-to-storage-mining/

I'm not familiar with waitSeed.

**Comment by johnnymatthews** [comment]
This issue will get closed with #212, since both issues cite the same blog post. Closing.
