### ISSUE TITLE
Point to DSS' Calibration SP.

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2163]
### Request type

Changes to existing content

### Describe the issue.

Please point https://docs.filecoin.io/networks/calibration/details/ to this, in addition to PiKNiK's Calibration SP as in https://github.com/filecoin-project/filecoin-docs/issues/2145

https://github.com/Distributed-Storage-Solutions/DSS_Calibration_Net_Miner

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
This information exists in https://docs.filecoin.io/networks/calibration#active-storage-providers. Closing.
