### ISSUE TITLE
Other fiat onramps for FIL in addition to exchanges.

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2164]
### Request type

New content

### Describe the issue.

Exchanges are not the only place where people can buy FIL. Fiat onramps offer the ability to purchase FIL via credit card, bank transfer, etc. Note that generally exchanges tend to have more favorable transaction fees and spot prices, but require new account KYC checks that can take some time to approve for new users. Fiat onramps, on the other hand, offer greater convenience in exchange for higher fees.

FIL is supported by a number of fiat onramps like [MoonPay](https://www.moonpay.com/), [Ramp Network](https://ramp.network/), [Changelly](https://changelly.com/), [ChangeNow](https://changenow.io/), [Simplex](https://www.simplex.com/).

Users are cautioned to do their own due diligence with respect to choosing a fiat onramp provider.

### Is there any other information we need to know?

It _might_ be good to quickly run this page by someone from legal.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
> It might be good to quickly run this page by someone from legal.

Good call.
