### ISSUE TITLE
Filecoin Documentation Discord Bot: Grants Proposal

### ISSUE THREAD

**Issue by realChainLife** [filecoin-project/filecoin-docs#2191]
We received a [grant proposal](https://github.com/filecoin-project/devgrants/issues/1633) for the development of a documentation discord bot based on Large Language Models to serve query responses linked to the docs. @johnnymatthews is this implementation feasible or beneficial for docs-use?

**Comment by johnnymatthews** [comment]
Not particularly. We already have a docs AI integration in the form of lens:

<img width="777" alt="Screenshot 2023-09-13 at 08 46 41" src="https://github.com/filecoin-project/filecoin-docs/assets/9611008/f61b9bda-2f7f-4fcd-8619-ed75c42f2ab8">

Furthermore, external integrations into the docs site must follow the [GitBook integrations process](https://www.gitbook.com/integrations). Finally, an Discord-based LLM would require readers to bounce over to the Discord app - this UX isn't ideal.

I'm going to close this issue, but feel free to keep the discussion going. I may be missing some key aspects of this grant proposal.

**Comment by realChainLife** [comment]
Thanks for the additional context. We should be good to make a funding decision based on this details.
