### ISSUE TITLE
Please don't use 'Partners'

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#22]
There's an Ecosystem Partners section. Don't use the term Partners, it has special meaning in business communities and open source. Safer to say Collaborators.

**Comment by terichadbourne** [comment]
Thanks for flagging @eshon! @mishmosh flagging for your review. I'm happy to make this change if you agree. This page doesn't currently have content, so we can also delete the section if you don't envision needing it or implementing it in the near future. 

https://filecoin-docs.netlify.app/introduction/ecosystem/

**Comment by mishmosh** [comment]
Yes, please delete this for now. Might belong in the website, not docs.

**Comment by terichadbourne** [comment]
On it!

**Comment by terichadbourne** [comment]
closed by #32
