### ISSUE TITLE
Explain how to connect the network inspector application to the mainline testnet.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#221]
In [this step of our network inspector example application/tutorial](https://docs.filecoin.io/build/examples/network-inspector/step-3-set-up-the-lotus-and-go-ipfs-api-clients/#step-3a-set-up-the-lotus-api-client), we show how to run the application against a local network (using a fork of textile's localnet). We've gotten requests from users to include steps for how to run this application against testnet as well so they can see how to connect their application to testnet.

What this needs: steps for how to set up the application if you wanted to connect it to testnet.

![Screen Shot 2020-08-04 at 6 53 32 PM](https://user-images.githubusercontent.com/5668171/89363069-3287a900-d684-11ea-83da-b5f2d2c35ccc.png)

**Comment by johndmulhausen** [comment]
Closed per discussion w/Pooja
