### ISSUE TITLE
Refresh  https://docs.filecoin.io/storage-providers/filecoin-deals/filecoin-programs

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/filecoin-docs#2252]
https://github.com/filecoin-project/filecoin-docs/blob/main/storage-providers/filecoin-deals/filecoin-programs.md

The list of programs needs to be brought up to date, including 3rd party data onboarding tools. 
-Live programs at the top.
-Deprecated programs below. 
 
Each entry section should have a good explanation of features, what it does, who's it for, etc including:

- docs and website
- team owning it
- github link
   -  check that repos also have a deprecation notice/
- deeplink to slack channels
- date when launched (month, year), when deprecated. 
- any other links to videos etc.
- related projects. 

(what have I missed?)

**Comment by smagdali** [comment]
As per Porter's suggestion - we should flag which commercial providers are in test or live, and have a disclaimer that being on this list is not an endorsement...

**Comment by jochasinga** [comment]
@smagdali why is there a need for specific time when launched for deprecated projects?

**Comment by jochasinga** [comment]
#2253 is addressing this issue right now.

**Comment by jochasinga** [comment]
> > @smagdali why is there a need for specific time when launched for deprecated projects?
> 
> No, I guess not. But we should say when they shut down.
> 
> I Iike the styling, let's get all the programs (from the doc) in next.

I don't think it's possible to know exactly when, or even if they did.

**Comment by jochasinga** [comment]
Done for now.

**Comment by jochasinga** [comment]
Reopening as the badges are messing up the deployed page.

**Comment by jochasinga** [comment]
#2269 fixes this issue @smagdali
