### ISSUE TITLE
Repo-wide broken links failing CI

### ISSUE THREAD

**Issue by jochasinga** [filecoin-project/filecoin-docs#2255]
There is currently a slew of broken links that [fails the CI test](https://github.com/filecoin-project/filecoin-docs/actions/runs/9214741632/job/25351614546?pr=2253). I think it's about time we hunt and prune @smagdali 

See also: [This discussion](https://github.com/filecoin-project/filecoin-docs/pull/2253#issuecomment-2116598845)

**Comment by jochasinga** [comment]
We should start with fixing this https://docs.filecoin.io/reference/general

**Comment by jochasinga** [comment]
This is potentially blocking a different merging workflow on gitbook by @robertagora #2257

**Comment by robertagora** [comment]
Doc with broken links is here: https://docs.google.com/document/d/1jznl6MeP6qtsD23SkCneR-DaBB6QB_xGKZV7p5JwKn4/edit

**Comment by robertagora** [comment]
Resolved with this merged PR [HERE](https://github.com/filecoin-project/filecoin-docs/pull/2262)
