### ISSUE TITLE
Add BlockScout to Explorers page

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2280]
Add to https://docs.filecoin.io/networks/mainnet/explorers

Blockscout Open-Source FEVM Explorer

https://filecoin.blockscout.com/

Optional info:

Features include:
Robust search, smart contract verification and interaction, internal transactions, advanced statistics, gas tracker, REST and JSON RPC APIs.

**Comment by trruckerfling** [comment]
thanks! moving this to done fyi pls close for next time @XORS-eng
