### ISSUE TITLE
Document MULTICALL3 in Filecoin Docs

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2288]
https://www.multicall3.com/

Is currently deployed to `0xcA11bde05977b3631167028862bE2a173976CA11`

See for verification:
https://filfox.info/en/address/0xcA11bde05977b3631167028862bE2a173976CA11?t=3

It also needs to be verified properly here:
https://filecoin.blockscout.com/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
(showing wrong contract from another chain - I've just flagged this to the BlockScout team)

More info about what this does is here:
https://github.com/mds1/multicall

Also needs to be documented for Calibration testnet

Might be nice to start a page in the Docs that tries to keep track of all important deployed contracts on FEVM that EVM devs find useful.

**Comment by trruckerfling** [comment]
Thanks! For contracts, wouldn't it be better to have them listed on explorers to keep them updated? Looking at etherscan, that seems to be the place devs look at for contract lists cc: xiangan @XORS-eng for any input and can we add this to painpoint pls?

**Comment by eshon** [comment]
@trruckerfling The reality is we have a lot of block explorers with varying levels of support for contract verification and also contract naming. While we can try to mandate they all list these and make them searchable, it will take a while, and would be easier for now to start a helpful list for them in the Filecoin Docs.

**Comment by xBalbinus** [comment]
Got you

**Comment by xBalbinus** [comment]
Seems like the link from Blockscout has been corrected. Do we want verified contracts on Calibration?

![Image](https://github.com/user-attachments/assets/b6142206-65a3-4e54-8339-504f0e5bdd33)

**Comment by eshon** [comment]
> Do we want verified contracts on Calibration?

Doesn't hurt to try

**Comment by eshon** [comment]
FYI 

From BlockScout:

> Regarding the Filecoin-specific smart-contracts, the best you can do is probably to manually verify those contracts on at least one blockscout instance. That way the contract code would be added into Bytecode DB and in case of full match will be automatically found by all other instances. If there would be only partial match available, Bytecode DB returns the latest verified contract code.
> Besides, contracts automatically verified from [Sourcify.dev](http://sourcify.dev/) are not added into the Bytecode DB unfortunately. We are planning to add such support, but it is not implemented yet

Therefore if you can verify Mainnet contracts on filecoin.blockscout.com that would be helpful. I've asked Filfox and Beryx to try to use[ BlockScout's EBD.](https://docs.blockscout.com/about/features/ethereum-bytecode-database-microservice)

I've also asked BlockScout for a quote on a Calibration testnet instance but for now we just have Filfox and Beryx on Calibration afaik.

**Comment by trruckerfling** [comment]
Ongoing PR, in final review stages: https://github.com/filecoin-project/filecoin-docs/pull/2291#issuecomment-2250784609

**Comment by longfeiWan9** [comment]
Adding my last few small suggestions, will be ready to publish soon.
