### ISSUE TITLE
Run LinkChecker only once per week

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2319]
Constant linkChecker issues from CI runs triggered by Docs PRs are problematic.

- No PR should be merged if a CI run fails.
- linkchecker issues sometimes prevent updates to the live Filecoin Docs site causing confusion among Contributors.
- ecosystem project links get updated, come and go, and sometimes take a while to load
- The linkChecker Github Action is [here](https://github.com/filecoin-project/filecoin-docs/blob/main/.github/workflows/check-external-links.yml)

Options:

Option 1. Run linkchecker via Github Actions only once per week if a PR is made that week
   - This would require a dev like @lanzafame or Fil-B DevRel (@trruckerfling) to modify the Github Actions yml for this repo using something like https://github.com/orgs/community/discussions/26519
  
Option 2. People who know how to [skip actions](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs) use that in their PRs and **everyone else needs to held accountable for fixing broken linkchecker CI issues before merging PRs.**

cc: @smagdali @robertagora @longfeiWan9 @xBalbinus

**Comment by nourakhy** [comment]
maybe this will help
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by BigLep** [comment]
Per DM, it looks like I was a contributor here with https://github.com/filecoin-project/filecoin-docs/pull/2323 when I moved certain URLs out of `<code>` blocks.   I'm game to engage here to improve the situation.

My thoughts:
1. Lets go with option 2 where we actually have branch protection rules that prevent pushing to the repo if the checks are failing.  That way bad links don't build up.
2. Lets document the way to work around the link checking if someone needs to.
3. Lets get all links valid again.
4. (bonus) Lets add a badge for our link status.

I'll take a stab on this and update where I get to.

**Comment by BigLep** [comment]
I think this can be resolved once https://github.com/filecoin-project/filecoin-docs/pull/2327 is closed.
