### ISSUE TITLE
Create content voting stubs and associated issues.

### ISSUE THREAD

**Issue by cwaring** [filecoin-project/filecoin-docs#233]
Based on content gaps in the new docs structure we should create content placeholder pages, using the `<ContentStatus />` component in order to collect voting data from each topic in order to help influence our priorities.

ref: https://github.com/ipfs-inactive/docs/issues/342

**Comment by johnnymatthews** [comment]
Hey @cwaring, are you still looking to build this, or can we close it?

**Comment by cwaring** [comment]
This exists in the codebase but we need to discuss what topic outlines we wish to test and get metrics on. I guess we can close it for now if you don't see that on the immediate horizon?

**Comment by johnnymatthews** [comment]
I've lowered the priority, as there's a bunch of other stuff we need to get done with the resources we currently have. Probably a good idea to keep the issue around though. If/when we have more folks to devote to this project, we can pick this up again.

**Comment by johndmulhausen** [comment]
Per chat w/@cwaring we're closing since there are alternatives for collecting this kind of feedback and the docs are too fleshed out to be littered w/random stubs
