### ISSUE TITLE
Sector upgrade page - Space Race

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#238]
We need to describe the sector upgrade actions that are required from miners to qualify for Space Race rewards.

1. @magik6k to show screenshots/instructions to...
- commands to upgrade/terminate/extend a sector
- show that sector was upgraded in sector list
- what an upgrade looks like on chain

2. @har00ga to edit & turn this into a new page in the Mine section.

The purpose of this upgrade is to swap a CC sector for real deal data. Once mining begins for real, miners would do this if they run out of disk space.

cc @zixuanzh @momack2

**Comment by momack2** [comment]
@ribasushi - could you maybe help take a pass at this and magik can add any corrections?

**Comment by ribasushi** [comment]
We don't have commands for `extend` at all: it is not possible in the current version of actors.

upgrade/terminate need to be validated on nerpa at least once ( supposedly tomorrow everything will be functional )
I'll make a pass as soon as that's a thing.

**Comment by mishmosh** [comment]
- sector extension is now a post-mainnet thing
- sector termination fell out of space race due to time constraints
- as a miner, to ugrade a sector, you need to find a CC sector ( looks like `1: Proving sSet: YES active: YES tktH: XXXX seedH: YYYY deals: [0]` in `lotus-miner sectors list`) and call `./lotus-miner sectors mark-for-upgrade {{sector-number}}`

No immediate signal of success/fail. Bot is getting fixed and will show success.

If everything works correctly, eventually (24ish hours later), that sector will start looking like:
`1: Proving sSet: YES active: NO tktH: XXXX seedH: YYYY deals: [0]`
the sector will not go away / free space - this is to be implemented after space race

that `1:` at the start is the `{{sector-number}}` to use in the `mark-for-upgrade` command
