### ISSUE TITLE
Migrate & update Mining instructions from lotu.sh

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#250]
Please migrate the mining content currently in https://lotu.sh/en+mining into the Mine section of this site (Storage Mining, Lotus Seal Worker, Static Ports, Troubleshooting). The static ports section may already been in Improving connectivity; if there's anything new please incorporate into there.

Keep in mind several things have changed and need to be updated (one of the motivations for moving here):

- Create miner instructions are different now (no longer part of the faucet). You now have to use the command line to create a miner by creating a bls wallet, getting funds from the faucet, and then using the the miner init command `./lotus-miner init --owner=<bls-address-with-funds> --sector-size=[512MiB|32GiB|64GiB]`

- These instructions assume Testnet only, please modify so that they can apply to any network.

- At least one of the key commands have been renamed - I think it was `lotus-miner` vs `lotus-miner-actor`. Please run locally and check though.

Ideally can publish by Fri Aug 14 to reduce the volume of new miner questions.

**Comment by johnnymatthews** [comment]
How's this going @har00ga? I'm running through the existing mining docs now, just playing around with things. I can lend a hand, or wait until you post a PR if you're in the middle of things (don't want to step on your toes).

**Comment by johnnymatthews** [comment]
> These instructions assume Testnet only, please modify so that they can apply to any network.

I don't know how to do this. Any chance you can tackle this @mishmosh in #256?
