### ISSUE TITLE
Add information on how to separate the sealing and storage locations for a Lotus miner.

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#254]
These are additional mining instructions that most miners need to know:

- How to configure separate sealing vs storage locations
https://github.com/filecoin-project/lotus/issues/2956#issuecomment-671524060

- Miner configuration in general with `config.toml`
https://github.com/filecoin-project/lotus/issues/2956#issuecomment-673145041

**Comment by johndmulhausen** [comment]
Covered here: https://docs.filecoin.io/mine/lotus/custom-storage-layout/
