### ISSUE TITLE
New nav hides the content you wanted

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#263]
The new breadcrumb feature is sweet, but has a couple usability issues that come up when clicking on subheader links. For example, go to https://docs.filecoin.io/mine/spacerace/#frequently-asked-questions and then click "Can I run multiple miners?"

![image](https://user-images.githubusercontent.com/1306020/90696614-98f6f480-e24a-11ea-9651-4e741e22b3fe.png)

Problems:
1. The content scrolls underneath the breadcrumb bar, so the first lines aren't visible.
2. The URL resets to the original page, instead of the https://docs.filecoin.io/mine/spacerace/#can-i-run-multiple-miners deep link (this took me a few times to realize, ping if you want to see this on screenshare).

@cwaring can you take a look once you're back online?

**Comment by cwaring** [comment]
Thanks for catching that, I built a plugin for protocol.ai that fixed this hash offset issue so I’ll try to port it over tomorrow.
