### ISSUE TITLE
Update wallet creation instructions

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#275]
Followup to #258.

The instructions in https://docs.filecoin.io/how-to/join-a-network/#create-your-first-address
assume that the faucet website includes a GUI for wallet creation, which is no longer supported in the new faucets for calibration and testnet (eg https://faucet.glif.io/).

1.
> Use an appropriate faucet to acquire FIL

Give users a bit more help on how to find the appropriate faucet. (describe & link to networks page, maybe?)

2.
> Paste the address you created
> Press the send button

We might not even need these steps anymore.

3.
> Here is an example of the response:

Might also mention "this is your default wallet address".

**Comment by johnnymatthews** [comment]
Pretty sure this isn't relevant anymore. Closing.
