### ISSUE TITLE
If a deploy happens and I have the documentation opened I lose the ability to navigate to other pages using the menu

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#276]
**URL of the page in question:**
https://docs.filecoin.io/

**What's wrong with this page?**
It requests the JavaScript file when you click an item in the menu, but if the file has changed while you had the page opened it might request a file that no longer exist.

**What would you like to have changed/amended/fixed in order to make things right?**
Here are a few brainstorm ideas:

- Option 1: if the request to the script returns 404 do a full page redirect to the menu url
- Option 2: if the request to the script returns 404 show a message that the website was update and let the user manually do a full reload
- Option 3: remove the need of having to load a JavaScript file to navigate to another page

**Would you be interested in helping fix this page?**
\-

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

## Steps to reproduce
1. open https://docs.filecoin.io/
1. wait for a website deploy
1. click a link in the menu

## Expected
Page to load

## Actual
Website makes a request to a JavaScript file that no longer exist

```
Request URL: https://docs.filecoin.io/assets/js/59.85ee1e72.js
Request Method: GET
Status Code: 404 
```

If the user fully reloads the page and clicks the same item in the menu

```
Request URL: https://docs.filecoin.io/assets/js/60.73de75a7.js
Request Method: GET
Status Code: 200
```

The file hash changed from `59.85ee1e72.js` to `60.73de75a7.js`. If the user doesn't refresh the page they get stuck forever unable to navigate the website.

It seems that the hash is associated with a section of the documentation, seems to be related to some sort of lazy loading.

**Comment by johnnymatthews** [comment]
My knowledge of the website infra is limited, but I wonder if this happens with `docs.ipfs.io`. Just to catch you up @brunolm, the IPFS docs site is _hosted_ on IPFS, whereas the Filecoin docs site isn't. I imagine that shouldn't be a problem with IPFS (since the file `/assets/js/xyz.123456.js` would be hosted from the CID, and should still exist in the IPFS cache, no?).

@cwaring would likely know. Would this problem disappear is Filecoin docs used IPFS?

**Comment by cwaring** [comment]
This is related to how Netlify builds are atomic so the old JS chunks for each route no longer exist after a deploy. 

Related:
https://github.com/vuejs/vuepress/issues/2090
https://community.netlify.com/t/keep-js-chunks-from-old-deploys/5991
https://github.com/gatsbyjs/gatsby/issues/18866

I suspect it would behave the same on IPFS considering the domain is pointing to a root CID but I'd need to test this, in the meantime I'll apply a patch to reload the app/url if this error is caught and I that _should_ fix the problem in most cases.
