### ISSUE TITLE
Introduction block doesn't match menu structure

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#293]
**URL of the page in question:**
https://docs.filecoin.io/

**What's wrong with this page?**
Introduction block links are different from menu links.

![image](https://user-images.githubusercontent.com/706078/91206195-21f3ad00-e6dd-11ea-87a3-3620d2a73780.png)

**What would you like to have changed/amended/fixed in order to make things right?**
1. Move `New to web3` and `Filecoin FAQ` inside `What is Filecoin?`; or
1. Include `New to web3` and `Filecoin FAQ` in the Introduction block

Personally I prefer having `New to web3` inside `What is Filecoin?` because my primary goal is to know what Filecoin is and not web3. After reading an introduction to what is Filecoin I will then be able to understand why web3 is important, so this sequence makes more sense to me.

**Would you be interested in helping fix this page?**
yes

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Nice find! Would you be willing to tackle this yourself @brunolm?

**Comment by brunolm** [comment]
@johnnymatthews yes, I can make a PR
