### ISSUE TITLE
Explain what web3 is and how it relates to Filecoin.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#295]
**URL of the page in question:**
https://docs.filecoin.io/introduction/new-to-web3/

**What's wrong with this page?**
It doesn't explain what web3 is and how it's related to Filecoin.

**What would you like to have changed/amended/fixed in order to make things right?**
Add at least one paragraph explaining what web3 is and how it's relevant to Filecoin.

We could use illustrations like they have on http://blockchainhub.net/web3-decentralized-web/

![image](https://user-images.githubusercontent.com/706078/91230345-ba038d80-e701-11ea-93c3-539da0bdea0e.png)

![image](https://user-images.githubusercontent.com/706078/91230354-bd971480-e701-11ea-8b89-c2c860ed6aa8.png)

**Would you be interested in helping fix this page?**
yes, I can write some content, however I'm not good with images so I wouldn't be able to create illustrations.

Working on this might conflict with changes made on https://github.com/filecoin-project/filecoin-docs/pull/294

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
I agree that we should explain what web3 is and why it's important. Fortunately there's a bunch of content on the internet explaining what web3 is already, so we don't need to go into a huge amount of details. We can use the [Binance Evolution of the Internet article](https://academy.binance.com/blockchain/the-evolution-of-the-internet-web-3-0-explained) as a starting point.
