### ISSUE TITLE
Remove links from "New to web3" page.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#296]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/introduction/new-to-web3/

**What's wrong with this page?**
The page provides links to `IPFS, libp2p, and Filecoin`, but it doesn't explain why or how those links are relevant to Filecoin. It needs some context so I can understand why I have to read/learn about these technologies.

**What would you like to have changed/amended/fixed in order to make things right?**
Some explanation of what those links are and why I should know about them.

**Would you be interested in helping fix this page?**
yes, I can help put something together but I'd be good if I could get some more context myself.

Working on this might conflict with changes made on https://github.com/filecoin-project/filecoin-docs/pull/294

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
I think we can actually removes these links. They're alluding to information that can be covered in [IPFS and Filecoin](https://docs.filecoin.io/introduction/ipfs-and-filecoin/).

## Tasks

- [ ] Remove the **Vision** section.
- [ ] Remove the **IPFS, libp2p, and Filecoin** section.
