### ISSUE TITLE
Include instructions on how to switch networks.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#297]
**URL of the page in question:**
https://docs.filecoin.io/how-to/networks/

**What's wrong with this page?**
There's no instructions on how to switch to a different network after you've already joined one.

**What would you like to have changed/amended/fixed in order to make things right?**
In order to do so you have to remove the `~/.lotus` folder. This should be in the documentation somewhere.

```
rm -rf ~/.lotus
```

**Would you be interested in helping fix this page?**
yes I can make a PR

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Closing this issue in favour of #638
