### ISSUE TITLE
Include a "branch" column in the networks table.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#298]
**URL of the page in question:**
https://docs.filecoin.io/how-to/networks/

**What's wrong with this page?**
Table doesn't include a branch, could be potentially useful to quickly lookup.

**What would you like to have changed/amended/fixed in order to make things right?**
Add a branch column to the table.

Potential issues:
1. not enough horizontal space
    - could be solved by removing Sector Size and/or Stability

**Would you be interested in helping fix this page?**
yes, need to know if this makes sense and if I should remove something from the existing table

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Redirect is now in place. Closing.
