### ISSUE TITLE
Explain what a "chain-sync" is.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#299]
**URL of the page in question:**
https://docs.filecoin.io/how-to/join-a-network/#chain-sync

**What's wrong with this page?**
What is a chain sync? The page gives me instructions to run a command I don't understand what it's for.

**What would you like to have changed/amended/fixed in order to make things right?**
Some information about the command, what is its purpose and why do I need it.

**Would you be interested in helping fix this page?**
yes, but I need to learn about it first.

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Installation guide has been updated. Closing.
