### ISSUE TITLE
Deploy docs site on IPFS

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/filecoin-docs#3]
Work with Marcus on a deployment plan for a first draft of this site, aiming for 3/20. 
We're essentially cloning the IPFS Docs Beta site (https://github.com/ipfs/ipfs-docs-v2) to get started with its nice VuePress formatting, so Chris (who led the IPFS Docs project) mentioned that [this issue](https://github.com/protocol/bifrost-infra/issues/487) may provide some helpful context around how it was set up by Oli to be hosted on the IPFS gateway.

- [ ] CLI
- [ ] DNS

**Comment by terichadbourne** [comment]
For now have deployed the draft on Netlify at: https://filecoin-docs.netlify.com/

**Comment by terichadbourne** [comment]
@andyschwab Thanks for offering to look into the IPFS hosting for us! I learned yesterday that this file in the IPFS docs repo includes a lot of the related setup required for hosting on IPFS: https://github.com/ipfs/ipfs-docs-v2/blob/master/.circleci/config.yml (The equivalent file doesn't currently exist in our Filecoin fork.) 

Hugo and Chris built a plugin to deal with the hash routing complications of hosting a VuePress SPA on IPFS, so we'll need to use that as well. (Haven't thoroughly checked to see if that bit is already in our codebase from the fork.)

**Comment by terichadbourne** [comment]
This issue is going to be complicated by the need for redirects to the old go-filecoin-tutorial that previously lived at the URL we're taking over, so we're tabling until after launch.

**Comment by cwaring** [comment]
I'd be keen to know if there is an update to deploying redirect on Fleek? I've since setup the [vuepress-plugin-ipfs](https://github.com/cwaring/vuepress-plugin-ipfs) so the app is ready to work from an IPFS gateway now. If this could be a while yet I might take advantage of the Netlify config to add a smart 404 page and other optimisations.

**Comment by andyschwab** [comment]
@cwaring - good news, at least some of this functionality should be available through Fleek as early as the end of this week (they are in the midst of migrating to IPFS 0.6, which includes custom 404s: https://blog.ipfs.io/2020-06-26-go-ipfs-0-6-0/)

**Comment by johndmulhausen** [comment]
There is a Fleek project with this building already and vuepress-plugin-ipfs is installed, so we think we just need to "cut over" 

https://app.fleek.co/#/sites/filecoin-project-filecoin-docs/overview?accountId=protocollabs-team

https://ipfs.fleek.co/ipfs/QmUGJEeCRhMHM8c5GiouSM8Bk7iksgwpXZbhhAaiYzXaS3/

**Comment by andyschwab** [comment]
@johndmulhausen - thanks for your patience! If the builds look good, I can swap over DNS as soon as you give me the green light!

**Comment by cwaring** [comment]
Please make sure there are meta redirects in place for all of these items before transitioning over 👉🏻  [_redirects](https://github.com/filecoin-project/filecoin-docs/blob/master/docs/.vuepress/public/_redirects), @johnnymatthews should know how to do this already but if you need a hand LMK.

**Comment by cwaring** [comment]
Also there is currently a [404 search page](https://docs.filecoin.io/not-found) in place that captures these links to GA, is it possible to do this on Fleek?

**Comment by andyschwab** [comment]
@cwaring - good news! Fleek's deployment should honor [v0.6.0's](https://github.com/ipfs/go-ipfs/releases/tag/v0.6.0) ipfs-404.html, so the site just needs to generate / provide the preferred 404 in the root output directly.

**Comment by johnnymatthews** [comment]
Fleek _were_ having an issue with serving the wrong CID. It looks like they've fixed that issue now, so we can move this project over to Fleek.
