### ISSUE TITLE
Clarify the need for a wallet when connecting to a network.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#300]
**URL of the page in question:**
https://docs.filecoin.io/how-to/join-a-network/#create-your-first-address

**What's wrong with this page?**
The following sections on this page feel out of place:

- Create your first address
- Check wallet address balance
- Send FIL to another wallet

Why do I need these operations to join a network? Shouldn't they be a part of a different section?

**What would you like to have changed/amended/fixed in order to make things right?**
Maybe move these instructions to its own section.

**Would you be interested in helping fix this page?**
yes if I have the instructions where this content should live

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
This is now addressed in https://docs.filecoin.io/get-started/lotus/send-and-receive-fil/. Closing.
