### ISSUE TITLE
Give more context to the video included on the Mine > Connectivity page.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#301]
**URL of the page in question:**
https://docs.filecoin.io/mine/connectivity/#improving-connectivity

**What's wrong with this page?**
The video in this page doesn't explain what is going on. It might make sense for people that are deeply involved in this technology, but for beginners it's not clear what is happening.

**What would you like to have changed/amended/fixed in order to make things right?**
Remove the video or create a new one with explanations on every step and more context.

**Would you be interested in helping fix this page?**
\-

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Video has been removed. Closing.
