### ISSUE TITLE
Fix the "node" and "go" commands in the Web Applications example.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#302]
**URL of the page in question:**
https://docs.filecoin.io/build/examples/web-applications/overview/#set-up-your-environment-macos

**What's wrong with this page?**
Commands to install `node` and `go` should not include `.` after it

**What would you like to have changed/amended/fixed in order to make things right?**
Remove `.` after the commands described above

**Would you be interested in helping fix this page?**
\-

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Closing issue.
