### ISSUE TITLE
Build > Introduction > How do I acquire FIL tokens to pay for Filecoin storage?

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#308]
**What's the subject of the item you're requesting?**
How do I acquire FIL tokens to pay for Filecoin storage?

Alternatively:
- How to acquire FIL tokens to pay for Filecoin storage
- FIL Faucets and dev networks

**What's the content of the item you're requesting?**
How to acquire FIL tokens to pay for Filecoin storage. Maybe and end-to-end explanation

**What will the user know how to do after going through this item?**
How to acquire FIL tokens to pay for Filecoin storage

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Addressed here: https://docs.filecoin.io/get-started/lotus/send-and-receive-fil/#obtaining-fil

Closing.
