### ISSUE TITLE
Build > Getting Started > Choose your application architecture

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#309]
**What's the subject of the item you're requesting?**
Choose your application architecture

**What's the content of the item you're requesting?**
choose whether building on hosted nodes, local nodes, etc

mention SDKs if any

**What will the user know how to do after going through this item?**
How to choose their application architecture

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
This is covered in the /build section here: https://docs.filecoin.io/build/

Closing.
