### ISSUE TITLE
Build > Getting Started > ⚡️Install Filecoin

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#311]
**What's the subject of the item you're requesting?**
⚡️Install Filecoin

**What's the content of the item you're requesting?**
How to install Filecoin

**What will the user know how to do after going through this item?**
⚡️Install Filecoin

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
This is addressed here: https://docs.filecoin.io/get-started/lotus/installation/

Closing.
