### ISSUE TITLE
Build > Getting Started > Set up a Lotus API client

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#313]
**What's the subject of the item you're requesting?**
Set up a Lotus API client

**What's the content of the item you're requesting?**
How to setup Lotus API client

**What will the user know how to do after going through this item?**
Set up a Lotus API client

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by pooja** [comment]
Hey @brunolm ! Some initial thoughts on this issue:
- Right now, there are a few main lotus API clients:
  - The core lotus JSON-RPC API client: Some [intro docs here](https://lotu.sh/en+api), the [relevant godoc](https://godoc.org/github.com/filecoin-project/lotus/api)
  - JS API client: [Repo](https://github.com/filecoin-shipyard/js-lotus-client), which also contains its own set of documentation. @alanshaw is the maintainer for this repo now.
  - Ruby API client: [Repo](https://github.com/subvisual/filecoin-ruby)
- For any of these, you should feel free to ask questions about the API clients in the Filecoin Slack workspace. Feel free to tag or DM `@Aayush Rajasekaran` for the lotus JSON-RPC API, `@Alan Shaw` for the JS API, and `@pfac` for the Ruby API.
- This guide should have 3 main sections: How to set up and use the lotus JSON-RPC API, how to set up and use the lotus JS API, and how to set up and use the Ruby API.

Let me know if you have any questions! Also cc @hsanjuan for visibility

**Comment by hsanjuan** [comment]
This one is very unclear to me. If obtaining the token is already explained in the intro, the API reference is somewhere else, we are left with a page that should just have links to clients implementation (which should carry their own language-specific docs).

**Comment by johnnymatthews** [comment]
This info mostly gets addressed [here](https://docs.filecoin.io/build/lotus/api-client-libraries/#frontmatter-title) and [here](https://docs.filecoin.io/build/examples/network-inspector/overview/). I'm inclined to close this. Feel free to re-open if you think we need to expand on things a bit further @pooja .
