### ISSUE TITLE
Build > Getting Started > ⚡️Managing FIL assets

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#314]
**What's the subject of the item you're requesting?**
⚡️Managing FIL assets

**What's the content of the item you're requesting?**
How to manage FIL assets

**What will the user know how to do after going through this item?**
⚡️Managing FIL assets

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
[Send and receive FIL addresses this](https://docs.filecoin.io/get-started/lotus/send-and-receive-fil/). Closing
