### ISSUE TITLE
Build > Getting Started > Integrating wallets for user payments

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#315]
**What's the subject of the item you're requesting?**
Integrating wallets for user payments

**What's the content of the item you're requesting?**
How to integrate wallets for user payments

**What will the user know how to do after going through this item?**
Integrating wallets for user payments

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Out of scope. Closing.
