### ISSUE TITLE
Build > Tutorials > Write a simple “hello, world” application on lotus

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#316]
**What's the subject of the item you're requesting?**
Write a simple “hello, world” application on lotus

**What's the content of the item you're requesting?**
Instructions to build a "hello world".

**What will the user know how to do after going through this item?**
Write a simple “hello, world” application on lotus

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
This issue can be readdressed when Filecoin adds smart contracts.
