### ISSUE TITLE
Build > Tutorials > Create application user accounts

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#317]
**What's the subject of the item you're requesting?**
Create application user accounts

**What's the content of the item you're requesting?**
Create application user accounts

**What will the user know how to do after going through this item?**
Create application user accounts

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Not sure what this one is about. Closing.
