### ISSUE TITLE
Build > Tutorials > Prepare application data for storage

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#318]
**What's the subject of the item you're requesting?**
Prepare application data for storage

**What's the content of the item you're requesting?**
Prepare application data for storage

**What will the user know how to do after going through this item?**
Prepare application data for storage

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Closing, no scope.
