### ISSUE TITLE
Build > Tutorials > Store and retrieve data

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#319]
**What's the subject of the item you're requesting?**
Store and retrieve data

**What's the content of the item you're requesting?**
Store and retrieve data. links out to the Store pages as needed

**What will the user know how to do after going through this item?**
Store and retrieve data

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Closing, no scope.
