### ISSUE TITLE
Build > Tutorials > Create a payment channel

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#322]
**What's the subject of the item you're requesting?**
Create a payment channel

**What's the content of the item you're requesting?**
Create a payment channel

**What will the user know how to do after going through this item?**
Create a payment channel

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by johnnymatthews** [comment]
Closing, no scope.
