### ISSUE TITLE
refactor: use the global app sidebar to populate the homepage index items

### ISSUE THREAD

**Issue by cwaring** [filecoin-project/filecoin-docs#335]
Currently the [Home.vue](https://github.com/filecoin-project/filecoin-docs/blob/master/docs/.vuepress/theme/components/Home.vue) component uses a manual array to populate the homepage blocks, this leads to inconsistencies as the documentation tree changes. Fix this to use the global [themeConfig.sidebar](https://vuepress.vuejs.org/theme/default-theme-config.html#sidebar) array.

**Comment by johndmulhausen** [comment]
This has diverged since the home page is not in sync w/left nav. Closing
