### ISSUE TITLE
Meme Marketplacee contracts that are being imported don't have the same solidity version that Truffle supports.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#350]
**URL of the page in question:**
https://docs.filecoin.io/build/examples/meme-marketplace/step-1-blockchain-and-contracts-setup/#blockchain-and-smart-contract-setup

**What's wrong with this page?**
`truffle@5` and `@zeppelin/contracts@3` are not compatible leading to an error when `truffle migrate` is executed:

```
Error: Truffle is currently using solc 0.5.16, but one or more of your contracts specify "pragma solidity ^0.6.0"
```

**What would you like to have changed/amended/fixed in order to make things right?**
A combination of versions that work or an alternative.

**Would you be interested in helping fix this page?**
\-

**Comment by vasa-develop** [comment]
Thanks for posting this here @brunolm. I will get in touch with openzeppelin/truffle teams to get this resolved.

**Comment by vasa-develop** [comment]
I added this to my `truffle-config.js` which fetches `0.6.2` version (in your case it seems like it's `0.6.0`).

```
compilers: {
    solc: {
      version: "0.6.2", // Fetch exact version from solc-bin (default: truffle's version)
    },
  },
```

I'm able to compile the contracts using this. @brunolm can you try this again and let me know if this works for you or not?

I'll add a PR to add instructions in the docs to enable `0.6.2` solc version.

**Comment by vasa-develop** [comment]
Update: Added a [commit](https://github.com/filecoin-shipyard/meme-nft-token/commit/1b24ef3164535aa731ef19d09ebf59140a563c21) to the truffle project to fix this issue.

**Comment by brunolm** [comment]
Thank @vasa-develop!

When I tried to change the config file it didn't work, that's odd, maybe I had a typo that I didn't see.
