### ISSUE TITLE
[DOCS ISSUE] Order of pages under "Start buildling" in sidebar menu

### ISSUE THREAD

**Issue by dchoi27** [filecoin-project/filecoin-docs#358]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/build/start-building/interacting-with-the-network/

**What's wrong with this page?**
Under "Start building" in the sidebar menu, "Deploy your application to the Filecoin testnet" is the first option. However, when you click directly on the "Start building" link, it takes you to the second option ("Interacting with the network").

**What would you like to have changed/amended/fixed in order to make things right?**
Either "Start building" should link you to the current first page listed ("Deploy your application to the Filecoin testnet"), or "Interacting with the network" should be listed as the first option. I think based on the flow of the docs the latter is probably right, but not 100% sure.

**Would you be interested in helping fix this page?**
Yes

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by andrew** [comment]
Looks like the whole build section has been rewritten, so this may not be a problem any longer?

**Comment by johnnymatthews** [comment]
Yeahp, this isn't really an issue anymore. Closing.
