### ISSUE TITLE
Network Inspector example doesn't allow uploading files

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#365]
**URL of the page in question:**
https://docs.filecoin.io/build/examples/network-inspector/step-2-run-the-react-app/

**What's wrong with this page?**
When trying to upload a file I can see in the console

```
POST http://localhost:5001/api/v0/add?stream-channels=true&progress=false net::ERR_CONNECTION_REFUSED
```

Following the steps in the examples there is no service running on port 5001.

![image](https://user-images.githubusercontent.com/706078/92163628-63d1d100-ee0a-11ea-8776-8ab3c89a6d14.png)

**What would you like to have changed/amended/fixed in order to make things right?**
The missing app that should be running on 5001.

**Would you be interested in helping fix this page?**
\-

**Comment by vasa-develop** [comment]
@brunolm The missing API endpoint is the `go-ipfs` instance that we start in the sequence 2, 3 of this [Step](https://docs.filecoin.io/build/examples/network-inspector/step-1-start-lotus-devnet-and-go-ipfs/#steps).

Can you confirm that this `go-ipfs` daemon is running (with CORS enabled)?

**Comment by brunolm** [comment]
@vasa-develop I followed the steps from start again and I was able to run `go-ipfs`.

But now I'm getting this error when I try to upload

```
Uncaught (in promise) Error: failed to start deal: computing commP failed: generating CommP: getting ipfs block: blockservice: key not found
```

To run `go-ipfs` I:

1. manually downloaded `go-ipfs_v0.6.0_darwin-amd64.tar.gz`
1. `tar -xvzf go-ipfs_v0.6.0_darwin-amd64.tar.gz`
1. `cd go-ipfs`
1. `ipfs init`
1. Mac warns about app not being from store, I clicked the help button and followed the steps to allow it
1. enabled CORs and started the daemon
```
ipfs init
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["GET", "POST"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Headers '["Authorization"]'
ipfs config --json API.HTTPHeaders.Access-Control-Expose-Headers '["Location"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '["true"]'
ipfs daemon
```

And I had `lotus-devnet` running (`make devnet BIGSECTORS=true`)

**Comment by MajdT51** [comment]
I'm also getting this error when I try to upload

`Uncaught (in promise) Error: failed to start deal: computing commP failed: generating CommP: getting ipfs block: blockservice: key not found`

**Comment by brunolm** [comment]
Maybe a new issue should be created for `block: blockservice: key not found`

This might be related to an issue we observed in another project where the `import`/`export` were generating different CIDs.

We found out that for >=2mb files the importer needs some specific parameters (we were using CID V1)

```
        cidVersion: 1,
        hashAlg: 'blake2b-256',
        rawLeaves: true,
        maxChunkSize: 1048576,  // ipfs default is 262144, which is different from lotus, so we have to force it
        maxChildrenPerNode: 1024, // we also have to force this
```

Adjusting these parameters should fix the `key not found`.

Here's a standalone project where this can be observed, the imported CID doesn't match the exported CID (unless the parameters above are specified)
https://github.com/Digital-MOB-Filecoin/ipfs-cid-checker

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Closing issue.
