### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#38]
Pull the README.md and related background image, etc. from closed PR #26.

Here is the [rendered preview](https://filecoin-docs-duncan.netlify.app/). Links and category names will need to be updated based on latest content structure.

**Comment by terichadbourne** [comment]
Based on Duncan's [comment](https://github.com/filecoin-project/filecoin-docs/pull/26#issuecomment-617567450) when he closed the PR, it's non-trivial to replicate just his landing page design without his full nav changes (which we should discuss with Chris before considering implementing). Would you like to create a markdown file for the landing page for the time being to get this out before Ready Layer One?

**Comment by mishmosh** [comment]
I think the Markdown file will get outdated pretty quickly. Can we autogenerate the links via VuePress?

**Comment by terichadbourne** [comment]
I assume the answer is yes, and that Duncan did it (mixed in with the edits we don't want), but that that's the piece that's going to be more complex and time-consuming to set up. I'd have to dig in further to figure it out, and might need to consult w/ Chris who's in the middle of his project now. We may need to sacrifice either this or the ProtoSchool tutorial if the deadline is the end of next week and it's just my time available to address it.
