### ISSUE TITLE
Instruct users to shutdown the miner only after the binary has been built properly.

### ISSUE THREAD

**Issue by raulk** [filecoin-project/filecoin-docs#384]
The instructions recommend shutting down the miner before even starting to build the new binary. This is inefficient and will cause operational distress if, for whatever reason, the source doesn't build.

Suggested approach:

1. Check out source tree in a new directory.
2. Run `make build` to build without installing to PATH. (Could also run `make install` as replacing the PATH binary shouldn't affect running processes, but just in case...)
3. If all goes well, only then shut down your miner.
4. Run `make install` to copy the new binaries to the PATH.
5. Start the daemons.

**Comment by johndmulhausen** [comment]
@raulk I believe this advice is no longer in there: https://docs.filecoin.io/get-started/lotus/installation/ 
Feel free to reopen if I'm mistaken
