### ISSUE TITLE
How to upgrade a Lotus client.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#392]
**What's the subject of the item you're requesting?**
🔶 [Lotus] Upgrades: a guide on upgrading Lotus (client)

**What's the content of the item you're requesting?**
It should just redirect to re-install and mention a way to remove `~/.lotus`. Should not mention miners, other than to link the relevant guide.

**What will the user know how to do after going through this item?**
How to upgrade Lotus

**Would you be interested in helping create this item?**
yes

**Comment by johnnymatthews** [comment]
Looks like we've already got a page for this. https://docs.filecoin.io/get-started/lotus/upgrades/#installing-an-update
