### ISSUE TITLE
Explain how to manage retrieval deals and prices.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#399]
**What's the subject of the item you're requesting?**
[Lotus] Managing retrieval deals and prices

**What's the content of the item you're requesting?**
[Lotus] Managing retrieval deals and prices

**What will the user know how to do after going through this item?**
[Lotus] Managing retrieval deals and prices

**Would you be interested in helping create this item?**
yes

**Comment by johnnymatthews** [comment]
Closing due to lack of scope.
