### ISSUE TITLE
Add a page explaining what Slate is and how it relies on the Filecoin network.

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#400]
**What's the subject of the item you're requesting?**
Store data with Slate

**What's the content of the item you're requesting?**
A guide to slate usage. Put links or existing docs here about what to do with slate.

**What will the user know how to do after going through this item?**
what to do with slate

**Would you be interested in helping create this item?**
yes

**Comment by johnnymatthews** [comment]
Slate is pretty intuitive already, not sure how valuable a page like this would be. Uploading files is as simple as dragging and dropping, right? Also, this might be better placed on the slate.host site itself. I'm inclined to close this issue, unless I'm missing some nuance of Slate that does require docs @brunolm.

**Comment by brunolm** [comment]
@johnnymatthews this is in the doc, not sure what @hsanjuan has in mind for it.

There's one page mentioning it already https://docs.filecoin.io/build/tools/slate/

**Comment by johnnymatthews** [comment]
Ah I see. A single page explaining what Slate is would be useful, but I wouldn't add anything more than that. I don't think there's any need for a guide or tutorial at this point.

**Comment by hsanjuan** [comment]
I think we'd want a page in the Store section that gives a description of Slate, mentions authors, briefly explains how the photos integrates with Filecoin, links to relevant existing resources (docs etc) and has a screenshot.

Then that page needs to be linked in the places Slate is mentioned.

**Comment by johnnymatthews** [comment]
> Then that page needs to be linked in the places Slate is mentioned.

+1 for cross linking.

**Comment by johnnymatthews** [comment]
Looks like this has been closed. https://docs.filecoin.io/store/slate/#frontmatter-title
