### ISSUE TITLE
Improve the UX of our top level navigation

### ISSUE THREAD

**Issue by cwaring** [filecoin-project/filecoin-docs#403]
Now that the lotus migration is complete we should take a moment to assess and test the UX of our top level items, the desire path from our analytics is still heavily weighted towards installing Filecoin/Lotus and I feel that we may have made this more confusing with the extra top level layers. Let's discuss how we can simplify this menu and consolidate items to make it more intuitive.

![2020-09-15 at 15 46 21](https://user-images.githubusercontent.com/106938/93226048-cf9d2d80-f76a-11ea-9ea5-35e08a34b59c.png)

**Comment by johndmulhausen** [comment]
Closed in favor of #153 which sketches a more concrete vision per the Stripe example given
