### ISSUE TITLE
Add link formatting styleguide

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#405]
**What's the subject of the item you're requesting?**
Add a link formatting styleguide to prevent the need for cleanup PRs like #404 

**What's the content of the item you're requesting?**
Whether to use .md extension, how to refer to parents, etc. 

**What will the user know how to do after going through this item?**
The user will know the correct way to create internal links.

**Would you be interested in helping create this item?**
Sure, if @cwaring can give direction on the correct style.

**Comment by cwaring** [comment]
I would love to figure out if we can build a linter rule to check this automatically.

Essentially we should enforce the following:
- Relative paths **WITH** .md extension for everything in the content body
This ensures the markdown is portable, can be browsed on GitHub and the 404 link-checker works.
- Absolute paths **WITHOUT** .md links for all navigation links
This represents the meta data for that drives the website layout

**Comment by johnnymatthews** [comment]
It's funny how the **Close** button looks like a **Cancel** button in the morning. Sorry about that : |

**Comment by johndmulhausen** [comment]
Closing as irrelevant now that we're using `relref` on Hugo
