### ISSUE TITLE
[DOCS ISSUE] Page: Lotus: switch networks

### ISSUE THREAD

**Issue by momack2** [filecoin-project/filecoin-docs#412]
**URL of the page in question:**
https://docs.filecoin.io/get-started/lotus/switch-networks/#shutdown-running-lotus-daemons

**What's wrong with this page?**
When moving between different hardware setups - you aren't switching **networks** but you are migrating your data / configuration / metadata. Embedding this in a "switch networks" page is hard to find.

**What would you like to have changed/amended/fixed in order to make things right?**
We should have a separate page dedicated to "switching hardware setups on a running network" (not embedded in a "switch networks" page). It should walk through an example of moving a lotus miner successfully from one machine to another - including importing / exporting chain, state, miner data, config, etc. In trying to transition hardware while running on a live network, being able to tell when your upcoming proving windows are is also important so you can time any transitions between machines - so it should include instructions for that too.

**Comment by hsanjuan** [comment]
Hmm "Switch networks" was never about migrating to a different hardware setup on the same network. That is getting addressed in #407 .

I see how the content on this page can lead to confusion though. I am going to limit it to Lotus daemon (it's in the get-started page) and clarify.
