### ISSUE TITLE
Miner wallets management guide

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/filecoin-docs#414]
* Replaces "Using a separate address for windowPoSt messages:" with a guide that covers more aspects of how miners manage their funds.

* Types of miner wallets and what they are used for
* Miner withdraw to worker addresses
* Separate address for windowPoSt
etc.

In @mishmosh words:

> *    what the 3 types of wallets are and what the purpose of each is
> *    what you should check for in a typical mining operation (ie owner/control address will deplete because it's sending messages, so if balance goes negative transfer from worker because that's where FIL is earned, etc.)
> *    what is the purpose of the control address & how to use that for windowpost submissions if it's not the default.

Follow up from #413

**Comment by hsanjuan** [comment]
cc @travisperson, @arajasek, mentioned in the other PR.

**Comment by travisperson** [comment]
The miner actor has 3 basic address owner, worker, control. The control address is actual an array of addresses. I do not know how lotus itself decided to use the multiple address though, I believe it will try to use the control address if set to send WindowPoSt but @aarshkshah1992 or @magik6k would need to probably document their purpose inside of lotus.

The owner address is a more privileged address and is the only addresses allowed to send `ChangeWorkerAddress`, `ConfirmUpdateWorkerKey`, `WithdrawBalance` messages to the miner actor (This are enforced via the `ValidateImmediateCallerIs`; [eg](https://github.com/filecoin-project/specs-actors/blob/d48c45d15f1d79b06bc27c5be326a9b88c1fae39/actors/builtin/miner/miner_actor.go#L171-L187)).

> what you should check for in a typical mining operation (ie owner/control address will deplete because it's sending messages, so if balance goes negative transfer from worker because that's where FIL is earned, etc.)

This line has the owner and worker addresses mixed up.

From the actor level, I do not know of any difference between worker address and control address they appear to have the same privileges.

**Comment by hsanjuan** [comment]
Merged #417
