### ISSUE TITLE
Warn those using systemd scripts to take care about the Environment variables

### ISSUE THREAD

**Issue by j1v** [filecoin-project/filecoin-docs#433]
Please add a note in the section about systemd that if using it, the scripts should be edited if using non standard environment as supposed in other parts of the documents : 
 
For example /etc/systemd/system/lotus-miner.service could have 

```
[Service]
...
Environment=LOTUS_PATH="/mnt/storage/.lotus/"
Environment=LOTUS_MINER_PATH="/mnt/storage/.lotusminer/"

```

**Comment by PatrickDeuse** [comment]
Just for reference from Slack

> [Service]
> ExecStart=/usr/local/bin/lotus-miner run
> Environment=GOLOG_FILE="/var/log/lotus/miner.log"
> Environment=GOLOG_LOG_FMT="json"
> Environment=BELLMAN_CPU_UTILIZATION=0.875
> Environment=FIL_PROOFS_MAXIMIZE_CACHING=1
> Environment=FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
> Environment=FIL_PROOFS_USE_GPU_TREE_BUILDER=1
> Environment=LOTUS_PATH="/mnt/storage/.lotus/"
> Environment=LOTUS_MINER_PATH="/mnt/storage/.lotusminer/"
> Environment=FIL_PROOFS_PARAMETER_CACHE="/mnt/storage/tmp/"
> Environment=FIL_PROOFS_PARENT_CACHE="/mnt/storage/tmp/"

https://filecoinproject.slack.com/archives/CPFTWMY7N/p1600884007037400?thread_ts=1600877944.032300&cid=CPFTWMY7N


Right now the lotus systemd service files are "installed" via `make`. If we hardcode default values into it will be a mess to deploy them.

We should implement `EnvironmentFile=` in the lotus systemd service files and document the deature accordingly.

**Comment by PatrickDeuse** [comment]
another way could eb using overrides as in thsi issue:

https://github.com/filecoin-project/lotus/issues/3358

**Comment by PatrickDeuse** [comment]
for reference:

https://filecoinproject.slack.com/archives/CQLDFHAJY/p1600939006002100

**Comment by hsanjuan** [comment]
Sorry, I had not seen this. I added a checklist of variables that should be defined before starting the miner:

![image](https://user-images.githubusercontent.com/1027022/94431748-fa897780-0195-11eb-9b65-a978d7f37e4f.png)

The logging variables are documented here: https://docs.filecoin.io/get-started/lotus/configuration-and-advanced-usage/#environment-variables

The systemd section has a warning saying the service files are generic and need to be edited.

The seal worker guide also has the list of env variables: https://docs.filecoin.io/mine/lotus/seal-workers/#launching-lotus-workers

Please verify if this addresses the concerns here (and close if so).

**Comment by johnnymatthews** [comment]
@j1v (and @PatrickDeuse), does @hsanjuan's comment above address your issue?

**Comment by PatrickDeuse** [comment]
@johnnymatthews i am fine - we will see over time if people understand that in regard to systemd.

i will come back to systemd when we are in a stable release cycle on mainnet and maybe address it again then ;)

**Comment by hsanjuan** [comment]
By all means. At some point it would be good to have less generic service files.

**Comment by PatrickDeuse** [comment]
the files should be generic as possible. one can just define files from where to load the env vars. in the systemd service files. thats not the problem.

it would be nice if lotus would not need the env vars to be set at all and just take them as arguments or read them from a config file...
