### ISSUE TITLE
[document issue] missing dependencies for ubuntu 18.04

### ISSUE THREAD

**Issue by bobjiang** [filecoin-project/filecoin-docs#440]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/get-started/lotus/installation/#software-dependencies

**What's wrong with this page?**
For ubuntu 18.04, it is missing for `clang` dependency installation.

**What would you like to have changed/amended/fixed in order to make things right?**
add `clang` in `sudo apt install` section.

**Would you be interested in helping fix this page?**
yes, but only for ubuntu section, not sure for other OS.

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
Thanks for bringing this up @bobjiang. I see that you've made a PR. I'll leave further comments in there :)
