### ISSUE TITLE
Sidebar bugs

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/filecoin-docs#46]
- [x] Fix bug preventing sidebar from collapsing when you return to homepage
- [x] Fix bug preventing sidebar from opening the section you've clicked to when you visit a section landing page from the headers of the boxes on the landing page

**Comment by terichadbourne** [comment]
@mishmosh I believe you found a third sidebar bug when exploring the other day. Do you recall what it was?

**Comment by mishmosh** [comment]
it was this, already fixed! https://github.com/filecoin-project/filecoin-docs/pull/54

**Comment by pooja** [comment]
Has this issue been addressed? cc @cwaring

**Comment by johnnymatthews** [comment]
Both these points looks fixed to me, so I'm gonna close this. Feel free to re-open if I'm completely wrong (highly likely).
