### ISSUE TITLE
Update all documentation for mainnet launch!

### ISSUE THREAD

**Issue by momack2** [filecoin-project/filecoin-docs#486]
Update all documentation for mainnet launch! Make sure it's clear:
- what phase of launch we're in (audit for "pre-launch", "not live", "mainnet", etc)
- how to join the **mainnet** as a miner / client
- the presence of various testnets like calibration net and how to join / use them (will continue having faucets)
- where to look for network status / report issues  (filecoin.statuspage.io,  security@)
Etc!

**Comment by jennijuju** [comment]
[ ] Ledger support
[ ] Miner backup
[ ] Owner address update
[ ] daemon backup

**Comment by hsanjuan** [comment]
Related #484

**Comment by jennijuju** [comment]
Note:  new miner will be able to win a block unless their miners have been created more than 900 epoch and has 10 TiB power

**Comment by hsanjuan** [comment]
Ledger support is still very experimental afaik. Will ledger have an official guide on that? We cannot recommend using something like that if it's not considered production-ready, particularly for real money.

I am not sure what Miner backup is (backup without the sectors?). Daemon backup also problematic. Can everything except blocks be backed up and then intialize from snapshot and expect everything to work as before? Or does it mean a backup with the chain? A lotus developer should write these, there are too many internals involved and publishing the wrong info might have really bad consequences.

**Comment by hsanjuan** [comment]
Since backups are the thing missing, I'll close this in favour of #521
