### ISSUE TITLE
[DOCS ISSUE] Page: The Filecoin Space Race

### ISSUE THREAD

**Issue by corviato1** [filecoin-project/filecoin-docs#487]
**URL of the page in question:**
_e.g. https://docs.filecoin.io/introduction/usage/_

**What would you like to have changed/amended/fixed in order to make things right?**

Is there any way you can amend the rules for miners who earned 100 FIL or less in SR, who want to use the FIL to get to 10TiB, the ability to get paid in full upfront?   :pray: It won't hurt anyone and I'll sign whatever contract saying that I wont dump that 100 FIL on the market and will use it for pledging and post fee.

Please don't make me(and other miners in the bottom 10%) buy 86.4 FIL after months of endless hard work and many thousands of dollars of hardware.

**Comment by hsanjuan** [comment]
This is not a docs issue. Can't help with this.
