### ISSUE TITLE
Update analytics 

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/filecoin-docs#5]
Replace Google Analytics ID [here](https://github.com/filecoin-project/filecoin-docs/blob/master/docs/.vuepress/config.js#L352) so we don't send our stats to the IPFS analytics site.

**Comment by terichadbourne** [comment]
Have set up a new Google Analytics property "New Filecoin Docs" under the account "Filecoin Docs" and swapped out the ID accordingly but haven't done any testing. GA dashboard for those with access: https://analytics.google.com/analytics/web/?authuser=2#/report-home/a148766289w225687004p213676221

We may also want to switch to Countly for better user privacy - TBD.

**Comment by terichadbourne** [comment]
Google Analytics site moved to Filecoin ownership and now located at https://analytics.google.com/analytics/web/?authuser=2#/report-home/a148766289w225687004p213676221

**Comment by mishmosh** [comment]
@terichadbourne would you consider this done?

**Comment by terichadbourne** [comment]
@mishmosh We're currently collecting data in Google Analytics but haven't taken the time to build custom reports. (If we stay here, we could investigate how the IPFS Docs team set theirs up.) We could also consider switching to Countly for privacy reasons; the IPFS Docs team didn't do this because it's harder to customize reporting.

**Comment by cwaring** [comment]
related #118

**Comment by cwaring** [comment]
Considering this complete for now. We can revisit this conversation at a later date.
