### ISSUE TITLE
Documentation doesn't say that I need to install jq beforehand, but I can't `make deps` until I do

### ISSUE THREAD

**Issue by ADeeds** [filecoin-project/filecoin-docs#501]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://go.filecoin.io/go-filecoin-tutorial/Getting-Started.html

**What's wrong with this page?**
TBH I'm not sure if this is a documentation problem or a build problem.
When I get to the "make deps" step on the page, the output looks like this:

```
> make deps
go run ./build/*.go smartdeps
pkg-config --version
1.7.3
Installing dependencies...
go mod download
Getting parameters...
./scripts/install-filecoin-ffi.sh
+ auth_header=()
+ '[' -n '' ']'
++ dirname ./install-filcrypto
+ cd .
+ rust_sources_dir=rust
++ jq -r '.[].rustc_target_feature'
./install-filcrypto: line 23: jq: command not found
+ optimized_release_rustc_target_features=
Command './scripts/install-filecoin-ffi.sh' failed: exit status 127
exit status 1
make: *** [Makefile:5: deps] Error 1
```
After I manually install jq, the process works as expected

**What would you like to have changed/amended/fixed in order to make things right?**
In the Installing Dependencies section, it would help if there was a line about how jq is necessary. It might make sense to put that either right before or after the section about Go 1.13

**Would you be interested in helping fix this page?**
If necessary

**Is there any other feedback you'd like to share about Filecoin docs?**
Nah

**Comment by johnnymatthews** [comment]
Thanks for bringing this up, but this repo does not manage content for [Go Filecoin](https://go.filecoin.io/go-filecoin-tutorial/Home.html). The repo handles docs for the Filecoin protocol, and the Lotus implementation. All other Filecoin implementations, like _Go Filecoin_ have their own repos. It's a bit confusing, I know. We're working on clarifying _which_ docs live _where_.

 Please raise this issue over at https://github.com/filecoin-project/docs.
