### ISSUE TITLE
[DOCS ISSUE] Page: Run a Filecoin local devnet

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/filecoin-docs#509]
**URL of the page in question:**
https://docs.filecoin.io/build/local-devnet/#textile-s-lotus-devnet

**What's wrong with this page?**
The walk through assumes that the user has directory `~/.lotus/keystore`.  I didn't on my machine and got error: `failed to build crypto.PrivKey: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): writing key 'libp2p-host': open /Users/zenground0/.lotus/keystore/NRUWE4BSOAWWQ33TOQ: no such file or directory`

**What would you like to have changed/amended/fixed in order to make things right?**
Whatever setup step is typically run to create this directory should be included earlier in the walkthrough.  If lotus supposed to create the directory off of the provided daemon command than a bug should be filed in lotus.

**Comment by hsanjuan** [comment]
On which step did this happen? the wallet import ?

**Comment by ZenGround0** [comment]
I failed starting the daemon. Going back through to reproduce the issue was that I was improperly skipping `export LOTUS_PATH=~/.lotusDevnet`.  Otherwise I could never have gotten to this state.
