### ISSUE TITLE
Confusing lotus hardware requirements section

### ISSUE THREAD

**Issue by daviddahl** [filecoin-project/filecoin-docs#511]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://github.com/filecoin-project/filecoin-docs/blob/master/docs/get-started/lotus/installation.md

**What's wrong with this page?**
The hardware requirements are a little bit confusing relating to required hardware. 

**What would you like to have changed/amended/fixed in order to make things right?**
If one has a 4-core cpu (with SHA extensions - and does that even exist?) Is that good enough?
Or can one use an 8-core cpu otherwise, but with 32GB of RAM? Perhaps the RAM requirement can be on its own bullet point?

FWIW, I am just running a lotus node on a 4-Core CPU with 24GB of RAM (soon to be 32) in order to get familiar with lotus and related cli programs. I am not attempting any mining or other more intensive activities, just syncing the chain, etc.

**Would you be interested in helping fix this page?**
Yes, happy to fix this with guidance.

**Is there any other feedback you'd like to share about Filecoin docs?**
Love the docs and spec so far. Exciting times.

**Comment by hsanjuan** [comment]
Sorry, this was a typo. Minimal requirements were recently updated from 4-core/8 GiB RAM to 8-core/32 GiB RAM (@pooja ). 

For me it works well with 4-cpu/16 GiB RAM.

Fix #512
