### ISSUE TITLE
[CONTENT REQUEST] Do I need FileCoin to Store Data?  Where do I get Some?

### ISSUE THREAD

**Issue by scottbourne** [filecoin-project/filecoin-docs#515]
Is there an item missing from Filecoin documentation that would be helpful to you? Please use this template to let us know!

**What's the subject of the item you're requesting?**
Do I need FileCoin to Store Data?  Where do I get Some?

**What's the content of the item you're requesting?**
As an end user in the general public, do I need FileCoin to store my data?  How do I get FileCoin?

**What will the user know how to do after going through this item?**
I would know if I need FileCoin to store my data and I would understand what I need ino order to buy and securely store my FileCoin.  I might even know how to earn FileCoin!

**Would you be interested in helping create this item?**
This item might already exist, I just could not find it.  I do not know the answers, hence my questions.  I'd be happy to review any proposed replies!

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by hsanjuan** [comment]
Hello,

please read the relevant docs about how filecoin works.

https://docs.filecoin.io/about-filecoin/how-filecoin-works/#deals

and the relevant docs about storing data:

https://docs.filecoin.io/store/

FIL can be obtained on exchanges. For the moment we've chosen to not document the list, but it can be googled.

**Comment by scottbourne** [comment]
Thanks for these, but neither helps a novice end-user understand that they
have to pay for storage with FileCoin and that they have to buy them from
some other place first.

Maybe the general public isn't the target market and it is not necessary.

Appreciate the quick response!

**Comment by hsanjuan** [comment]
From the docs linked above:

> Nodes can propose storage and retrieval deals to Filecoin miners and pay for them as they are executed.

> For mainnet, the easiest is to buy FIL from an exchange supporting FIL trading.

If you have concrete improvements, please send them. But first please read and absorb all the existing information.
