### ISSUE TITLE
Update Miner Lifecycle doc to include details on proving deadlines.

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/filecoin-docs#517]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/mine/lotus/miner-lifecycle/#ensuring-proofs-for-the-current-deadline-have-been-sent

**What's wrong with this page?**

It is not clear enough. It does not explain how to read `proving deadlines` and how to identify the right time to restart the miner if all the deadlines have sectors in them.

Users report that they have never seen all deadline times to be in the future.

**Comment by johndmulhausen** [comment]
Closing as done; we looked and we do advise on restarts / deadlines. Let us know if you disagree.
