### ISSUE TITLE
Clarify some nuances surrounding wallet information.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#518]
Can we clarify some nuances about wallets/addresses?
- Per node, you can only have one wallet. But one wallet can have multiple addresses. Can we change [this section](https://docs.filecoin.io/get-started/lotus/send-and-receive-fil/#listing-wallets) to be about "listing addresses" rather than wallets.
- Can we also change [this section](https://docs.filecoin.io/get-started/lotus/send-and-receive-fil/#creating-a-wallet) to be about "creating an address" rather than creating a wallet?

**Comment by hsanjuan** [comment]
@johnnymatthews can you take care of this one?

@pooja is right, this has been badly written and address != wallet in lotus terminology.

**Comment by johnnymatthews** [comment]
Sorry, saw this one and then completely forgot about it. On it now.
