### ISSUE TITLE
Explain how to create a backup and restore important metadata/datastores.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#521]
There are many ways in which users today can lose important data from their lotus nodes:
- If a node crashes and corrupts some metadata
- If a node is borked for some unrelated reason, and a user removes .lotus/datastore
- etc

The lotus node provides a `lotus backup` command from the CLI, and will soon be adding functionality to restore from a backup. Can we add docs to exlain to users how to create these backups (they are not created automatically) and how to restore?

**Comment by johnnymatthews** [comment]
Just a note to myself: this is different to `lotus-miner backup`.

**Comment by johnnymatthews** [comment]
Relevant PR here https://github.com/filecoin-project/lotus/pull/5362
