### ISSUE TITLE
Explain what multi-signatures are and how to use them.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/filecoin-docs#523]
Why suggested miners to use multisig as the owner address, however, miners dont know how.

`lotus msig`

**Comment by johnnymatthews** [comment]
What's going on with this issue @jennijuju? Can you expand more on what needs to be written?

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/filecoin-docs/pull/539

**Comment by johnnymatthews** [comment]
Looks like we've merged this one in already. Closing.
