### ISSUE TITLE
Fix current 404s

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#534]
Lots of reports that this link 404s: https://docs.filecoin.io/build/onboard-testnet/

But we also have others (looks like 126 more?):
![Screen Shot 2020-10-29 at 3 59 39 PM](https://user-images.githubusercontent.com/5668171/97641302-ceb11a00-19ff-11eb-9df1-d4870e8f9fb5.png)

:) Could we do a sweep and fix these pls? 🙏

**Comment by cwaring** [comment]
I'll double check asap and new redirects if required 👍
