### ISSUE TITLE
Add `http` to the end of a MINER_API_INFO variable, and fix typo.

### ISSUE THREAD

**Issue by marsoln** [filecoin-project/filecoin-docs#542]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/mine/lotus/seal-workers/#configuring-the-miner-sealing-capabilities

**What's wrong with this page?**
![image](https://user-images.githubusercontent.com/7898688/97981676-a06f7800-1e0d-11eb-8781-5a4a7f4f7c75.png)

**What would you like to have changed/amended/fixed in order to make things right?**
I thought this might be `export MINER_API_INFO=<TOKEN>:/ip4/<miner_api_address>/tcp/<port>/http`

**Comment by marsoln** [comment]
![1604404153487](https://user-images.githubusercontent.com/7898688/97981969-08be5980-1e0e-11eb-9805-bc2970ddcfa5.jpg)

**Comment by johnnymatthews** [comment]
Yeahp, you're right. We're missing the `/http` at the end. Also, it looks like there's a typo in _Environmet variables_. Thanks for bringing this up.
