### ISSUE TITLE
[DOCS ISSUE] Page: Lotus Miner: setup a high performance miner

### ISSUE THREAD

**Issue by Leozhang404** [filecoin-project/filecoin-docs#562]
In the "Miner initialization" part, there is an error

**URL of the page in question:**
_https://docs.filecoin.io/mine/lotus/miner-setup/#miner-initialization_

**What's wrong with this page?**
Initialize a new miner command:
error: 
  - 'lotus-miner init --owner=<bls address>  --worker=<other_address> --no-local-storage'
![image](https://user-images.githubusercontent.com/38653654/98209558-1b55a180-1f7a-11eb-8094-169251a0bd8e.png)

**What would you like to have changed/amended/fixed in order to make things right?**
_The right command should be: lotus-miner init --owner=<other address>  --worker=<bls_address> --no-local-storage._

As @magik6k said, worker address must be bls Address(f3...), and owner address can be bls address and other address(f1..., f3...)
**Would you be interested in helping fix this page?**
yes

**Is there any other feedback you'd like to share about Filecoin docs?**
yes，there are other bugs I will fix them

**Comment by johnnymatthews** [comment]
Thanks for your suggestion @Leozhang404! However, `lotus-miner init --owner= --worker=<bls_address> --no-local-storage` looks incorrect since `--owner=` has been left blank. I don't have a miner set up right now, but I can spin one up. Can you double check that your suggestion is correct? Thanks!

**Comment by Leozhang404** [comment]
sorry, I see it is still as my paste, '--owner ' is not blank
![image](https://user-images.githubusercontent.com/38653654/98642855-13767280-2369-11eb-84ef-40f2365dd6f3.png)
@johnnymatthews
