### ISSUE TITLE
Calibration net block explorers

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/filecoin-docs#568]
Idk if [this page](https://github.com/filecoin-project/filecoin-docs/blob/42263d153a6cc9930f3e9ebdfa0e08a408988b59/docs/build/start-building/interacting-with-the-network.md#calibration-devnet) is displayed anywhere, but the block explorers listed under calibration devnets aren't alive anymore.

**Comment by johnnymatthews** [comment]
Can't find that information anywhere anymore. Also, can't find either `https://calibration.filfox.io/` or `https://calibration.filscan.io/`. So I'm guessing it got ripped out.
