### ISSUE TITLE
Explain how to back up a daemon and a miner.

### ISSUE THREAD

**Issue by momack2** [filecoin-project/filecoin-docs#570]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/mine/lotus/miner-upgrades/#upgrade-with-reset

**What's wrong with this page?**
Doesn't explain how to back up my daemon/miner.

**What would you like to have changed/amended/fixed in order to make things right?**
Explain the exact steps, frequency, etc to back up my daemon / miner / etc. 

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
Closed in #583
