### ISSUE TITLE
Fix links in /get-started/lotus/installation/.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#577]
A lot of the hash `#` links are borked in [get-started/lotus/installation/](https://docs.filecoin.io/get-started/lotus/installation/). This is likely a left-over step from a past migration. The links aren't explicitly broken, they just reload the page.

I'm planning to get to this today, but someone else can jump on it if this issue is still open on Friday afternoon.

## Tasks

- [x] Find all hash `#` links.
- [x] If they don't address anything on that page, re-link them to the proper page.

**Comment by cwaring** [comment]
Internal hash links should be caught by the 404 checks if they are setup
correctly using relative paths. So this might be another issues that
needs to be resolved. Would be good to double check.

**Comment by johnnymatthews** [comment]
Ha, so turns out everything is fine with the docs. No idea what was going on when I made this issue. Could've been an issue with the Firefox Nightly version I was running? Anyway, this is a non-issue.
