### ISSUE TITLE
Clarify what gets stored on the Filecoin blockchain, along with how data is stored by miners.

### ISSUE THREAD

**Issue by muzicturb** [filecoin-project/filecoin-docs#586]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/about-filecoin/how-filecoin-works/

**What's wrong with this page?**
I believe that there is some information that can be added to this page to increase the understanding of newcomers. Mainly, what is being stored on the blockchain is not being made clear. Are the cryptographic proofs being stored, or something else? Some may interpret that miners are storing user data on the blockchain, which would result in major privacy and scalability concerns. It would be good to explicitly clarify this aspect of the network. In addition, I suggest adding a section on how the privacy of the client's files is ensured.

**What would you like to have changed/amended/fixed in order to make things right?**
Adding a section that explains **what** is being stored on the Filecoin blockchain and **how** the files are being kept private from miners when they store them.

**Would you be interested in helping fix this page?**
I don't know enough about Filecoin to confidently edit this, sorry.

**Is there any other feedback you'd like to share about Filecoin docs?**
None

**Comment by johnnymatthews** [comment]
Thanks for the issue @muzicturb. I've updated the title to better describe what we need to fix here.
