### ISSUE TITLE
Explain issues with the Great Firewall.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#603]
Filecoin is currently facing some issues with the Great Firewall of China, namely transfers slow to a crawl when sending/receiving anything more than a few MB in or out of China. Because of this, storage users will likely see better connections and transfers by using a miner within their own region. The issue will likely get fixed at some point, but for now we should point this out to storage users.

**Comment by PatrickDeuse** [comment]
this is only true for online deals and data transfers

terrabytes of data rsync/scp fine through the firewall

**Comment by johnnymatthews** [comment]
@ribasushi do you happen to know if this is still an issue, or did the Lotus engineers perform some magic and fix it?

**Comment by f8-ptrk** [comment]
this will always be an issue i think. traffic crossing the gwf is always slow. 

my 15th of january might be not correct and we are just lucky to have a direct connection to a china telecom fiber in germany.
