### ISSUE TITLE
Define the minimum required funds for Lotus miner addresses.

### ISSUE THREAD

**Issue by Shekelme** [filecoin-project/filecoin-docs#610]
**URL of the page in question:**
[https://docs.filecoin.io/mine/lotus/miner-setup/#creating-wallets-for-the-miner](https://docs.filecoin.io/mine/lotus/miner-setup/#creating-wallets-for-the-miner)

**What's wrong with this page?**
It says "Next make sure to send some funds to the worker address so that the miner setup can be completed", but actually you can't proceed while there is 0 FIL on your owner address.

**What would you like to have changed/amended/fixed in order to make things right?**
Please mention that owner address should have some funds too. And the minimal sufficient amount to init the miner.

**Would you be interested in helping fix this page?**
Probably, but how?

**Is there any other feedback you'd like to share about Filecoin docs?**
You know, it is generally difficult for a beginner to navigate the documentation...

**Comment by johnnymatthews** [comment]
Thanks for bringing this up @Shekelme.

> You know, it is generally difficult for a beginner to navigate the documentation...

Could you elaborate? We could use your input to create more actionable issues.

**Comment by johndmulhausen** [comment]
This page has been migrated to the Lotus repo, closing here and resolving in https://github.com/filecoin-project/lotus-docs/pull/37
