### ISSUE TITLE
[Docs] I18n for Korean Documentation

### ISSUE THREAD

**Issue by kkdg** [filecoin-project/filecoin-docs#625]
I'd like to initiate I18n for Korean documentation since there is a lot of fuss going about Filecoin in Korea quite recently. 
I think many of Korean people having substantial difficulty to get along with what's going on in Filecoin universe for they are not ready to digest contents one by one written in English. 

Could any one from core team tell me how to start I18n for other languages in Filecoin docs sector?

Thanks!

**Comment by johnnymatthews** [comment]
While it's very kind of you to translate these docs, manual translation is not a viable option right now. The amount of updates coming into this repo on a daily basis is far to much for any one to keep up with, translation wise. Right now, we're relying on users to source their own translation tools.

**Comment by kkdg** [comment]
Noted.

**Comment by benjioh5** [comment]
@kkdg Still in interest?
