### ISSUE TITLE
Update instructions for switching networks using Lotus.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#638]
Switching between `mainnet` and `calibnet` no longer requires switching branches. Instead, build with `make calbinet` if you want to connect to `calibnet`. Continue to use just `make` to connect to `mainnet`.

## Tasks

- [x] Update instructions in [/get-started/lotus/switch-networks/](https://docs.filecoin.io/get-started/lotus/switch-networks/#frontmatter-title)
- ~~[ ] Update instructions on [network.filecoin.io](https://network.filecoin.io/#calibration)~~

**Comment by johnnymatthews** [comment]
@arajasek does this mean that the two methods we currently have to switch network are now redundant? https://docs.filecoin.io/get-started/lotus/switch-networks/#approach-1-clean-re-build-and-re-install

**Comment by arajasek** [comment]
No, we still just use the $LOTUS_PATH as the directory, so you would still trod on your own toes if you switched without taking either of those 2 steps (either nuking the old directory, or setting a new $LOTUS_PATH).

**Comment by arajasek** [comment]
(we should change that behaviour, though)

**Comment by PatrickDeuse** [comment]
if you change that behavior please make sure to scream at everyone running a lotus - like for a week before changing it!
