### ISSUE TITLE
Add examples to CAR section

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/filecoin-docs#64]
Address the outstanding TODO in https://docs.filecoin.io/how-to/store-large-files/#recommended-file-format-car by adding examples. 

[TODO: Example of real data indexed and pointers to the subset that can grab that specific data, to help ppl think about splitting data up better for their use cases and specific file formats.]

**Comment by mishmosh** [comment]
I believe @mikeal and @ianjdarrow are working on this.

**Comment by johnnymatthews** [comment]
The [link goes to a 404 page]. Did this get fixed and can we close this issue @mishmosh?

**Comment by mishmosh** [comment]
The link was broken in one of the recent navigation refactors. The URL is now https://docs.filecoin.io/how-to/store/large-files/.

Still an open issue.
