### ISSUE TITLE
[DOCS ISSUE] Page: Lotus Miner - very minor typo

### ISSUE THREAD

**Issue by gregsskyles** [filecoin-project/filecoin-docs#643]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
_https://docs.filecoin.io/mine/lotus/_

**What's wrong with this page?**
_Grammatically, the word 'application' referring to more than one (three in this case) should be plural._

**What would you like to have changed/amended/fixed in order to make things right?**
_This sentence: "Once installation is completed all three application (node, miner and worker) should be installed." should read "Once installation is completed all three application**s** (node, miner and worker) should be installed."_

**Would you be interested in helping fix this page?**
_Sorry to be too lazy to fork your repo and submit a PR; if I were more Git(hub) literate, I might have a go. It seems like it would be easier for someone with the appropriate privileges to add the single character._

**Is there any other feedback you'd like to share about Filecoin docs?**
_What I've read so far seems well written, easy to understand and clearly laid out._

**Comment by johnnymatthews** [comment]
Thanks for raising the issue @gregsskyles!
