### ISSUE TITLE
Revist the "Powergate Pinning Service App" example.

### ISSUE THREAD

**Issue by tsiotas** [filecoin-project/filecoin-docs#645]
https://docs.filecoin.io/build/examples/simple-pinning-service/step-4-explore-pinning-service-app/#step-4f-fetch-data-back-from-ipfs-and-ffs-via-powergate-instance

The pinning service app apparently works only with powergate docker version  < 1.0.0 but only the Network page 
if I try to use the first version v.0.0.1-beta10 it doesn't work anyway because a dns error occours:
"resolving dns: lookup lotus on 127.0.0.11:53: no such host localnet_powergate_1 exited with code 1" OR SIGINT e"
I tried to build the lotus image by myself, too and tried on different OS (Ubuntu and CentOS) 
The Profile page retrieves always messages like "Uncaught (in promise) Error: auth token not found" or the Pin page "Cannot read property 'defaultConfig' of undefined"
So for me not possible testing Powergate Pinning Service, probably because problems related to different version releases and compatibility with the original service (but also the docker version 0.0.1 doesn't work anymore)... so no way to fix these problems?
Thanks

**Comment by johnnymatthews** [comment]
Thanks for bringing this up @tsiotas. It sounds like we need to revisit this example.

**Comment by tsiotas** [comment]
If it can be useful to someone, in the end we made a simple working project in typescript to test filecoin pinning and to retrieve other information in node.js using powergate-client and powergate docker v.2.0.0 in localnet, available at this repository:
 
 https://github.com/tsiotas/powergate-node.js
 
 It's a very raw code only to test and understand the functionalities of filecoin architecture

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Closing issue.
