### ISSUE TITLE
Fix inconsistent use of title case

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/filecoin-docs#65]
Between sidebar nav, page titles, and headers in markdown files, we're using title case in some places and not others. Need to make a decision about which way we'd like to go and stick with it. @mishmosh is there already a chosen path for other docs sites or written comms?

**Comment by mishmosh** [comment]
The styleguide has an opinion for us: sentence case.
https://docs.filecoin.io/community/contribute/grammar-formatting-and-style/#grammar-and-spelling
