### ISSUE TITLE
remove --gas-limit from the c+p -able command line

### ISSUE THREAD

**Issue by PatrickDeuse** [filecoin-project/filecoin-docs#657]
https://docs.filecoin.io/mine/lotus/message-pool/#replacing-messages-in-the-pool

the command example at the bottom includes the optional `--gas-limit` - it is an optional parameter, as mentioned right above the command line.

setting/changing the `--gas-limit` to something else than the original value is dangerous (costly possibly!). there is basically no reason to ever do it under normal circumstances.

people tend to just copy paste stuff! there is even a button in the bottom right of the command line to do exactly that. i have seen the copy pasted cmd line at least once in the wild...

removing the `--gas-limit` from the command line will not hurt - people who need to set it by hand are way beyond the point of having to consult the documentation.

**Comment by PatrickDeuse** [comment]
if someone responsible for this here thinks that is a reasonable change i will PR it

**Comment by johnnymatthews** [comment]
> people who need to set it by hand are way beyond the point of having to consult the documentation.

I agree. This is a useful suggestion. If you have the time @PatrickDeuse we'd really appreciate a PR. I'm gonna assign you to this issue. Feel free to un-assign yourself if you're busy.
