### ISSUE TITLE
Fill in TODO in Sample Architectures page

### ISSUE THREAD

**Issue by miyazono** [filecoin-project/filecoin-docs#67]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/how-to/build-sample-architectures/

**What's wrong with this page?**
Seems like there's an outstanding ToDo of filling in the examples.

**What would you like to have changed/amended/fixed in order to make things right?**
The examples look like placeholders.  I don't think it's urgent, but I wanted to make sure there was an open issue linking the ToDo.

**Would you be interested in helping fix this page?**
I don't have enough context to fill them in myself, but I figured I could at least flag for someone else.

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by mishmosh** [comment]
Thanks for getting this into our issue queue @miyazono!

**Comment by johnnymatthews** [comment]
Looks like the [link no longer goes anywhere](https://docs.filecoin.io/how-to/build-sample-architectures/). Can we close this issue @mishmosh?
