### ISSUE TITLE
Explain how to extend storage volumes.

### ISSUE THREAD

**Issue by jancco** [filecoin-project/filecoin-docs#69]
**Requested page: How to extend storage volumes?**
As we known, very limited volumes can be mounted to one server, but we hope a storage node can govern a large amount of storage volumes. So we need some contents to guide us to achieve that.

**What's the content of the item I'm requesting?**
I propose to contain the following contents in the page:
1. How to implement the extendable storage? ---- configurable multiple storage sources or SAN or NAS or ...?
2. How to deploy the nodes? ---- only one full node is enough or we need more nodes including worker nodes.
3. How to config the nodes? ---- in which config file(s) or environment variable(s) to config? what's the format of config variable(s).

**Comment by eshon** [comment]
Hi @jancco,

Some of these questions are answered in node-specific docs like https://lotu.sh/ because they are node-specific configuration parameters.

For example `.lotus/config.toml` file has many of these options for extending storage volume as does https://lotu.sh/en+lotus-seal-worker#running-over-the-network-11788 for running over a network.

Do these resources answer your questions or are you requesting more general docs?

**Comment by jancco** [comment]
Hi @eshon ,

Thanks for your detailed answer! Maybe I didn't describe my question clearly in the initial post and my exact purpose is to extend storage volumes but not computing ability.

If I didn't misunderstand, this article ([https://lotu.sh/en+lotus-seal-worker#running-over-the-network-11788](https://lotu.sh/en+lotus-seal-worker#running-over-the-network-11788)) introduces the method to extend computing ability for sealing but not storage volumes. (In fact, I ever deployed a separate worker node, but it would not seal its local [in worker node] storage but the storage in miner node.)

Thanks for your answering again!

**Comment by eshon** [comment]
To extend storage volumes:

<img width="508" alt="Screen Shot 2020-05-15 at 7 42 59 PM" src="https://user-images.githubusercontent.com/1017762/82080181-5f12d100-96e4-11ea-9382-7d9d360c0107.png">

**Comment by jancco** [comment]
Hi @eshon ,

Thanks a lot for your information! It's really helpful for me!

@mishmosh , if possible, I still hope a page concerning this content was added, it would be helpful for more people. Thanks!

**Comment by johnnymatthews** [comment]
This looks like it's answered here: https://docs.filecoin.io/mine/lotus/custom-storage-layout/#custom-location-for-sealing

Feel free to re-open if there's still a problem here.
