### ISSUE TITLE
Remove the "Calculate the datasize" section.

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/filecoin-docs#705]
This is bugging me but I don't have better words to suggest for replacement at the moment because it's really hard to explain this clearly and accurately so I'm flagging it to be addressed in the future (or someone with better words than me).

In this: https://github.com/filecoin-project/filecoin-docs/blob/master/docs/store/lotus/very-large-files.md#calculate-the-datasize

We have this:

```
### Calculate the datasize

1. Take the final car size `ls -l data.car`
1. Round it up to the nearest power of 2. This is your padded piece size.
1. Divide by 128, multiply by 127. this is your unpadded piece size.
1. Go to [Wolfram Alpha](https://www.wolframalpha.com).
1. Enter `x = SIZE_IN_BYTES; 127*( 2^( ceil( log2( ceil ( x /127 ) ) ) ) )` and changing `SIZE_IN_BYTES` to your value.
1. You solution can be found under **Substitution**:
```

The Wolfram script is fine, if obscure, but the second and third instructions are not quite correct. They won't work as you edge up close to a power-of-two for your original data source.

e.g. if you have a file size of `4194300` bytes, the next power-of-two is `4194304`. Doing a "Divide by 128, multiply by 127" gives you `4161532`. which is `32768` bytes _less_ than the original input size.

This is because Fr32 padding (2 bits per 254 bits, i.e. 1 per 127) is done _before_ fitting it into a power-of-two. So you need to account for the extra 1 / 127 before going up to the power-of-two. But then you need to come back down again to remove the Fr32 padding to get this "datasize" value. This "datasize" would roughly be defined as "the smallest size needed to make space for 2 bits per 254 bits and fit within a power-of-two.".

The algorithm goes something like this:

1. Find the next power-of-two
2. Is there enough room between actual and power-of-two to fit in 2-per-254 bits? If no, bump up to the _next_ power-of-two.
3. Divide by 256 and multiply by 254.

(You can even find something similar to this in Lotus, because it doesn't get `log2` involved.)

We iterated a bit on language for the specs @ https://spec.filecoin.io/#section-systems.filecoin_files.piece.data-representation and Yiannis did a nice job of explaining step 3 there. But it gets awkward here because we need to care about this "datasize" thing which is a step backward.

**Comment by rvagg** [comment]
OK, here's a proposal for how we might do it:

1. Add bit-padding, adding 2 bits per every 254 bits (i.e. multiply by `256/254`)
2. Round up to the next power-of-two above the bit-padded padded size
3. Remove bit-padding from the power-of-two size (i.e. divide by `256/254`)

With a link to https://spec.filecoin.io/#section-systems.filecoin_files.piece.data-representation for further information.

Still confusing, but such is the nature of this particular double-padding process.

**Comment by rvagg** [comment]
Also might be worth putting a note that the "ideal" size of deal data size for a client is as close as possible, but not over `254/256`ths of a power-of-two size to avoid as much power-of-two zero-padding as possible. A table could even show these numbers:

| B | KiB | MiB |
| -- | -- | -- |
| 1,016 B | | |
| 2,032 B | | |
| 4,064 B | | |
| 8,128 B | | |
| 16,256 B | | |
| 32,512 B | | |
| 65,024 B | | |
| 130,048 B | 127 KiB | |
| 260,096 B | 254 KiB | |
| 520,192 B | 508 KiB | |
| 1,040,384 B | 1,016 KiB | |
| 2,080,768 B | 2,032 KiB | |
| 4,161,536 B | 4,064 KiB | |
| 8,323,072 B | 8,128 KiB | |
| 16,646,144 B | 16,256 KiB | |
| 33,292,288 B | 32,512 KiB | |
| 66,584,576 B | 65,024 KiB | |
| 133,169,152 B | 130,048 KiB | 127 MiB |
| 266,338,304 B | 260,096 KiB | 254 MiB |
| 532,676,608 B | 520,192 KiB | 508 MiB |
| 1,065,353,216 B | 1,040,384 KiB | 1,016 MiB |
| 2,130,706,432 B | 2,080,768 KiB | 2,032 MiB |
| 4,261,412,864 B | 4,161,536 KiB | 4,064 MiB |
| 8,522,825,728 B | 8,323,072 KiB | 8,128 MiB |
| 17,045,651,456 B | 16,646,144 KiB | 16,256 MiB |

(maybe TMI and  could be trimmed)

Comes from JS:

```js
for (let i = 10; i < 35; i++) { let b = (254/256) * (2**i); console.log(`| ${b.toLocaleString()} B | ${Math.floor(b / 1024).toLocaleString()} KiB | ${Math.floor(b / 1024 / 1024).toLocaleString()} MiB |`) }
```

For a miner it's apparently the opposite of this because they save on data transfer costs while getting the full power-of-two price! But we probably don't want to highlight that! (/cc @ribasushi)

**Comment by ribasushi** [comment]
Honestly I think the above is both:
- TMI
- Something lotus should be doing for the client in the first place, at least in interactive mode...

Wonder if the latter can be retrofitted somehow without breaking the API too much
Thoughts @whyrusleeping @magik6k ?

**Comment by jsign** [comment]
Very interesting! 

I think the Wolfram Alpha formula mentioned in the original post (taken from the docs) also has some extra thing wrong, should be: `128*(2^(ceil(log2(ceil ( x /127)))))`, not `127 * ...`.

The way I usually think about it is `2^(ceil(log2(ceil(x+x/127)))`, which is basically rounding the padded size to the next power of two. The `128` appears since `x+x/127 = 128*x/127`, and then is just moving things to simplify to `128*(2^(ceil( log2(ceil(x /127)))))`.

---
Semi-related, I always found a bit odd that the API for making deals requires both unpadded and padded sizes depending on the field.

If you want to make a deal with provided Piece information (e.g: offline, or pre-calculated):
```
  // DataRef is a reference for how data will be transferred for a given storage deal                                                                                           
  type DataRef struct {                                                                                                                                                         
          TransferType string                                                                                                                                                   
          Root         cid.Cid                                                                                                                                                  
                                                                                                                                                                                
          PieceCid  *cid.Cid              // Optional for non-manual transfer, will be recomputed from the data if not given                                                    
          PieceSize abi.UnpaddedPieceSize // Optional for non-manual transfer, will be recomputed from the data if not given                                                    
  }  
```
So, should use the unpadded size. But for total deal cost calculation (`price*Gib*epoch`) the padded size should be used!

For `PieceSize` above, the good part is that is typed, so `abi.UnpaddedPieceSize` looks to be a good safeguard to not be confused. But for `EpochPrice big.Int`, the Padded/Unpadded dilemma gets diluted since the magnitude gets canceled by `price*GiB*epoch`, so isn't entirely clear what size should be used.

I think a better API could be supplying the three values separately, to expose the right type on each part, and let the API do the multiplication internally to not hide this important detail.

Of course, breaking the API now isn't nice. For most people using the CLI, I think the interactive mode automatically deals with all this, but taking a look at the API might not be entirely clear the correct usage.

**Comment by ribasushi** [comment]
> should be: 128*(2^(ceil(log2(ceil ( x /127))))), not 127 *

@jsign the docs are written in the context of https://github.com/filecoin-project/lotus/blob/v1.5.0/cli/client.go#L419-L424 which takes unpadded size, which ... yes, `127 *` is corret 🤦

**Comment by jsign** [comment]
> > should be: 128*(2^(ceil(log2(ceil ( x /127))))), not 127 *
> 
> @jsign the docs are written in the context of https://github.com/filecoin-project/lotus/blob/v1.5.0/cli/client.go#L419-L424 which takes unpadded size, which ... yes, `127 *` is correct

Cool, yep, so makes sense if it's for that field.

**Comment by johnnymatthews** [comment]
This is pretty in-depth, and potentially out-of-scope for this repo.

> Something lotus should be doing for the client in the first place, at least in interactive mode. - @ribasushi 

If this is the case, then we could drop the _Calculate the datasize_ section completely. Anything we can do to stop the user having to do math 😄

**Comment by rvagg** [comment]
Thanks @johnnymatthews, you're right, this is far too much info. And, looking properly at this doc, it's all [explained in the top section](https://github.com/filecoin-project/filecoin-docs/blob/master/docs/store/lotus/very-large-files.md#maximizing-storage-per-sector) anyway, with a table and all, and the "datasize" bit just muddies things. So +1 to just yeeting that entire section and letting them make appropriate inferences from that top section.

**Comment by johnnymatthews** [comment]
Nice, thanks @rvagg.

I've updated the title of this issue. Here's what we need to do:

## Tasks

- [ ] Remove the _Calculate the datasize_ section from `/docs/store/lotus/very-large-files.md`.
