### ISSUE TITLE
Add Mining section

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#71]
To coordinate with @angiemaguire. Here is a brief outline discussed with @ianjdarrow:

- what's involved in mining?
- how do i get started, hardware, etc.
- what's a deal, how do i accept deals
- how do i get block rewards
- quality and uptime - slashing, etc.

Can pull content from:
- FAQs: https://filecoin.io/faqs/#2-mining
- Notes from sync with mining team: https://docs.google.com/document/d/1P1OiqlmkN3hvBl-NFHHmTV_65OpLPurXtqkkhdDxmDI/edit

**Comment by mishmosh** [comment]
Some relevant user feedback via #fil-lotus (some may belong in lotu.sh docs):

From karam.eth "Write a detailed documentation of the mining storage steps, including screenshot reference of the code execution, which is convenient for the new miners."

From dayu: "How to use msig. How to make deal"

**Comment by har00ga** [comment]
@mishmosh the first link is dead, any idea what's up?

**Comment by mishmosh** [comment]
It got overwritten with the new website launch last week, but here's the original source code: https://github.com/filecoin-project/website/blob/master/content/faqs/_index.md#2-mining

**Comment by har00ga** [comment]
I get a 404 trying to view that, do I need permissions?

**Comment by har00ga** [comment]
Good to go, ty
