### ISSUE TITLE
Create a page on "Chain tools" under "Build apps".

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#73]
Add a "Chain Tools" page under "How tos" > Build apps. 

- Describe [sentinel](https://github.com/filecoin-project/sentinel), for chain data backends. Probably best to wait until @placer14 has finished the preliminary README (https://github.com/filecoin-project/sentinel/pull/3)
- Also list prior art. These were mostly built for older versions of filecoin, so not recommended for new projects but can serve as design reference.
  - [Lotus-chainwatch](https://github.com/filecoin-project/lotus/tree/master/cmd/lotus-chainwatch) for postgres (check on status & recommended usage, might be active)
  - Older example: Network Stats Dashboard project built a [chain listener/postgresdb](https://github.com/filecoin-project/filecoin-network-stats) called chainsaw. Uses outdated version of go-filecoin.

**Comment by johnnymatthews** [comment]
Hey @mishmosh, is this issue still relevant?

**Comment by johnnymatthews** [comment]
This issue is over a year old, and has had no updates for a while. Closing. If it's still relevant, feel free to re-open it.
