### ISSUE TITLE
Add link to next section from Simple Pinning Service index page.

### ISSUE THREAD

**Issue by Z0rlord** [filecoin-project/filecoin-docs#734]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

https://docs.filecoin.io/build/examples/simple-pinning-service/overview/

**What's wrong with this page?**

Text on page says:
"The next section describes Powergate and how it interacts with Lotus and go-ipfs nodes."

where is this next section? there is no link

**What would you like to have changed/amended/fixed in order to make things right?**
add link to continue

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

**Is there any other feedback you'd like to share about Filecoin docs?**

just getting started
 #gitcoin-bounty

**Comment by johnnymatthews** [comment]
That sentence should link to [Powergate and Its Interactions with Lotus and go-ipfs
](https://docs.filecoin.io/build/examples/simple-pinning-service/powergate-lotus-go-ipfs-interactions/#resources).

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Closing issue.
