### ISSUE TITLE
attempting to do the basic filecoin tutorial and link to tutorial is broken 

### ISSUE THREAD

**Issue by Z0rlord** [filecoin-project/filecoin-docs#735]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

#gitcoin-bounty

**URL of the page in question:**
https://github.com/filecoin-shipyard/powergate-pinning-service

**What's wrong with this page?**
link does not work https://github.com/filecoin-shipyard/powergate-pinning-service/blob/master

**What would you like to have changed/amended/fixed in order to make things right?**
link needs to work

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
Which page did you encounter this link on @Z0rlord?

**Comment by Z0rlord** [comment]
bottom of this page:  https://github.com/filecoin-shipyard/powergate-pinning-service

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Also this repo is for the documentation, not the pinning service example app itself - you may want to file this over there.
