### ISSUE TITLE
[DOCS ISSUE] Page: Overview no link to "next section"

### ISSUE THREAD

**Issue by Z0rlord** [filecoin-project/filecoin-docs#736]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/build/examples/network-inspector/overview/

**What's wrong with this page?**
text says "Before diving into the tutorial for this sample application, the next section gives you an understanding of how lotus and go-ipfs nodes interact."

but there is no link to next section

**What would you like to have changed/amended/fixed in order to make things right?**
_Again, the more specific you are, the easier/faster fixing this item can be._

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

**Is there any other feedback you'd like to share about Filecoin docs?**

#gitcoin-bounty

**Comment by johnnymatthews** [comment]
This sentence should link to https://docs.filecoin.io/build/examples/network-inspector/lotus-and-go-ipfs-interactions/#resources.

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Closing issue.
