### ISSUE TITLE
Reminder users about the "powergate-pinning-service" repo.

### ISSUE THREAD

**Issue by Z0rlord** [filecoin-project/filecoin-docs#748]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/build/examples/simple-pinning-service/step-3-connecting-powergate-to-app/#step-3a-connecting-to-the-powergate-instance

**What's wrong with this page?**
cannot find powergate pinning client project files and they are not linked:

"Use any text editor to open the **powergate-pinning-client project**. Multiple pages in the React app interact with the powergate instance.

**What would you like to have changed/amended/fixed in order to make things right?**
_link to project files

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

**Is there any other feedback you'd like to share about Filecoin docs?**

learning a ton thanks! 
#gitcoin-bounty

**Comment by johnnymatthews** [comment]
I believe the React App in question comes from here: https://github.com/filecoin-shipyard/powergate-pinning-service. This is listed at the top of the previous page. We should reminder users about the `powergate-pinning-service` repo at the top of _this_ page, just in case they missed it.

**Comment by Z0rlord** [comment]
awesome, thanks! #gitcoin-bounty

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Closing issue.
