### ISSUE TITLE
[DOCS ISSUE] Page: Step 3 - Connecting Powergate instance with React app

### ISSUE THREAD

**Issue by Z0rlord** [filecoin-project/filecoin-docs#754]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/build/examples/simple-pinning-service/step-3-connecting-powergate-to-app/#step-3b-connecting-to-the-pouchdb-instance

**What's wrong with this page?**
repo, text language and example pic confusing. Text says: "Use any text editor to open the powergate-pinning-client project. Multiple pages in the React app interact with the powergate instance." and example pic shows same but repo seems to call is "powergate-pinning-service"

this may not be an actual problem, as maybe client and service are the same here, but I don't know.

**What would you like to have changed/amended/fixed in order to make things right?**
make language clear and add link to repo

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

yes but would prob make more probs than I fix

**Is there any other feedback you'd like to share about Filecoin docs?**

loving learning more

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Closing issue.
