### ISSUE TITLE
IPFS + Filecoin How-tos

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#76]
Following up on the conceptual work added in #72, this issue is a placeholder for usage examples.

Reference links:
https://github.com/filecoin-project/lotus/pull/1843

**Comment by har00ga** [comment]
@mishmosh Who should I be buggin' for usecases to wrap this up?

**Comment by johnnymatthews** [comment]
Not sure what this issue is for. Can it be closed @mishmosh? If not, what's the work that need to be done?

**Comment by har00ga** [comment]
This still needs to be completed, it's for use case examples on the IPFS + Filecoin page under the introduction section

**Comment by johnnymatthews** [comment]
So, there's a bunch of use-case examples for IPFS on the [IPFS docs site](https://docs.ipfs.io/concepts/usage-ideas-examples/). These _might_ be useful for this issue.

**Comment by johnnymatthews** [comment]
[Examples currently exist here](https://docs.filecoin.io/build/examples/). Closing this issue.
