### ISSUE TITLE
[DOCS ISSUE] Page: Community

### ISSUE THREAD

**Issue by AndrewHamm** [filecoin-project/filecoin-docs#763]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/community/

**What's wrong with this page?**
The link to join slack is broken. Clicking the link takes you to a page which says "This link is no longer active".

This is more of a problem with the page https://filecoin.io/slack than this documentation page, but I'm not exactly sure what the best way to open an issue for that is.

**What would you like to have changed/amended/fixed in order to make things right?**
I would like https://filecoin.io/slack to go to a working invite link.

**Would you be interested in helping fix this page?**
I don't believe that I will have permission to fix this since we will likely need a new slack invite link from the workspace admin. I'm happy to help if I can though.

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
Do you not see this page when you go to https://filecoin.io/slack @AndrewHamm?

![image](https://user-images.githubusercontent.com/9611008/114587747-f31e4d00-9c53-11eb-861e-061852b9c1cb.png)

**Comment by AndrewHamm** [comment]
Seems like it is working now! Must've been fixed some other way.

**Comment by johnnymatthews** [comment]
Fair enough. Glad it's working now! It could've been an issue with the redirects, so we'll keep an eye on things.
