### ISSUE TITLE
[DOCS ISSUE] Page: Mining rewards

### ISSUE THREAD

**Issue by lurch** [filecoin-project/filecoin-docs#766]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/mine/mining-rewards/#retrieval-fees

**What's wrong with this page?**
It says "Retrieval fees are paid incrementally using payment channels as the retrieval deals are fulfilled (by sending portions of the data to the cl."

**What would you like to have changed/amended/fixed in order to make things right?**
Looks like perhaps "cl" should be "client"? And there's also no closing-bracket.

**Would you be interested in helping fix this page?**
No, as I don't know if there's additional text that is missing here.

**Is there any other feedback you'd like to share about Filecoin docs?**
None

**Comment by johnnymatthews** [comment]
Nice find. Added a PR #788.
