### ISSUE TITLE
Reword "memory" to "disk space" in Lotus seal worker.

### ISSUE THREAD

**Issue by UltraVis** [filecoin-project/filecoin-docs#767]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/mine/lotus/seal-workers/#resource-windows

**What's wrong with this page?**
What is the difference between "Min RAM" and "Min Memory" in the  "Task resource table" ? Or is that a typo?

**What would you like to have changed/amended/fixed in order to make things right?**
update the table if there is any error....

**Would you be interested in helping fix this page?**
sure! but I don't know the answer...

**Is there any other feedback you'd like to share about Filecoin docs?**
Is there a 2nd person reviewing / proof-reading the Docs and Blogs?

**Comment by johnnymatthews** [comment]
This is a good point. We should reword _memory_ to _disk space_.
