### ISSUE TITLE
[DOCS ISSUE] Page: Meme Marketplace Overview

### ISSUE THREAD

**Issue by Z0rlord** [filecoin-project/filecoin-docs#769]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/build/examples/meme-marketplace/overview/

**What's wrong with this page?**
text at bottom of page says:

"Before diving into the tutorial for this sample application, the following section provides an understanding of Textile Hub and ERC 721 standard token contract."

but there is no following section

**What would you like to have changed/amended/fixed in order to make things right?**
there needs to be a link to the actual tutorial. is there an existing tutorial?
![Screenshot from 2021-03-29 11-57-18](https://user-images.githubusercontent.com/32578867/112864816-31c5dc00-9086-11eb-88ac-657e14c54994.png)

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

**Is there any other feedback you'd like to share about Filecoin docs?**

#gitcoin-bounty

**Comment by johndmulhausen** [comment]
This example has been removed from the docs due to staleness. We are going to regroup and review our example app strategy. Closing issue.
