### ISSUE TITLE
error in RPC call

### ISSUE THREAD

**Issue by Jiangxianbin** [filecoin-project/filecoin-docs#775]
lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car

call    lotus wallet list
 

WARN    rpc     go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:279  error in RPC call to 'Filecoin.StateGetActor': resolution lookup failed (f3vkxarlwbqpwi35qe2xsos7pkncjlpynlvbpcidukh4yiuxg23y4w65dfnv5cr2i3gr6ug2oggqtlwkuio7uq):
    github.com/filecoin-project/lotus/chain/state.(*StateTree).GetActor
        /root/lotus/chain/state/statetree.go:318
  - resolve address f3vkxarlwbqpwi35qe2xsos7pkncjlpynlvbpcidukh4yiuxg23y4w65dfnv5cr2i3gr6ug2oggqtlwkuio7uq:
    github.com/filecoin-project/lotus/chain/state.(*StateTree).lookupIDinternal
        /root/lotus/chain/state/statetree.go:283
  - actor not found

**Comment by johnnymatthews** [comment]
Support issues are best placed over in the [Lotus discussion boards](https://github.com/filecoin-project/lotus/discussions).
