### ISSUE TITLE
Explain how to deal with browsers enforcing a single-origin policy.

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#81]
This is a placeholder issue for now.

## Problem
Browsers enforce a single-origin policy. Any Filecoin web app (that you access via a browser) is affected by this.

If your node is hosted on mylotusnode.com, the JS running on github.com can't read data from mylotusnode.com. A few workarounds exist, such as websockets, CORS headers, or reverse proxy, though they open security vulnerabilities.

## Workarounds & Solutions

Lotus gives you an HTTP import REST endpoint, but it can't be used from another domain. 

Reverse proxy (caddyserver — preferred one to document since modern, golang, several PL contributors; nginx is more popular; apache)

If you're using the IPFS integration, the IPFS daemon lets you add CORS headers. So you could perform an import & storage operation via the IPFS daemon, then use websockets for lotus.

@jimpick has started documenting this here:
https://ipfs.io/ipfs/QmRRp9Y5i6d3Lkf4UbNvnhtaNqyaB4jnALuJ2vcHnVpphL/endpoint-deployment.html

## Longer-term solutions

- Lotus could support CORS headers, though that's adding features/possible bloat.
- Other considerations including where tokens live, security, etc.

**Comment by johnnymatthews** [comment]
Gonna close this placeholder issues since it's pretty old. Feel free to open it again if there's been some changes and/or more exit conditions are created.
