### ISSUE TITLE
export and import key not working

### ISSUE THREAD

**Issue by RealLau** [filecoin-project/filecoin-docs#814]
- version
    - lotus
        ```shell
         Daemon:  1.6.0-rc1+calibnet+git.f357530ef+api1.1.0
         Local: lotus version 1.6.0-rc1+calibnet+git.f357530ef
        ```
    - OS
        ``` Mac OSX Big Sur 11.2.3```
- operation
    just like documented [here](https://docs.filecoin.io/get-started/lotus/send-and-receive-fil/#exporting-and-importing-addresses) 
    - ```lotus wallet export <address> <address>.key``` and output is a *hash* like string with length 148. Tried to find a file named _address_.key(`sudo find / -name *.key`) with no luck.
    - ```lotus wallet import <hash> ``` generated before and the output is ```ERROR open <hash>: no such file or directory```
   

How can I resolve this, or I make a misunderstanding?

**Comment by johnnymatthews** [comment]
The command you need to run is:

```shell
lotus wallet export <address> > <filename>
```

For example:

```shell
lotus wallet export f1ne4kbuqed3faluu4ky4x4ygvksjmw7uzpyq5h5y > exported-key-file.key
```

This creates a file called `exported-key-file.key` in the same directory that I ran the command in.

Judging by your comment, it looks like you're missing a right bracket `>`.
