### ISSUE TITLE
Add high-level wallet address documentation.

### ISSUE THREAD

**Issue by autonome** [filecoin-project/filecoin-docs#816]
Is there an item missing from Filecoin documentation that would be helpful to you? Please use this template to let us know!

**What's the subject of the item you're requesting?**
Filecoin wallet addresses

This should be a high-level overview of wallet types (talking about `actors` without ever using the term), use-cases and examples of what each looks like (f1, f2... etc)

The [spec](https://spec.filecoin.io/appendix/address/) has the technical details but is not designed for end users.

**What's the content of the item you're requesting?**
1. the types of wallet addresses
2. how to recognize each, and what they are used for
3. are you using the right one for what you want to do?

**What will the user know how to do after going through this item?**

see above

**Would you be interested in helping create this item?**

**Is there any other feedback you'd like to share about Filecoin docs?**

yes, thank you

**Comment by olizilla** [comment]
pls sir i call them actors but i just wanted to avoid creating another bit of terminology https://github.com/filecoin-project/filecoin-docs/pull/653

**Comment by olizilla** [comment]
I wasn't clear when writing #653 what, if anything "a wallet" really is in Filecoin-land. My assumption is it's software that uses Filecoin and probably manges (or accesses via a Ledger device) the keys for an `f1` or `f3` account actor.

As far as I can tell the only entity that really exists in Filecoin is an "actor", of which some are "account actors" which can be controlled directly by users via keys. Users would probably think of them as wallets, but it would be good to get that clarified.

**Comment by autonome** [comment]
We have a wallets reference page, so it seems like it is a thing:
https://docs.filecoin.io/reference/#wallets

Maybe I'm asking for a page that is about the addresses in the context of
wallet usage?

**Comment by johnnymatthews** [comment]
@yusefnapora is gonna tackle this one. Annoying I have to tag him in a comment before I can assign him to the task. Silly GitHub.

**Comment by yusefnapora** [comment]
odd indeed... anyway I am working on this but it will be Monday before I've got anything worth pushing up
