### ISSUE TITLE
lotus demon restart error

### ISSUE THREAD

**Issue by 196918327** [filecoin-project/filecoin-docs#821]
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/develop/test/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): genesis in the repo is not the one expected by this version of Lotus!

**Comment by johnnymatthews** [comment]
Looks like this is a support request. Head over to the [discussions tab in the Lotus repo](https://github.com/filecoin-project/lotus/discussions) to get support from the Lotus team.
