### ISSUE TITLE
[DOCS ISSUE] Page: Store data on Filecoin

### ISSUE THREAD

**Issue by DamianSiniakowicz** [filecoin-project/filecoin-docs#824]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
_e.g. https://docs.filecoin.io/introduction/usage/_

https://docs.filecoin.io/store/

**What's wrong with this page?**
_Please be as specific as possible. If relevant, screenshots are helpful!_

Something is wrong with Space Storage
The sign up link on their site doesn't work.
https://space.storage/signup/

**What would you like to have changed/amended/fixed in order to make things right?**
_Again, the more specific you are, the easier/faster fixing this item can be._

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
This is an issue for the [Fleek team](https://github.com/FleekHQ). Closing.
