### ISSUE TITLE
为什么中文网站的字体这么奇怪？[DOCS ISSUE] (add your title here!)

### ISSUE THREAD

**Issue by MRJAVAZHAO** [filecoin-project/filecoin-docs#829]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://filecoin.filgo.info/about-filecoin/how-filecoin-works/#%E9%99%84%E5%8A%A0%E6%9D%90%E6%96%99

**What's wrong with this page?**
这个网站的字体为什么这个奇怪？
![image](https://user-images.githubusercontent.com/47096545/117403066-28a81480-af3a-11eb-8fbc-afe4cbe39aae.png)

**What would you like to have changed/amended/fixed in order to make things right?**
字体为常规的黑体就可以了

**Would you be interested in helping fix this page?**
no

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
The `filgo.info` domain is not managed by this repository. docs.filecoin.io is manged by Protocol Labs and FIlecoin. Any other sites are not managed by this repo. Closing.
