### ISSUE TITLE
Add a link to the protocol labs tutorials on the How mining works page

### ISSUE THREAD

**Issue by smith-phil** [filecoin-project/filecoin-docs#831]
**URL of the page in question:**
https://docs.filecoin.io/mine/how-mining-works/#types-of-miners

**What's wrong with this page?**
It doesn't include a link to the protocol labs filecoin tutorial.

**What would you like to have changed/amended/fixed in order to make things right?**
The **How mining works** section could include a link to https://proto.school/tutorials?course=filecoin, along with some text explaining that it will give a user a better understanding of the topics discussed on the docs page. Users who choose to complete some or all of the tutorials will have a better high level understanding of how mining works. This would help them as they move through the rest of the documentation.

Something along the lines of 
> A better understanding of how mining works can be developed by completing the Protocol Labs [Filecoin tutorials](https://proto.school/tutorials?course=filecoin).

**Would you be interested in helping fix this page?**
Yes. I can submit a pull request right now, but I'd like to get feedback on the additional text before I do.

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by smith-phil** [comment]
Is the additional text suggested okay as is or should I change it?

**Comment by johnnymatthews** [comment]
Yeah that's a good idea. The best solution would be to add something like this to the top of the `/mine/how-mining-works` page:

```markdown
:::tip ProtoSchool tutorial available
Take a look at the [Filecoin Tutorial over at ProtoSchool](https://proto.school/verifying-storage-on-filecoin) to get a better understanding of how mining works.
:::
```

If you're available to make a PR here @smith-phil we'd really appreciate it! I'll assign you to this issue. Feel free to unassign yourself if you're busy right now though :)

**Comment by smith-phil** [comment]
[Pull request #842](https://github.com/filecoin-project/filecoin-docs/pull/842) created.
