### ISSUE TITLE
No link to the API overview or method list

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/filecoin-docs#844]
https://docs.filecoin.io/build/get-started/ seems to have no link to an api method overview whatsoever

**Comment by johnnymatthews** [comment]
What link are you expecting to see here @f8-ptrk? There's links to the Infura homepage, and to the Infura Filecoin API docs.

![image](https://user-images.githubusercontent.com/9611008/118288327-50e7c400-b4a2-11eb-8383-bd3abc1fb935.png)

If you're expecting to see a link to somewhere else, we can add it in.

**Comment by f8-ptrk** [comment]
i expected a link to the raw version without a 3rd party tool. i know there is some kind of list somewhere of all the rpc methods for http rpc - i cannot find it

**Comment by johnnymatthews** [comment]
Ah I see; yeah that makes sense. So you'd like to see a link or a call out to the [Lotus API Methods under the **Reference** section](https://docs.filecoin.io/reference/lotus-api)? That's a fair idea.

## Tasks

- [ ] Add a paragraph or callout pointing users to the [Lotus API methods](https://docs.filecoin.io/reference/lotus-api) in the **Get started** section.

**Comment by f8-ptrk** [comment]
hola! there they are :D

i think in the get started and/or build section a prominent placement will not hurt!

**Comment by johnnymatthews** [comment]
Fixed in #885.
