### ISSUE TITLE
External Deal filter documentation seems to have vanished

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/filecoin-docs#849]
https://docs.filecoin.io/mine/lotus/manage-storage-deals

this site once included a documentation for the external deal filter feature - did it more or is it gone?

i remember it to be here:

https://docs.filecoin.io/mine/lotus/manage-storage-deals/#blocking-storage-deals-by-piececid

**Comment by f8-ptrk** [comment]
https://docs.filecoin.io/mine/lotus/miner-configuration/#using-filters-for-fine-grained-storage-and-retrieval-deal-acceptance

it's here. maybe move that into the deal making section of the miner?

**Comment by atopal** [comment]
Thanks for the feedback. We have discussed this and decided to leave this where it is. Please feel free to re-open, if you have more info.

**Comment by RobQuistNL** [comment]
Now neither work
