### ISSUE TITLE
APIstruct import  in Go JSON-RPC example no longer exists.

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/filecoin-docs#852]
"github.com/filecoin-project/lotus/api/apistruct"

imported in the example seems to not exist anymore.

i will confirm if the example still works or not

**Comment by johnnymatthews** [comment]
@hsanjuan might have some ideas on how to fix this example.

**Comment by hsanjuan** [comment]
git blame points to @magik6k . See https://github.com/filecoin-project/lotus/commit/7a23b411ae988c644f3160afe7ee5703d092a444

**Comment by longfeiWan9** [comment]
@johnnymatthews This one is actually being fixed in [PR-964](https://github.com/filecoin-project/filecoin-docs/pull/964).

**Comment by johnnymatthews** [comment]
Looks like you're right @longfeiWan9! Nice catch!
