### ISSUE TITLE
Lolotus-miner info：      ERROR: websocket: bad handshaketus Miner: troubleshooting

### ISSUE THREAD

**Issue by baysmall1** [filecoin-project/filecoin-docs#867]
execute  **lotus-miner start**  after   : JWT Verification failed (originating from 192.168.2.79:58304): JWT Verification failed: jwt: HMAC verification failed

 execute  **Lolotus-miner info**：      ERROR: websocket: bad handshaketus Miner: troubleshooting

How to solve this problem？

**Comment by johnnymatthews** [comment]
You might be better off posting this error over at the [Lotus discussion forum](https://github.com/filecoin-project/lotus/discussions/categories/miner-q-a).
