### ISSUE TITLE
[DOCS ISSUE] How can I validate miner?

### ISSUE THREAD

**Issue by erdemeserekinci** [filecoin-project/filecoin-docs#880]
It is not clear how to validate my miner and how to relate the miner with wallet? 

Additionally, there is no link to find brief info about the metric of mining rewards.

**Comment by johnnymatthews** [comment]
I'm not really sure what you're asking. If you're looking for support, you should take a look at the [Lotus discussion tab](https://github.com/filecoin-project/lotus/discussions), specifically the [Miner Q&A section](https://github.com/filecoin-project/lotus/discussions/categories/miner-q-a).
