### ISSUE TITLE
"Offline deals" is missing information.

### ISSUE THREAD

**Issue by William8Work** [filecoin-project/filecoin-docs#882]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/store/lotus/very-large-files/#deals-with-offline-data-transfer

**What's wrong with this page?**
I was trying to create a new offline deals as a client. the document steps were good, except there is one information is missing.

1. First of all, I run this to generate car file: `lotus client generate-car dataset.zip dataset.car`
2. Then, get the piece CID through `lotus client commP dataset.car`
3. According to this https://docs.filecoin.io/store/lotus/very-large-files/#generate-a-unique-piece-cid, I would need to propose the offline deal with the miner: `lotus client deal --manual-piece-cid=CID --manual-piece-size=datasize <Data CID> <miner> <price> <duration>`. Problem is: how to create the  `<Data CID>`?

Looks like `lotus client import --car dataset.car` will create a data CID but is that for online deals or offline deals?

**What would you like to have changed/amended/fixed in order to make things right?**
Add the step to allow the client create data CID in the section of Calculate the Data Size to show the command of client import --car <car file>.

**Comment by johnnymatthews** [comment]
Ah ok, thanks for flagging this. Looks like we need to review the Offline Deals process.

**Comment by superkaiy** [comment]
> Ah ok, thanks for flagging this. Looks like we need to review the Offline Deals process.
so, any update?
