### ISSUE TITLE
Properly explain how to turn off multicore SDR as soon as the update (assumed v1.10.0) is released

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/filecoin-docs#894]
see: https://github.com/filecoin-project/lotus/issues/6450

this will flip the logic on how multicore SDR is used. from opt in to opt out.

please make sure the documentation is up to date with this change as soon as the update gets released. 

multicore SDR doesn't improve speed on all processors and especially early setups designed for single core processing will see decreasing PC1 speed if they do not opt out

**Comment by yusefnapora** [comment]
This is the only mention of multicore SDR I could find in a quick grep through the docs site: https://docs.filecoin.io/mine/lotus/seal-workers/#task-resource-table

Seems like it could also go into https://docs.filecoin.io/get-started/lotus/installation/#build-and-install-lotus 

@f8-ptrk is there a simple criteria we can give for whether to opt out? e.g. "if your processor doesn't support instruction XYZ, you should set this flag to opt out".

**Comment by f8-ptrk** [comment]
if a processor doesn't have more then 1 core per CCD --> AMD 7f32 (if you look at the PL test setup - the one they aare using there for PC1)
