### ISSUE TITLE
Review the "dynamic retrieval pricing" branch.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#895]
The Lotus team is building documentation surrounding dynamic retrieval pricing. The branch they're using is `feat/dynamic-retrieval-pricing`. The file to change is `docs/mine/lotus/dynamic-retrieval-pricing.md`.

Once they've finished their draft we need to go through and tidy things up a bit. Can't really add tasks to this issue until there's something to look over in the branch.

**Comment by atopal** [comment]
Here's the draft for the dynamic retrieval pricing: https://github.com/filecoin-project/lotus/pull/6175#issuecomment-860374944
