### ISSUE TITLE
[DOCS ISSUE] Page: Lotus: node troubleshooting

### ISSUE THREAD

**Issue by jick68** [filecoin-project/filecoin-docs#906]
![image](https://user-images.githubusercontent.com/25079070/122390454-02fe2a00-cf40-11eb-999b-c09e940f36bc.png)

no troubleshooting guide recommend for the bug captured in screenshot

---

1. installed lotus
2. installed ipfs
3. synced to chain
4. pinned ipfs CID
5. attempt to form a deal
6. ERROR: failed to start deal: computing commP failed: generating CommP: blockstore: block not found

**Comment by jick68** [comment]
if block not found, then data is not being found in lotus, if this is due to using IPFS cid, then must double check that config was loaded.
```bash
lotus daemon stop
lotus daemon --config=~/.lotus/config.toml
```

**Comment by jick68** [comment]
tks filecoin team! really appreciate everyone's work here!

**Comment by johnnymatthews** [comment]
Sorry you're having trouble @jick68. The best place to get support with Lotus issues is the [discussion section of the filecoin-project/lotus repo](https://github.com/filecoin-project/lotus/discussions).
