### ISSUE TITLE
[DOCS ISSUE] Page: Lotus: store data

### ISSUE THREAD

**Issue by cobycloud** [filecoin-project/filecoin-docs#908]
problem: 
    documentation does not explain what price is... this discrepancy and lack of information costs users in transactions fees as they must learn through trial and error

question to answer:
* is price in FIL or in attoFIL?

how to improve:
* update the documentation with more detailed explanation of lotus deal command and its parameters

**Comment by jick68** [comment]
Another way of phrasing this is that the documentation does not provide the unit measurement of "price"

is it fil/TiB, or attofil/GiB, or attofil/GiB/block, so on?

this may seem intuitive, but it should be clearly documented in this page here

**Comment by johnnymatthews** [comment]
I'm not quite sure what information you're looking for. Filecoin docs has a section on [Managing assets](https://docs.filecoin.io/about-filecoin/managing-assets) that details the different denominations of FIL.
