### ISSUE TITLE
[DOCS ISSUE] Page: Filecoin Plus

### ISSUE THREAD

**Issue by ryanemax** [filecoin-project/filecoin-docs#948]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/store/filecoin-plus/

**What's wrong with this page?**
There is no description of how miners who complete FIL+ deals are rewarded 10 times. 
How to distinguish between ordinary revenue and FIL+ revenue?

**What would you like to have changed/amended/fixed in order to make things right?**
Looking forward to further answers from the authorities

**Would you be interested in helping fix this page?**
Yes, If I figure out how to check FIL+ revenue as an miner, I will share it with others.

**Is there any other feedback you'd like to share about Filecoin docs?**
It's fine.

**Comment by johnnymatthews** [comment]
There's this line in the [Filecoin Plus page](https://docs.filecoin.io/store/filecoin-plus/#concepts)

> Storage Providers that receive DataCap receive a 10x boost to their quality-adjusted power for the storage space offered in that deal

There's also this line further down the page under the [DataCap section](https://docs.filecoin.io/store/filecoin-plus/#concepts):

> which increases the "quality adjusted power" of the storage provider on the network by a factor of 10

Do these two lines not address your questions?
