### ISSUE TITLE
Change `lotus client retrieve` command in Store & Retrieve tutorial.

### ISSUE THREAD

**Issue by momack2** [filecoin-project/filecoin-docs#949]
I really enjoyed the tutorial! Unfortunately, my retrieval deal failed the first time. Can we have the steps here to cancel a failed retrieval deal correctly? I flailed a bit - I think my successful action was using the "list-transfers" and "cancel-transfer" commands to clear things out. I wasn't able to successfully use the "cancel-retrieval" command I don't think (I tried using the deal-id https://filecoin.tools/2081795 but got `ERROR: failed to cancel retrieval deal: loadOrCreate state: saving initial state: failed to write cid field t.PayloadCID: undefined cid`)

**Comment by terichadbourne** [comment]
Thanks for flagging, @momack2! 

@atopal I'll leave this to you for prioritization amongst other work during our FFF pause.

**Comment by momack2** [comment]
(fyi `lotus client retrieve --miner f07709 mAVWg5AIgFw51hfKzfy8nRsKHlMtT8/DPBJhn1f9eFyOSeldlAiE output-file-1` worked for me and was only 66KB!)

**Comment by johnnymatthews** [comment]
Having a tiny `66kb` file to retrieve is _super useful_! Let's add @momack2's command into the tutorial and make sure that the miner it's store with is reliable.

@momack2 , can you remember what the file actually is? Or just a bunch of random data?
