### ISSUE TITLE
US English is not the most common

### ISSUE THREAD

**Issue by getsnoopy** [filecoin-project/filecoin-docs#962]
**URL of the page in question:**
https://docs.filecoin.io/community/contribute/grammar-formatting-and-style/#grammar-and-spelling

**What's wrong with this page?**
The page reads: 
> While Filecoin is a global project, the fact is that American English is the most commonly used style of English used today.

This is simply not true. Of [all of the English speakers of the world](https://en.wikipedia.org/wiki/List_of_countries_by_English-speaking_population), those which use US English [constitute around 24%](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences). The rest of the world uses either international (Oxford) English or Commonwealth English, which make up the rest of the 76%.

**What would you like to have changed/amended/fixed in order to make things right?**
If Filecoin (and the *InterPlanetary* File System that it's based on) is to be a global project, a global standard should be used. That standard is [Oxford English](https://en.wikipedia.org/wiki/Oxford_spelling), which is known worldwide as international English and is taught as *the* standard. The UN, ISO, IEC, NATO, WTO, BIPM, WWF, and practically every other international organization use it as the standard. *Even the [original Bitcoin white paper](https://bitcoin.org/bitcoin.pdf) uses Oxford English.* It is also taught to millions of people worldwide.

**Would you be interested in helping fix this page?**
Yes, definitely. If approved, I can fix all of the docs in one fell swoop. It's also easy for others to help as well since it just so happens that writing in this locale is very easy, as Google Chrome already supports spellchecking in it via the `English (United Kingdom, Oxford English Dictionary spelling)` locale.

**Is there any other feedback you'd like to share about Filecoin docs?**
Similarly, all standards (date formats, etc.) should also be changed to their international equivalents so that it is as accessible as possible.

**Comment by johnnymatthews** [comment]
Fair enough. From this point onwards we can start to use UK English as the writing style of Filecoin docs. Closing.
