### ISSUE TITLE
Currencies symbols and codes are prefixed, not suffixed

### ISSUE THREAD

**Issue by getsnoopy** [filecoin-project/filecoin-docs#963]
**URL of the page in question:**
https://docs.filecoin.io/community/contribute/grammar-formatting-and-style/#references-to-filecoin

**What's wrong with this page?**
It says:
> These symbols can be used as suffixes or prefixes, as seen fit:
> Unit prefix: **100 FIL**.
> Unit suffix: **FIL 100**.
> Symbol prefix: **⨎100**.
> Symbol suffix: **100 ⨎**.

**What would you like to have changed/amended/fixed in order to make things right?**
In English, [all currency symbols and codes](https://en.wikipedia.org/wiki/ISO_4217#Position_of_ISO_4217_code_in_amounts) are [prefixed to the amount](https://www.govinfo.gov/content/pkg/GPO-STYLEMANUAL-2016/pdf/GPO-STYLEMANUAL-2016.pdf#page=252), not suffixed, with symbols being unspaced and codes being spaced. The rows where the code and the symbol are suffixed (i.e., `100 FIL` and `100 ⨎`) should be removed, as these are not correct in English. The other ones should have information added to them to require a space between the code and the amount, and no space between the symbol and the amount.

**Would you be interested in helping fix this page?**
Yes, definitely. Once agreed upon, I can change this guidance and any instances of the currency amounts throughout the docs.

**Is there any other feedback you'd like to share about Filecoin docs?**
No.

**Comment by Blazing-Mike** [comment]
So the suffixes should be removed and prefixes should be used throughout right?.  Using this statement to compare suffixes and prefixes;

Statement 1
" The Filecoin research group is giving 100 FIL/ 100 ⨎  to each participant of the hackathon." 

Statement 2
" The Filecoin research group is giving FIL 100 / 100 ⨎  to each participant of the hackathon."

We can look at the two statements as correct  but sticking to one ( and I suggest the prefix will ensure consistency throughout).
 Just like one dollar is $1 and not 1$ or 1 dollar , so I think this is reasonable. So we should have
 FIL 100 and  ⨎100 .
