### ISSUE TITLE
Dead link on https://docs.filecoin.io/mine/lotus/miner-addresses/#the-owner-address

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/filecoin-docs#977]
https://docs.filecoin.io/mine/get-started/lotus/ledger this link leads no where anymore

**Comment by johnnymatthews** [comment]
Looks like it should go to `/get-started/lotus/ledger/`.

**Comment by f8-ptrk** [comment]
confirmed to work at /get-started/lotus/ledger/
