### ISSUE TITLE
Lotus DAG store documentation

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/filecoin-docs#993]
**What's the subject of the item you're requesting?**
The Lotus DAG store

_This is targeted for the next release of Lotus after 1.11.1, presumably in 1.11.2_

**What's the content of the item you're requesting?**
The DAG store is a sharded store to hold large IPLD graphs efficiently, packaged as location-transparent attachable CAR files, with mechanical sympathy. We're aiming to have documentation that:
- Clarifies what the DAG store is and what value it provides to users
- How to migrate to the DAG store.
- Operators docs on how to setup and manage the DAG store
- Troubleshooting / FAQs (We'll be leveraging data we've been and will be gathering via testing with MinerX fellows)

**What will the user know how to do after going through this item?**
What the DAG store is, how to migrate to it and use it, along with helpful tips on troubleshooting any issues. 

**Would you be interested in helping create this item?**
Yes, we'll be creating PRs leading up to the 1.11.2 RC (tentatively Aug 17), reviews from the docs team will be very appreciated.

**Comment by momack2** [comment]
Might this be a good issue for a launchpad participant to pick up?

**Comment by jacobheun** [comment]
This is actually done, https://lotus.filecoin.io/docs/storage-providers/dagstore/, forgot to close this out 🤦
