### ISSUE TITLE
https://docs.filecoin.io/get-started/#filecoin-implementations is not accurate

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/filecoin-docs#997]
Venus for example has no implementation of markets. 

Please revisit the page and talk to people with knowledge of the matter what is really implemented within each filecoin protocol implementation.

**Comment by johnnymatthews** [comment]
The table in [Get started](https://docs.filecoin.io/get-started/#filecoin-implementations) shows Venus as pending implementation for Markets. Closing.
